// Generated by scaffold-enum-sync — DO NOT EDIT BY HAND. Re-run if backend enum changes.

/**
 * course_level — generated by scaffold-enums-from-spec from PROJECT_DATABASE.md.
 */
export enum course_level {
  BEGINNER = 1,
  INTERMEDIATE = 2,
  ADVANCED = 3,
}
