// Generated by scaffold-enum-sync — DO NOT EDIT BY HAND. Re-run if backend enum changes.

/**
 * order_status — generated by scaffold-enums-from-spec from PROJECT_DATABASE.md.
 */
export enum order_status {
  PENDING = 0,
  PAID = 1,
  CANCELLED = 2,
  REFUNDED = 3,
}
