/** Generated by scaffold-crud-pages. Query hooks for OrderItem.
 *
 * Every read is a `useQuery`, every write a `useMutation` that invalidates the
 * domain on success. Nothing here re-fetches by hand — the invalidation IS the
 * refresh, which is what keeps two screens from disagreeing about one record.
 */
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { qk } from '~/queries/keys';
import {
  fetchOrderItemList,
  fetchOrderItemById,
  createOrderItem,
  updateOrderItem,
  deleteOrderItem,
  type FetchOrderItemListParams,
} from '~/services/httpServices/orderItemService';
import type { CreateOrderItemRequest, UpdateOrderItemRequest } from '~/types/order-item';

const DOMAIN = 'orderItem';

export function useOrderItemList(params?: FetchOrderItemListParams) {
  return useQuery({
    queryKey: qk.list(DOMAIN, params),
    queryFn: () => fetchOrderItemList(params),
  });
}

export function useOrderItem(id: string | undefined) {
  return useQuery({
    queryKey: qk.detail(DOMAIN, id ?? ''),
    queryFn: () => fetchOrderItemById(id as string),
    enabled: Boolean(id),
  });
}

export function useCreateOrderItem() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (body: CreateOrderItemRequest) => createOrderItem(body),
    onSuccess: () => qc.invalidateQueries({ queryKey: qk.all(DOMAIN) }),
  });
}

export function useUpdateOrderItem() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: ({ id, body }: { id: string; body: UpdateOrderItemRequest }) =>
      updateOrderItem(id, body),
    onSuccess: (_data, { id }) => {
      qc.invalidateQueries({ queryKey: qk.detail(DOMAIN, id) });
      qc.invalidateQueries({ queryKey: qk.list(DOMAIN) });
    },
  });
}

export function useDeleteOrderItem() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (id: string) => deleteOrderItem(id),
    onSuccess: () => qc.invalidateQueries({ queryKey: qk.all(DOMAIN) }),
  });
}
