/** Generated by scaffold-crud-pages. Query hooks for User.
 *
 * Every read is a `useQuery`, every write a `useMutation` that invalidates the
 * domain on success. Nothing here re-fetches by hand — the invalidation IS the
 * refresh, which is what keeps two screens from disagreeing about one record.
 */
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { qk } from '~/queries/keys';
import {
  fetchUserList,
  fetchUserById,
  createUser,
  updateUser,
  deleteUser,
  type FetchUserListParams,
} from '~/services/httpServices/userService';
import type { CreateUserRequest, UpdateUserRequest } from '~/types/user';

const DOMAIN = 'user';

export function useUserList(params?: FetchUserListParams) {
  return useQuery({
    queryKey: qk.list(DOMAIN, params),
    queryFn: () => fetchUserList(params),
  });
}

export function useUser(id: string | undefined) {
  return useQuery({
    queryKey: qk.detail(DOMAIN, id ?? ''),
    queryFn: () => fetchUserById(id as string),
    enabled: Boolean(id),
  });
}

export function useCreateUser() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (body: CreateUserRequest) => createUser(body),
    onSuccess: () => qc.invalidateQueries({ queryKey: qk.all(DOMAIN) }),
  });
}

export function useUpdateUser() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: ({ id, body }: { id: string; body: UpdateUserRequest }) =>
      updateUser(id, body),
    onSuccess: (_data, { id }) => {
      qc.invalidateQueries({ queryKey: qk.detail(DOMAIN, id) });
      qc.invalidateQueries({ queryKey: qk.list(DOMAIN) });
    },
  });
}

export function useDeleteUser() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (id: string) => deleteUser(id),
    onSuccess: () => qc.invalidateQueries({ queryKey: qk.all(DOMAIN) }),
  });
}
