// Generated by scaffold-page-from-story from user_stories/A-02-signup.yaml
// Story: US-A-02-SIGNUP
// Role:  all
// Feature: Registration (student accounts)
// Goal: As a visitor I can create an account and say whether I am here to learn or to teach so that I land with the right role.
//
// Restyled by convert-pages to mirror design/html/student/A-02-signup.html.
// Scope-locked parts preserved: every data-testid, the SignUpPage default
// export, and the createRegister1 fetch wiring. The proto's
// single card maps AC-1 (learn) / AC-2 (teach) through the "I want to" select;
// the form (ac-1) nests inside a transparent ac-2 wrapper so BOTH wirings read
// the same fields (fullName, email, password).

import { useState } from 'react';
import { Link, useNavigate } from 'react-router';
import { useTranslation } from 'react-i18next';
import { useAppDispatch } from '~/hooks/useAppDispatch';
import { signupThunk } from '~/services/httpServices/authService';
import { toast } from '~/lib/toast';
import { getApiErrorMessage } from '~/utils/apiError';
import { FieldError, fieldProps } from '~/components/shared/FieldError';
import { email as emailRule, password as passwordRule, readForm, required, serverFieldErrors, validate, type FieldErrors } from '~/utils/validation';
import { AuthPanel } from '~/components/shared/AuthPanel';

export default function SignUpPage() {
  const { t } = useTranslation('common');
  const navigate = useNavigate();
  const dispatch = useAppDispatch();

  const [error, setError] = useState<string | null>(null);
  const [errors, setErrors] = useState<FieldErrors>({});

  const [loading1, setLoading1] = useState<boolean>(false);
  const createRegister1 = async () => {
    // The password rule here is the one the API enforces, word for word — a
    // form that accepts a password the server rejects just moves the rejection
    // one round trip later.
    const values = readForm(document.querySelector('[data-testid="a-02-signup-ac-1"]'));
    const found = validate(values, {
      fullName: [required(t('auth.signup.fullName', { defaultValue: 'Full name' }))],
      email: [required(t('auth.email', { defaultValue: 'Email' })), emailRule()],
      password: [required(t('auth.password', { defaultValue: 'Password' })), passwordRule()],
    });
    setErrors(found);
    if (Object.keys(found).length) {
      document.querySelector<HTMLElement>(`[name="${Object.keys(found)[0]}"]`)?.focus();
      return;
    }
    setLoading1(true);
    setError(null);
    const __body: Record<string, unknown> = {};
    if (typeof document !== 'undefined') {
      const __sect = document.querySelector('[data-testid="a-02-signup-ac-1"]');
      __sect?.querySelectorAll('input, textarea, select').forEach((el) => {
        const __el = el as HTMLInputElement; const n = __el.name; const v = __el.value;
        if (n && v) __body[n] = __el.type === 'number' ? Number(v) : v;
      });
    }
    try {
      const email = String(__body.email ?? '');
      const password = String(__body.password ?? '');
      // SignupDto requires fullName (@IsNotEmpty @MinLength(2)) alongside email/password
      // and an optional numeric role; omitting fullName 400s on every signup.
      const fullName = String(__body.fullName ?? '');
      await dispatch(signupThunk({ fullName, email, password })).unwrap();
      toast.success(t('auth.signup.success', { defaultValue: 'Account created' }));
      navigate('/');
    } catch (err) {
      setErrors(serverFieldErrors(err));
      const message = getApiErrorMessage(err, t('auth.signup.failure', { defaultValue: 'Could not create the account' }));
      setError(message);
      toast.error(message);
    } finally {
      setLoading1(false);
    }
  };
  const submitting = loading1;

  return (
    <div className="grid w-full grid-cols-1 items-stretch gap-[24px] lg:grid-cols-[1.05fr_1fr] lg:gap-[40px]" data-testid="a-02-signup-page">
      <AuthPanel
        brand={t('brand.name')}
        homeHref="/"
        title={t('auth.panel.signupTitle', 'Start learning something new today.')}
        points={[
          t('auth.panel.point4', 'Seventeen expert-led courses, one account'),
          t('auth.panel.point5', 'Pay once, keep access for six months'),
          t('auth.panel.point6', 'Downloadable notes with every lesson'),
        ]}
      />
      <div className="flex items-center justify-center py-[8px] lg:py-[24px]">
      <div className="w-full max-w-[440px]" data-testid="a-02-signup-main">
        <Link
          to="/"
          data-testid="a-02-signup-home-link"
          className="mb-[16px] inline-flex min-h-[36px] items-center text-[14px] font-medium text-[var(--c-body)] hover:text-[var(--c-primary)]"
        >
          {t('auth.signup.backToHome', { defaultValue: 'Back to home' })}
        </Link>

        {/* Signing up creates a STUDENT. The teaching branch that lived here asked
            the API to make the visitor an instructor, and the API obliged — it read
            the role straight off the request body. Instructors are appointed in the
            admin console; a public form does not choose roles. */}
        <div data-testid="a-02-signup-ac-2">
          <form
            data-testid="a-02-signup-ac-1"
            onSubmit={(e) => {
              e.preventDefault();
              createRegister1();
            }}
            className="space-y-[16px] rounded-[var(--radius-lg)] border border-[var(--c-hairline)] bg-[var(--c-surface)] p-[24px] shadow-[0_1px_3px_rgb(29_32_38_/_0.08)]"
          >
            <h1
              data-testid="a-02-signup-heading"
              className="text-[24px] font-semibold leading-[1.25] tracking-[-0.2px] text-[var(--c-ink)]"
            >
              {t('auth.signup.title', { defaultValue: 'Create your account' })}
            </h1>

            <label className="flex flex-col gap-[4px]">
              <span className="text-[14px] font-medium text-[var(--c-ink)]">
                {t('auth.signup.fullName', { defaultValue: 'Full name' })}
              </span>
              <input
                name="fullName"
                type="text"
                data-testid="a-02-signup-ac-1-title"
                placeholder={t('auth.signup.fullNamePlaceholder', { defaultValue: 'Your name' })}
                {...fieldProps('fullName', errors)}
                className="min-h-[44px] w-full rounded-[var(--radius-md)] border border-[var(--c-hairline-strong)] bg-[var(--c-canvas)] px-[14px] py-[10px] transition-[border-color,box-shadow] duration-150 focus:border-[var(--c-primary)] focus:shadow-[0_0_0_3px_color-mix(in_srgb,var(--c-primary)_18%,transparent)] text-[15px] text-[var(--c-ink)] placeholder:text-[var(--c-muted)] focus:border-[var(--c-primary)] focus:outline-none"
              />
              <FieldError id="fullName-error" message={errors.fullName} />
            </label>

            <label className="flex flex-col gap-[4px]">
              <span className="text-[14px] font-medium text-[var(--c-ink)]">
                {t('auth.signup.email', { defaultValue: 'Email' })}
              </span>
              <input
                name="email"
                type="email"
                data-testid="a-02-signup-ac-1-content"
                placeholder={t('auth.signup.emailPlaceholder', { defaultValue: 'you@example.com' })}
                {...fieldProps('email', errors)}
                className="min-h-[44px] w-full rounded-[var(--radius-md)] border border-[var(--c-hairline-strong)] bg-[var(--c-canvas)] px-[14px] py-[10px] transition-[border-color,box-shadow] duration-150 focus:border-[var(--c-primary)] focus:shadow-[0_0_0_3px_color-mix(in_srgb,var(--c-primary)_18%,transparent)] text-[15px] text-[var(--c-ink)] placeholder:text-[var(--c-muted)] focus:border-[var(--c-primary)] focus:outline-none"
              />
              <FieldError id="email-error" message={errors.email} />
            </label>

            <label className="flex flex-col gap-[4px]">
              <span className="text-[14px] font-medium text-[var(--c-ink)]">
                {t('auth.signup.password', { defaultValue: 'Password' })}
              </span>
              <input
                name="password"
                type="password"
                data-testid="a-02-signup-ac-2-title"
                placeholder={t('auth.signup.passwordPlaceholder', { defaultValue: 'At least 8 characters' })}
                {...fieldProps('password', errors)}
                className="min-h-[44px] w-full rounded-[var(--radius-md)] border border-[var(--c-hairline-strong)] bg-[var(--c-canvas)] px-[14px] py-[10px] transition-[border-color,box-shadow] duration-150 focus:border-[var(--c-primary)] focus:shadow-[0_0_0_3px_color-mix(in_srgb,var(--c-primary)_18%,transparent)] text-[15px] text-[var(--c-ink)] placeholder:text-[var(--c-muted)] focus:border-[var(--c-primary)] focus:outline-none"
              />
              <FieldError id="password-error" message={errors.password} />
            </label>

            {error && (
              <p role="alert" data-testid="a-02-signup-error" className="text-[14px] text-[var(--c-error)]">
                {error}
              </p>
            )}

            <button
              type="submit"
              disabled={submitting}
              data-testid="a-02-signup-ac-1-action"
              className="inline-flex min-h-[48px] items-center justify-center gap-[8px] rounded-[var(--radius-md)] border border-transparent bg-[var(--c-primary)] px-[32px] py-[16px] text-[18px] font-semibold leading-none text-[var(--c-on-primary)] transition-colors hover:bg-[var(--c-primary-active)] disabled:pointer-events-none disabled:opacity-50"
            >
              <span data-testid="a-02-signup-ac-2-action">
                {submitting
                  ? t('auth.signup.submitting', { defaultValue: 'Creating account…' })
                  : t('auth.signup.submit', { defaultValue: 'Create account' })}
              </span>
            </button>

            <p className="text-[14px] leading-[1.5] text-[var(--c-body)]">
              {t('auth.signup.haveAccount', { defaultValue: 'Already registered?' })}{' '}
              <Link
                to="/signin"
                data-testid="a-02-signup-ac-3"
                className="font-medium text-[var(--c-primary-text)] hover:underline"
              >
                {t('auth.signup.signIn', { defaultValue: 'Sign in' })}
              </Link>
            </p>
          </form>
        </div>
      </div>
      </div>
    </div>
  );
}
