// Generated by scaffold-page-from-story from user_stories/S-01-home.yaml
// Story: US-S-01-HOME
// Role:  all
// Feature: Catalogue landing page
// Goal: As a visitor on the home page I can see the live catalogue — categories, best selling courses, recently added courses and top instructors — so that I can pick something to learn without signing in fir
//
// PRIMARY deterministic page (v128): generated BEFORE convert-pages. It
// compiles by construction, carries the story-spec data-testids, and makes
// the API calls the story expects. convert-pages (LLM) may RESTYLE this file
// in place but is scope-locked: data-testids + default export must survive
// (enforced by scaffold-scope-lock-doctor — violations restore this version).
//
// Restyled by convert-pages to mirror design/html/student/S-01-home.html.
// The shared chrome (topbar + footer) is owned by StudentLayout; this page
// renders only the design's `data-shell="content"` region.

import { useEffect, useState } from 'react';
import { Link } from 'react-router';
import { useTranslation } from 'react-i18next';
import { useAppDispatch } from '~/hooks/useAppDispatch';
import { useAppSelector } from '~/hooks/useAppSelector';
import { listCourses, listCategories, listInstructors } from '~/services/httpServices/catalogueService';
import type { CourseRow, CategoryCard, InstructorRow } from '~/types/view-models';
import { CourseCard } from '~/components/shared/CourseCard';
import { Reveal } from '~/components/shared/Reveal';

/** Type-safe extraction of a list from an unknown API payload (bare array, {items}, or {data}). */
function toArray<T>(value: unknown): T[] {
  if (Array.isArray(value)) return value as T[];
  if (value && typeof value === 'object') {
    const bag = value as { items?: unknown; data?: unknown };
    if (Array.isArray(bag.items)) return bag.items as T[];
    if (Array.isArray(bag.data)) return bag.data as T[];
  }
  return [];
}

/** Aspect-locked image slot with a token-driven fallback (mirrors the design's `.media`). */
function Media({ src, alt, className }: { src?: string; alt: string; className?: string }) {
  if (src) {
    return <img src={src} alt={alt} loading="lazy" className={`h-full w-full object-cover ${className ?? ''}`} />;
  }
  return <div aria-hidden="true" className={`h-full w-full bg-gradient-to-br from-[var(--c-surface-soft)] to-[var(--c-primary-soft)] ${className ?? ''}`} />;
}

export default function HomePage() {
  const { t } = useTranslation('common');
  const dispatch = useAppDispatch();
  const user = useAppSelector((s) => s.auth?.user);

  const [data1, setData1] = useState<unknown>(null);
  const [loading1, setLoading1] = useState<boolean>(true);
  const [error1, setError1] = useState<string | null>(null);
  const [data2, setData2] = useState<unknown>(null);
  const [loading2, setLoading2] = useState<boolean>(true);
  const [error2, setError2] = useState<string | null>(null);
  const [data3, setData3] = useState<unknown>(null);
  const [loading3, setLoading3] = useState<boolean>(true);
  const [error3, setError3] = useState<string | null>(null);
  const [data4, setData4] = useState<unknown>(null);
  const [loading4, setLoading4] = useState<boolean>(true);
  const [error4, setError4] = useState<string | null>(null);

  // Best-selling / recently-added courses — GET /api/courses via the catalogue
  // read thunk (httpService client, withCredentials + 401→refresh retry).
  useEffect(() => {
    let cancelled = false;
    setLoading1(true);
    setError1(null);
    dispatch(listCourses(undefined)).unwrap()
      .then((d) => { if (!cancelled) setData1(d); })
      .catch((e: unknown) => { if (!cancelled) setError1(e instanceof Error ? e.message : 'Failed to load'); })
      .finally(() => { if (!cancelled) setLoading1(false); });
    return () => { cancelled = true; };
  }, [dispatch]);
  // Top categories — GET /api/categories.
  useEffect(() => {
    let cancelled = false;
    setLoading2(true);
    setError2(null);
    dispatch(listCategories(undefined)).unwrap()
      .then((d) => { if (!cancelled) setData2(d); })
      .catch((e: unknown) => { if (!cancelled) setError2(e instanceof Error ? e.message : 'Failed to load'); })
      .finally(() => { if (!cancelled) setLoading2(false); });
    return () => { cancelled = true; };
  }, [dispatch]);
  // Recently added — GET /api/courses?sort=newest. This used to re-sort the
  // best-selling payload by `createdAt`, a field the catalogue projection does
  // not send: every comparison was `new Date(undefined)` vs `new Date(undefined)`,
  // so "Recently added" silently rendered the four most POPULAR courses. The
  // endpoint orders by publishedAt itself — ask it.
  useEffect(() => {
    let cancelled = false;
    setLoading4(true);
    setError4(null);
    dispatch(listCourses({ sort: 'newest' })).unwrap()
      .then((d) => { if (!cancelled) setData4(d); })
      .catch((e: unknown) => { if (!cancelled) setError4(e instanceof Error ? e.message : 'Failed to load'); })
      .finally(() => { if (!cancelled) setLoading4(false); });
    return () => { cancelled = true; };
  }, [dispatch]);
  // Top instructors — GET /api/instructors.
  useEffect(() => {
    let cancelled = false;
    setLoading3(true);
    setError3(null);
    dispatch(listInstructors(undefined)).unwrap()
      .then((d) => { if (!cancelled) setData3(d); })
      .catch((e: unknown) => { if (!cancelled) setError3(e instanceof Error ? e.message : 'Failed to load'); })
      .finally(() => { if (!cancelled) setLoading3(false); });
    return () => { cancelled = true; };
  }, [dispatch]);

  const courses = toArray<CourseRow>(data1);
  const categories = toArray<CategoryCard>(data2);
  const instructors = toArray<InstructorRow>(data3);

  // The list endpoint already sorts by studentCount DESC (sort=popular is its
  // default), so this is the server's ranking, trimmed to the row width.
  const bestSelling = courses.slice(0, 8);
  const recentlyAdded = toArray<CourseRow>(data4).slice(0, 4);

  const renderCourseCard = (course: CourseRow, testId: string) => (
    <CourseCard
      key={course.id}
      course={course}
      testId={testId}
      studentsLabel={t('home.students', 'students')}
    />
  );

  return (
    <div data-testid="s-01-home-page">
      <Link to="/" className="sr-only" data-testid="s-01-home-home-link">{t('nav.home')}</Link>

      <div data-testid="s-01-home-main">
        {/* Hero — carries AC-4 (Browse courses CTA) */}
        <section
          data-testid="s-01-home-ac-4"
          className="et-aurora rounded-[var(--radius-xl)] border border-[var(--c-hairline)] bg-[var(--c-canvas)]"
        >
          <div className="grid grid-cols-1 items-center gap-[32px] px-[20px] py-[48px] sm:px-[32px] lg:grid-cols-2 lg:py-[72px]">
            <div className="flex flex-col gap-[16px]">
              <h1 data-testid="s-01-home-heading" className="et-enter text-[34px] font-extrabold leading-[1.08] tracking-[-0.03em] text-[var(--c-ink)] sm:text-[44px] lg:text-[56px]">
                {t('app.tagline', 'Learn with experts, anytime, anywhere')}
              </h1>
              <p className="et-enter et-enter-1 max-w-[46ch] text-[16px] leading-[1.6] text-[var(--c-muted)] sm:text-[18px]">
                {t('home.heroSubtitle', 'Browse expert-led courses, enrol in one click and pick up exactly where you left off.')}
              </p>
              <div className="et-enter et-enter-2 flex flex-wrap items-center gap-[12px]">
                <Link
                  to="/signup"
                  data-testid="s-01-home-hero-signup"
                  className="et-press et-sheen inline-flex min-h-[52px] items-center justify-center rounded-[var(--radius-pill)] bg-[var(--c-primary)] px-[30px] text-[16px] font-semibold text-[var(--c-on-primary)] shadow-[var(--shadow-2)] transition-colors hover:bg-[var(--c-primary-active)] sm:text-[18px]"
                >
                  {t('auth.createAccount', 'Create account')}
                </Link>
                <Link
                  to="/courses"
                  data-testid="s-01-home-hero-browse"
                  className="et-press inline-flex min-h-[52px] items-center justify-center rounded-[var(--radius-pill)] border border-[var(--c-hairline-strong)] bg-[var(--c-surface)] px-[30px] text-[16px] font-semibold text-[var(--c-primary-text)] transition-colors hover:border-[var(--c-primary)] hover:bg-[var(--c-surface-soft)] sm:text-[18px]"
                >
                  {t('auth.browseCourses', 'Browse courses')}
                </Link>
              </div>
            </div>
            <div className="et-enter et-enter-3 aspect-[4/3] w-full overflow-hidden rounded-[var(--radius-xl)] bg-[var(--c-canvas)] shadow-[var(--shadow-3)] ring-1 ring-[var(--c-hairline)]">
              <Media src="/images/hero-learning.jpg" alt={t('app.tagline', 'Learn with experts, anytime, anywhere')} />
            </div>
          </div>
        </section>

        {/* Browse top categories — AC-2 (category strip) */}
        <section data-testid="s-01-home-ac-2" className="py-[32px]">
          <Reveal className="mb-[24px]">
            <h2 className="text-[24px] font-semibold leading-[1.25] tracking-[-0.2px] text-[var(--c-ink)]">
              {t('home.categoriesTitle', 'Browse top categories')}
            </h2>
            <p className="text-[14px] text-[var(--c-muted)]">{t('home.categoriesSubtitle', 'Pick a subject and start today')}</p>
            <div className="mt-[8px] h-[3px] w-[48px] rounded-full bg-[var(--c-primary)]" />
          </Reveal>

          {loading2 && (
            <div data-testid="s-01-home-ac-2-loading" className="grid grid-cols-1 gap-[16px] sm:grid-cols-2 lg:grid-cols-4">
              {Array.from({ length: 8 }).map((_, i) => (
                <div key={i} className="et-shimmer h-[88px] rounded-[var(--radius-lg)] border border-[var(--c-hairline)]" />
              ))}
            </div>
          )}
          {error2 && <p data-testid="s-01-home-ac-2-error" className="text-[14px] text-[var(--c-error)]">{t('home.loadError', 'We could not load categories right now.')}</p>}
          {!loading2 && !error2 && (
            categories.length === 0 ? (
              <p className="text-[14px] text-[var(--c-muted)]">{t('empty.title', 'Nothing here yet')}</p>
            ) : (
              <div data-testid="s-01-home-ac-2-kpis" className="grid grid-cols-1 gap-[16px] sm:grid-cols-2 lg:grid-cols-4">
                {categories.map((cat) => {
                  const count = cat.courseCount ?? 0;
                  return (
                    <Link
                      key={cat.id}
                      to={`/courses?category=${encodeURIComponent(cat.slug)}`}
                      data-testid={`s-01-home-ac-2-kpi-${cat.id}`}
                      className="et-lift flex items-center gap-[12px] rounded-[var(--radius-lg)] border border-[var(--c-hairline)] bg-[var(--c-surface)] p-[14px] shadow-[var(--shadow-0)]"
                    >
                      <span className="inline-flex h-[56px] w-[56px] flex-shrink-0 items-center justify-center overflow-hidden rounded-[6px] bg-[var(--c-primary-soft)]">
                        <Media src={cat.iconUrl} alt="" className="h-[32px] w-[32px] object-contain" />
                      </span>
                      <span className="flex flex-col">
                        <span className="text-[16px] font-semibold text-[var(--c-ink)]">{cat.name}</span>
                        <span className="text-[14px] text-[var(--c-muted)]">
                          {count} {count === 1 ? t('home.course', 'course') : t('home.courses', 'courses')}
                        </span>
                      </span>
                    </Link>
                  );
                })}
              </div>
            )
          )}
        </section>

        {/* Best selling courses — AC-1 (opens home, sees the live catalogue) */}
        <section data-testid="s-01-home-ac-1" className="py-[32px]">
          <Reveal className="mb-[24px]">
            <h2 className="text-[24px] font-semibold leading-[1.25] tracking-[-0.2px] text-[var(--c-ink)]">
              {t('home.bestSellingTitle', 'Best selling courses')}
            </h2>
            <p className="text-[14px] text-[var(--c-muted)]">{t('home.bestSellingSubtitle', 'What learners are buying this month')}</p>
            <div className="mt-[8px] h-[3px] w-[48px] rounded-full bg-[var(--c-primary)]" />
          </Reveal>

          {loading1 && (
            <div data-testid="s-01-home-ac-1-loading" className="grid grid-cols-1 gap-[16px] sm:grid-cols-2 lg:grid-cols-4">
              {Array.from({ length: 8 }).map((_, i) => (
                <div key={i} className="et-shimmer h-[300px] rounded-[var(--radius-lg)] border border-[var(--c-hairline)]" />
              ))}
            </div>
          )}
          {error1 && <p data-testid="s-01-home-ac-1-error" className="text-[14px] text-[var(--c-error)]">{t('home.loadError', 'We could not load courses right now.')}</p>}
          {!loading1 && !error1 && (
            bestSelling.length === 0 ? (
              <p className="text-[14px] text-[var(--c-muted)]">{t('empty.title', 'Nothing here yet')}</p>
            ) : (
              <div data-testid="s-01-home-ac-1-detail" className="grid grid-cols-1 gap-[16px] sm:grid-cols-2 lg:grid-cols-4">
                {bestSelling.map((course) => renderCourseCard(course, `s-01-home-course-${course.slug}`))}
              </div>
            )
          )}
        </section>

        {/* Recently added — AC-3 (click a course card → /courses/:slug) */}
        <section data-testid="s-01-home-ac-3" className="py-[32px]">
          <Reveal className="mb-[24px]">
            <h2 className="text-[24px] font-semibold leading-[1.25] tracking-[-0.2px] text-[var(--c-ink)]">
              {t('home.recentTitle', 'Recently added')}
            </h2>
            <p className="text-[14px] text-[var(--c-muted)]">{t('home.recentSubtitle', 'Fresh from our instructors')}</p>
            <div className="mt-[8px] h-[3px] w-[48px] rounded-full bg-[var(--c-primary)]" />
          </Reveal>

          {loading4 && (
            <div data-testid="s-01-home-ac-3-loading" className="grid grid-cols-1 gap-[16px] sm:grid-cols-2 lg:grid-cols-4">
              {Array.from({ length: 4 }).map((_, i) => (
                <div key={i} className="et-shimmer h-[300px] rounded-[var(--radius-lg)] border border-[var(--c-hairline)]" />
              ))}
            </div>
          )}
          {error4 && <p data-testid="s-01-home-ac-3-error" className="text-[14px] text-[var(--c-error)]">{t('home.loadError', 'We could not load courses right now.')}</p>}
          {!loading4 && !error4 && (
            recentlyAdded.length === 0 ? (
              <p className="text-[14px] text-[var(--c-muted)]">{t('empty.title', 'Nothing here yet')}</p>
            ) : (
              <div className="grid grid-cols-1 gap-[16px] sm:grid-cols-2 lg:grid-cols-4">
                {recentlyAdded.map((course) => renderCourseCard(course, `s-01-home-recent-${course.slug}`))}
              </div>
            )
          )}
        </section>

        {/* Learn on E-Tutor — the learner's path through this app, in the order
            the app actually offers it: catalogue → checkout → player → progress.
            It was a "Teach on E-Tutor" pitch with a "Become an instructor" button.
            Instructors are appointed by E-Tutor, so that button had nowhere to
            lead; the section is the same shape, addressed to the person the site
            is for. */}
        <section data-testid="s-01-home-learn" className="py-[32px]">
          <Reveal className="mb-[24px]">
            <h2 className="text-[24px] font-semibold leading-[1.25] tracking-[-0.2px] text-[var(--c-ink)]">
              {t('home.learnTitle', 'Learn on E-Tutor')}
            </h2>
            <p className="text-[14px] text-[var(--c-muted)]">
              {t('home.learnSubtitle', 'Four steps from browsing to your first finished lesson')}
            </p>
            <div className="mt-[8px] h-[3px] w-[48px] rounded-full bg-[var(--c-primary)]" />
          </Reveal>
          <div className="grid grid-cols-1 items-start gap-[24px] lg:grid-cols-[2fr_1fr]">
            <div className="flex flex-col gap-[16px] rounded-[8px] border border-[var(--c-hairline)] bg-[var(--c-surface)] p-[24px] shadow-[var(--shadow-1)]">
              {[
                t('home.learnStep1', 'Find a course in the catalogue'),
                t('home.learnStep2', 'Add it to your cart and check out'),
                t('home.learnStep3', 'Watch the lessons at your own pace'),
                t('home.learnStep4', 'Pick up where you left off, lesson by lesson'),
              ].map((label, i) => (
                <div key={i} className="flex items-center gap-[12px]">
                  <span className="inline-flex h-[32px] w-[32px] flex-shrink-0 items-center justify-center rounded-full bg-[var(--c-primary-soft)] text-[14px] font-bold text-[var(--c-primary-text)]">
                    {i + 1}
                  </span>
                  <span className="text-[15px] text-[var(--c-ink)]">{label}</span>
                </div>
              ))}
              {/* Where the button leads depends on whether there is anything to
                  come back to. Sending a signed-in learner to the catalogue they
                  have already bought from is the small wrongness this section had
                  before, in the other direction. */}
              <Link
                to={user ? '/my-learning' : '/courses'}
                data-testid="s-01-home-learn-cta"
                className="mt-[8px] inline-flex min-h-[44px] w-fit items-center justify-center et-press et-sheen rounded-[var(--radius-pill)] bg-[var(--c-primary)] px-[24px] text-[15px] font-semibold text-[var(--c-on-primary)] transition hover:bg-[var(--c-primary-active)]"
              >
                {user
                  ? t('home.learnCtaMember', 'Go to my learning')
                  : t('home.learnCtaGuest', 'Browse courses')}
              </Link>
            </div>
            <div className="aspect-[4/3] w-full overflow-hidden rounded-[8px] bg-[var(--c-canvas)]">
              <Media src="/images/learn-journey.jpg" alt={t('home.learnTitle', 'Learn on E-Tutor')} />
            </div>
          </div>
        </section>

        {/* Top instructors */}
        <section className="py-[32px]">
          <Reveal className="mb-[24px]">
            <h2 className="text-[24px] font-semibold leading-[1.25] tracking-[-0.2px] text-[var(--c-ink)]">
              {t('home.instructorsTitle', 'Top instructors')}
            </h2>
            <p className="text-[14px] text-[var(--c-muted)]">{t('home.instructorsSubtitle', 'Learn from people who do the work')}</p>
            <div className="mt-[8px] h-[3px] w-[48px] rounded-full bg-[var(--c-primary)]" />
          </Reveal>

          {loading3 && (
            <div data-testid="s-01-home-instructors-loading" className="grid grid-cols-1 gap-[16px] sm:grid-cols-2 lg:grid-cols-4">
              {Array.from({ length: 4 }).map((_, i) => (
                <div key={i} className="et-shimmer h-[180px] rounded-[var(--radius-lg)] border border-[var(--c-hairline)]" />
              ))}
            </div>
          )}
          {error3 && <p data-testid="s-01-home-instructors-error" className="text-[14px] text-[var(--c-error)]">{t('home.loadError', 'We could not load instructors right now.')}</p>}
          {!loading3 && !error3 && (
            instructors.length === 0 ? (
              <p data-testid="s-01-home-instructors-empty" className="text-[14px] text-[var(--c-muted)]">{t('empty.title', 'Nothing here yet')}</p>
            ) : (
              <div className="grid grid-cols-1 gap-[16px] sm:grid-cols-2 lg:grid-cols-4">
                {instructors.slice(0, 4).map((inst) => (
                  <Link
                    key={inst.id}
                    to={`/instructors/${inst.id}`}
                    data-testid={`s-01-home-instructor-${inst.id}`}
                    className="et-lift flex flex-col items-start gap-[8px] rounded-[var(--radius-lg)] border border-[var(--c-hairline)] bg-[var(--c-surface)] p-[24px] shadow-[var(--shadow-1)]"
                  >
                    <span className="inline-flex h-[64px] w-[64px] items-center justify-center overflow-hidden rounded-full bg-[var(--c-canvas)]">
                      <Media src={inst.avatarUrl} alt={inst.name ?? ''} />
                    </span>
                    <p className="text-[16px] font-semibold text-[var(--c-ink)]">{inst.name ?? ''}</p>
                    <p className="text-[14px] text-[var(--c-muted)]">{inst.headline ?? ''}</p>
                    {/* `country` is not part of this projection — it rendered nothing.
                        The two aggregates the endpoint DOES send are what a learner
                        picking an instructor actually wants to compare. */}
                    <p className="text-[12px] font-medium text-[var(--c-muted)]">
                      {inst.courseCount ?? 0} {(inst.courseCount ?? 0) === 1 ? t('home.course', 'course') : t('home.courses', 'courses')}
                      {' · '}
                      {(inst.studentCount ?? 0).toLocaleString()} {t('home.students', 'students')}
                    </p>
                  </Link>
                ))}
              </div>
            )
          )}
        </section>
      </div>
    </div>
  );
}
