// Generated by scaffold-page-from-story from user_stories/S-01-home.yaml
// Story: US-S-01-HOME
// Role:  all
// Feature: Catalogue landing page
// Goal: As a visitor on the home page I can see the live catalogue — categories, best selling courses, recently added courses and top instructors — so that I can pick something to learn without signing in fir
//
// PRIMARY deterministic page (v128): generated BEFORE convert-pages. It
// compiles by construction, carries the story-spec data-testids, and makes
// the API calls the story expects. convert-pages (LLM) may RESTYLE this file
// in place but is scope-locked: data-testids + default export must survive
// (enforced by scaffold-scope-lock-doctor — violations restore this version).
//
// Restyled by convert-pages to mirror design/html/student/S-01-home.html.
// The shared chrome (topbar + footer) is owned by StudentLayout; this page
// renders only the design's `data-shell="content"` region.

import { useEffect, useState } from 'react';
import { Link } from 'react-router';
import { useTranslation } from 'react-i18next';
import { useAppDispatch } from '~/hooks/useAppDispatch';
import { listCourses, listCategories, listInstructors } from '~/services/httpServices/catalogueService';
import type { Course } from '~/types/course';
import type { Category } from '~/types/category';
import type { User } from '~/types/user';
import { Star } from 'lucide-react';

/** Type-safe extraction of a list from an unknown API payload (bare array, {items}, or {data}). */
function toArray<T>(value: unknown): T[] {
  if (Array.isArray(value)) return value as T[];
  if (value && typeof value === 'object') {
    const bag = value as { items?: unknown; data?: unknown };
    if (Array.isArray(bag.items)) return bag.items as T[];
    if (Array.isArray(bag.data)) return bag.data as T[];
  }
  return [];
}

/** Aspect-locked image slot with a token-driven fallback (mirrors the design's `.media`). */
function Media({ src, alt, className }: { src?: string; alt: string; className?: string }) {
  if (src) {
    return <img src={src} alt={alt} loading="lazy" className={`h-full w-full object-cover ${className ?? ''}`} />;
  }
  return <div aria-hidden="true" className={`h-full w-full bg-gradient-to-br from-[var(--c-surface-soft)] to-[var(--c-primary-soft)] ${className ?? ''}`} />;
}

export default function HomePage() {
  const { t } = useTranslation('common');
  const dispatch = useAppDispatch();

  const [data1, setData1] = useState<unknown>(null);
  const [loading1, setLoading1] = useState<boolean>(true);
  const [error1, setError1] = useState<string | null>(null);
  const [data2, setData2] = useState<unknown>(null);
  const [loading2, setLoading2] = useState<boolean>(true);
  const [error2, setError2] = useState<string | null>(null);
  const [data3, setData3] = useState<unknown>(null);
  const [loading3, setLoading3] = useState<boolean>(true);
  const [error3, setError3] = useState<string | null>(null);

  // Best-selling / recently-added courses — GET /api/courses via the catalogue
  // read thunk (httpService client, withCredentials + 401→refresh retry).
  useEffect(() => {
    let cancelled = false;
    setLoading1(true);
    setError1(null);
    dispatch(listCourses(undefined)).unwrap()
      .then((d) => { if (!cancelled) setData1(d); })
      .catch((e: unknown) => { if (!cancelled) setError1(e instanceof Error ? e.message : 'Failed to load'); })
      .finally(() => { if (!cancelled) setLoading1(false); });
    return () => { cancelled = true; };
  }, [dispatch]);
  // Top categories — GET /api/categories.
  useEffect(() => {
    let cancelled = false;
    setLoading2(true);
    setError2(null);
    dispatch(listCategories(undefined)).unwrap()
      .then((d) => { if (!cancelled) setData2(d); })
      .catch((e: unknown) => { if (!cancelled) setError2(e instanceof Error ? e.message : 'Failed to load'); })
      .finally(() => { if (!cancelled) setLoading2(false); });
    return () => { cancelled = true; };
  }, [dispatch]);
  // Top instructors — GET /api/instructors.
  useEffect(() => {
    let cancelled = false;
    setLoading3(true);
    setError3(null);
    dispatch(listInstructors(undefined)).unwrap()
      .then((d) => { if (!cancelled) setData3(d); })
      .catch((e: unknown) => { if (!cancelled) setError3(e instanceof Error ? e.message : 'Failed to load'); })
      .finally(() => { if (!cancelled) setLoading3(false); });
    return () => { cancelled = true; };
  }, [dispatch]);

  const courses = toArray<Course>(data1);
  const categories = toArray<Category>(data2);
  const instructors = toArray<User>(data3);

  const categoryName = new Map(categories.map((c) => [c.id, c.name] as const));
  const courseCountFor = (categoryId: string) => courses.filter((c) => c.categoryId === categoryId).length;

  const bestSelling = [...courses]
    .sort((a, b) => (b.studentCount ?? 0) - (a.studentCount ?? 0))
    .slice(0, 8);
  const recentlyAdded = [...courses]
    .sort((a, b) => new Date(b.createdAt ?? 0).getTime() - new Date(a.createdAt ?? 0).getTime())
    .slice(0, 4);

  const renderCourseCard = (course: Course, testId: string) => (
    <Link
      key={course.id}
      to={`/courses/${course.slug}`}
      data-testid={testId}
      className="group flex flex-col overflow-hidden rounded-[8px] border border-[var(--c-hairline)] bg-[var(--c-surface)] shadow-[var(--shadow-1)] transition hover:-translate-y-[2px] hover:shadow-[var(--shadow-hover)]"
    >
      <div className="h-[180px] w-full overflow-hidden bg-[var(--c-canvas)]">
        <Media src={course.thumbnailUrl} alt={course.title} />
      </div>
      <div className="flex flex-col gap-[8px] p-[16px]">
        <div className="flex items-center justify-between gap-[8px]">
          <span className="inline-flex items-center rounded-full bg-[var(--c-primary-soft)] px-[8px] py-[2px] text-[12px] font-medium text-[var(--c-primary-text)]">
            {categoryName.get(course.categoryId) ?? ''}
          </span>
          <span className="text-[16px] font-bold text-[var(--c-primary-text)]">
            ${course.price ?? 0}
            {course.compareAtPrice != null && course.compareAtPrice > (course.price ?? 0) && (
              <span className="ml-[4px] text-[14px] font-normal text-[var(--c-muted)] line-through">${course.compareAtPrice}</span>
            )}
          </span>
        </div>
        <p className="text-[16px] font-semibold leading-[1.35] text-[var(--c-ink)]">{course.title}</p>
        <div className="mt-[12px] flex items-center justify-between border-t border-[var(--c-hairline)] pt-[12px]">
          <span className="inline-flex items-center gap-[4px] text-[14px] text-[var(--c-ink)]">
            <Star className="h-[14px] w-[14px] text-[var(--c-primary-text)]" aria-hidden="true" />
            {course.ratingAvg != null ? (course.ratingAvg ?? 0).toFixed(1) : '0.0'}
          </span>
          <span className="text-[14px] text-[var(--c-muted)]">
            {(course.studentCount ?? 0).toLocaleString()} {t('home.students', 'students')}
          </span>
        </div>
      </div>
    </Link>
  );

  return (
    <div data-testid="s-01-home-page">
      <Link to="/" className="sr-only" data-testid="s-01-home-home-link">{t('nav.home')}</Link>

      <div data-testid="s-01-home-main">
        {/* Hero — carries AC-4 (Browse courses CTA) */}
        <section
          data-testid="s-01-home-ac-4"
          className="border-b border-[var(--c-hairline)] bg-[var(--c-canvas)]"
        >
          <div className="grid grid-cols-1 items-center gap-[32px] px-[24px] py-[64px] lg:grid-cols-2">
            <div className="flex flex-col gap-[16px]">
              <h1 data-testid="s-01-home-heading" className="text-[48px] font-bold leading-[1.15] tracking-[-0.5px] text-[var(--c-ink)]">
                {t('app.tagline', 'Learn with experts, anytime, anywhere')}
              </h1>
              <p className="text-[18px] leading-[1.55] text-[var(--c-muted)]">
                {t('home.heroSubtitle', 'Browse expert-led courses, enrol in one click and pick up exactly where you left off.')}
              </p>
              <div className="flex flex-wrap items-center gap-[12px]">
                <Link
                  to="/signup"
                  data-testid="s-01-home-hero-signup"
                  className="inline-flex min-h-[48px] items-center justify-center rounded-[6px] bg-[var(--c-primary)] px-[32px] text-[18px] font-semibold text-[var(--c-on-primary)] transition hover:bg-[var(--c-primary-active)]"
                >
                  {t('auth.createAccount', 'Create account')}
                </Link>
                <Link
                  to="/courses"
                  data-testid="s-01-home-hero-browse"
                  className="inline-flex min-h-[48px] items-center justify-center rounded-[6px] border border-[var(--c-hairline-strong)] bg-[var(--c-surface)] px-[32px] text-[18px] font-semibold text-[var(--c-primary-text)] transition hover:bg-[var(--c-surface-soft)]"
                >
                  {t('auth.browseCourses', 'Browse courses')}
                </Link>
              </div>
            </div>
            <div className="aspect-[4/3] w-full overflow-hidden rounded-[12px] bg-[var(--c-canvas)]">
              <Media src={undefined} alt={t('app.tagline', 'Learn with experts, anytime, anywhere')} />
            </div>
          </div>
        </section>

        {/* Browse top categories — AC-2 (category strip) */}
        <section data-testid="s-01-home-ac-2" className="px-[24px] py-[32px]">
          <div className="mb-[24px]">
            <h2 className="text-[24px] font-semibold leading-[1.25] tracking-[-0.2px] text-[var(--c-ink)]">
              {t('home.categoriesTitle', 'Browse top categories')}
            </h2>
            <p className="text-[14px] text-[var(--c-muted)]">{t('home.categoriesSubtitle', 'Pick a subject and start today')}</p>
            <div className="mt-[8px] h-[3px] w-[48px] rounded-full bg-[var(--c-primary)]" />
          </div>

          {loading2 && (
            <div data-testid="s-01-home-ac-2-loading" className="grid grid-cols-1 gap-[16px] sm:grid-cols-2 lg:grid-cols-4">
              {Array.from({ length: 8 }).map((_, i) => (
                <div key={i} className="h-[80px] animate-pulse rounded-[8px] border border-[var(--c-hairline)] bg-[var(--c-canvas)]" />
              ))}
            </div>
          )}
          {error2 && <p data-testid="s-01-home-ac-2-error" className="text-[14px] text-[var(--c-error)]">{t('home.loadError', 'We could not load categories right now.')}</p>}
          {!loading2 && !error2 && (
            categories.length === 0 ? (
              <p className="text-[14px] text-[var(--c-muted)]">{t('empty.title', 'Nothing here yet')}</p>
            ) : (
              <div data-testid="s-01-home-ac-2-kpis" className="grid grid-cols-1 gap-[16px] sm:grid-cols-2 lg:grid-cols-4">
                {categories.map((cat) => {
                  const count = courseCountFor(cat.id);
                  return (
                    <Link
                      key={cat.id}
                      to="/courses"
                      data-testid={`s-01-home-ac-2-kpi-${cat.id}`}
                      className="flex items-center gap-[12px] rounded-[8px] border border-[var(--c-hairline)] bg-[var(--c-surface)] p-[12px] transition hover:border-[var(--c-primary)] hover:shadow-[var(--shadow-1)]"
                    >
                      <span className="inline-flex h-[56px] w-[56px] flex-shrink-0 items-center justify-center overflow-hidden rounded-[6px] bg-[var(--c-primary-soft)]">
                        <Media src={cat.iconUrl} alt="" className="h-[32px] w-[32px] object-contain" />
                      </span>
                      <span className="flex flex-col">
                        <span className="text-[16px] font-semibold text-[var(--c-ink)]">{cat.name}</span>
                        <span className="text-[14px] text-[var(--c-muted)]">
                          {count} {count === 1 ? t('home.course', 'course') : t('home.courses', 'courses')}
                        </span>
                      </span>
                    </Link>
                  );
                })}
              </div>
            )
          )}
        </section>

        {/* Best selling courses — AC-1 (opens home, sees the live catalogue) */}
        <section data-testid="s-01-home-ac-1" className="px-[24px] py-[32px]">
          <div className="mb-[24px]">
            <h2 className="text-[24px] font-semibold leading-[1.25] tracking-[-0.2px] text-[var(--c-ink)]">
              {t('home.bestSellingTitle', 'Best selling courses')}
            </h2>
            <p className="text-[14px] text-[var(--c-muted)]">{t('home.bestSellingSubtitle', 'What learners are buying this month')}</p>
            <div className="mt-[8px] h-[3px] w-[48px] rounded-full bg-[var(--c-primary)]" />
          </div>

          {loading1 && (
            <div data-testid="s-01-home-ac-1-loading" className="grid grid-cols-1 gap-[16px] sm:grid-cols-2 lg:grid-cols-4">
              {Array.from({ length: 8 }).map((_, i) => (
                <div key={i} className="h-[300px] animate-pulse rounded-[8px] border border-[var(--c-hairline)] bg-[var(--c-canvas)]" />
              ))}
            </div>
          )}
          {error1 && <p data-testid="s-01-home-ac-1-error" className="text-[14px] text-[var(--c-error)]">{t('home.loadError', 'We could not load courses right now.')}</p>}
          {!loading1 && !error1 && (
            bestSelling.length === 0 ? (
              <p className="text-[14px] text-[var(--c-muted)]">{t('empty.title', 'Nothing here yet')}</p>
            ) : (
              <div data-testid="s-01-home-ac-1-detail" className="grid grid-cols-1 gap-[16px] sm:grid-cols-2 lg:grid-cols-4">
                {bestSelling.map((course) => renderCourseCard(course, `s-01-home-course-${course.slug}`))}
              </div>
            )
          )}
        </section>

        {/* Recently added — AC-3 (click a course card → /courses/:slug) */}
        <section data-testid="s-01-home-ac-3" className="px-[24px] py-[32px]">
          <div className="mb-[24px]">
            <h2 className="text-[24px] font-semibold leading-[1.25] tracking-[-0.2px] text-[var(--c-ink)]">
              {t('home.recentTitle', 'Recently added')}
            </h2>
            <p className="text-[14px] text-[var(--c-muted)]">{t('home.recentSubtitle', 'Fresh from our instructors')}</p>
            <div className="mt-[8px] h-[3px] w-[48px] rounded-full bg-[var(--c-primary)]" />
          </div>

          {!loading1 && !error1 && (
            recentlyAdded.length === 0 ? (
              <p className="text-[14px] text-[var(--c-muted)]">{t('empty.title', 'Nothing here yet')}</p>
            ) : (
              <div className="grid grid-cols-1 gap-[16px] sm:grid-cols-2 lg:grid-cols-4">
                {recentlyAdded.map((course) => renderCourseCard(course, `s-01-home-recent-${course.slug}`))}
              </div>
            )
          )}
        </section>

        {/* Teach on E-Tutor — static instructor onboarding steps */}
        <section className="px-[24px] py-[32px]">
          <div className="mb-[24px]">
            <h2 className="text-[24px] font-semibold leading-[1.25] tracking-[-0.2px] text-[var(--c-ink)]">
              {t('home.teachTitle', 'Teach on E-Tutor')}
            </h2>
            <p className="text-[14px] text-[var(--c-muted)]">{t('home.teachSubtitle', 'Four steps from idea to first learner')}</p>
            <div className="mt-[8px] h-[3px] w-[48px] rounded-full bg-[var(--c-primary)]" />
          </div>
          <div className="grid grid-cols-1 items-start gap-[24px] lg:grid-cols-[2fr_1fr]">
            <div className="flex flex-col gap-[16px] rounded-[8px] border border-[var(--c-hairline)] bg-[var(--c-surface)] p-[24px] shadow-[var(--shadow-1)]">
              {[
                t('home.step1', 'Plan your curriculum'),
                t('home.step2', 'Record your lessons'),
                t('home.step3', 'Publish and set a price'),
                t('home.step4', 'Get paid every month'),
              ].map((label, i) => (
                <div key={i} className="flex items-center gap-[12px]">
                  <span className="inline-flex h-[32px] w-[32px] flex-shrink-0 items-center justify-center rounded-full bg-[var(--c-primary-soft)] text-[14px] font-bold text-[var(--c-primary-text)]">
                    {i + 1}
                  </span>
                  <span className="text-[15px] text-[var(--c-ink)]">{label}</span>
                </div>
              ))}
              <Link
                to="/signup"
                data-testid="s-01-home-become-instructor"
                className="mt-[8px] inline-flex min-h-[44px] w-fit items-center justify-center rounded-[6px] bg-[var(--c-primary)] px-[24px] text-[15px] font-semibold text-[var(--c-on-primary)] transition hover:bg-[var(--c-primary-active)]"
              >
                {t('home.becomeInstructor', 'Become an instructor')}
              </Link>
            </div>
            <div className="aspect-[4/3] w-full overflow-hidden rounded-[8px] bg-[var(--c-canvas)]">
              <Media src={undefined} alt={t('home.becomeInstructor', 'Become an instructor')} />
            </div>
          </div>
        </section>

        {/* Top instructors */}
        <section className="px-[24px] py-[32px]">
          <div className="mb-[24px]">
            <h2 className="text-[24px] font-semibold leading-[1.25] tracking-[-0.2px] text-[var(--c-ink)]">
              {t('home.instructorsTitle', 'Top instructors')}
            </h2>
            <p className="text-[14px] text-[var(--c-muted)]">{t('home.instructorsSubtitle', 'Learn from people who do the work')}</p>
            <div className="mt-[8px] h-[3px] w-[48px] rounded-full bg-[var(--c-primary)]" />
          </div>

          {loading3 && (
            <div data-testid="s-01-home-instructors-loading" className="grid grid-cols-1 gap-[16px] sm:grid-cols-2 lg:grid-cols-4">
              {Array.from({ length: 4 }).map((_, i) => (
                <div key={i} className="h-[180px] animate-pulse rounded-[8px] border border-[var(--c-hairline)] bg-[var(--c-canvas)]" />
              ))}
            </div>
          )}
          {error3 && <p data-testid="s-01-home-instructors-error" className="text-[14px] text-[var(--c-error)]">{t('home.loadError', 'We could not load instructors right now.')}</p>}
          {!loading3 && !error3 && (
            instructors.length === 0 ? (
              <p data-testid="s-01-home-instructors-empty" className="text-[14px] text-[var(--c-muted)]">{t('empty.title', 'Nothing here yet')}</p>
            ) : (
              <div className="grid grid-cols-1 gap-[16px] sm:grid-cols-2 lg:grid-cols-4">
                {instructors.slice(0, 4).map((inst) => (
                  <Link
                    key={inst.id}
                    to={`/instructors/${inst.id}`}
                    data-testid={`s-01-home-instructor-${inst.id}`}
                    className="flex flex-col items-start gap-[8px] rounded-[8px] border border-[var(--c-hairline)] bg-[var(--c-surface)] p-[24px] shadow-[var(--shadow-1)] transition hover:-translate-y-[2px] hover:shadow-[var(--shadow-hover)]"
                  >
                    <span className="inline-flex h-[64px] w-[64px] items-center justify-center overflow-hidden rounded-full bg-[var(--c-canvas)]">
                      <Media src={inst.avatarUrl} alt={inst.fullName} />
                    </span>
                    <p className="text-[16px] font-semibold text-[var(--c-ink)]">{inst.fullName}</p>
                    <p className="text-[14px] text-[var(--c-muted)]">{inst.headline ?? ''}</p>
                    {inst.country && <p className="text-[12px] font-medium text-[var(--c-muted)]">{inst.country}</p>}
                  </Link>
                ))}
              </div>
            )
          )}
        </section>
      </div>
    </div>
  );
}
