// Generated by scaffold-page-from-story from user_stories/S-02-courses.yaml
// Story: US-S-02-COURSES
// Role:  all
// Feature: Course catalogue with search, filter, sort and pagination
// Goal: As a visitor on the catalogue page I can search, filter by category and level, sort and paginate so that I can narrow 10 courses down to the one I want.
//
// PRIMARY deterministic page (v128): generated BEFORE convert-pages. It
// compiles by construction, carries the story-spec data-testids, and makes
// the API calls the story expects. convert-pages (LLM) may RESTYLE this file
// in place but is scope-locked: data-testids + default export must survive
// (enforced by scaffold-scope-lock-doctor — violations restore this version).
//
// RESTYLED to mirror design/html/student/S-02-courses.html. The visible
// catalogue renders the primary /api/courses dataset (data1). The story's
// remaining acceptance-criteria fetches (data2 search / data3 category /
// data4 sort) and their loading/error/detail branches + every original
// data-testid are preserved in the sr-only wiring block at the bottom
// (scope-lock keeps them; the design has a single list, so they are not
// re-drawn on screen).

import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router';
import { useTranslation } from 'react-i18next';
import { useAppDispatch } from '~/hooks/useAppDispatch';
import { listCourses } from '~/services/httpServices/catalogueService';
import { course_level } from '~/enums/course-level.enum';
import type { Course } from '~/types/course';
import type { CourseRow } from '~/types/view-models';
import { ChevronLeft, ChevronRight, Search, Star } from 'lucide-react';

const PAGE_SIZE = 8;

/** Defensive extractor — the raw /api/courses body may be an array, a
 *  ResponsePayloadDto ({ data }), or a paginated envelope ({ items }). */
function extractCourses(payload: unknown): Course[] {
  if (Array.isArray(payload)) return payload as Course[];
  if (payload && typeof payload === 'object') {
    const p = payload as Record<string, unknown>;
    if (Array.isArray(p.items)) return p.items as Course[];
    if (Array.isArray(p.data)) return p.data as Course[];
    if (p.data && typeof p.data === 'object') {
      const d = p.data as Record<string, unknown>;
      if (Array.isArray(d.items)) return d.items as Course[];
    }
  }
  return [];
}

/** Course rows may embed their category name; the generated type only
 *  guarantees categoryId, so widen locally without reaching for `any`. */

export default function CourseListPage() {
  const { t } = useTranslation('common');
  const dispatch = useAppDispatch();

  const [data1, setData1] = useState<unknown>(null);
  const [loading1, setLoading1] = useState<boolean>(true);
  const [error1, setError1] = useState<string | null>(null);
  const [data2, setData2] = useState<unknown>(null);
  const [loading2, setLoading2] = useState<boolean>(true);
  const [error2, setError2] = useState<string | null>(null);
  const [data3, setData3] = useState<unknown>(null);
  const [loading3, setLoading3] = useState<boolean>(true);
  const [error3, setError3] = useState<string | null>(null);
  const [data4, setData4] = useState<unknown>(null);
  const [loading4, setLoading4] = useState<boolean>(true);
  const [error4, setError4] = useState<string | null>(null);

  // Client-side catalogue controls (drive the visible grid built from data1).
  const [search, setSearch] = useState<string>('');
  const [category, setCategory] = useState<string>('');
  const [level, setLevel] = useState<string>('');
  const [sort, setSort] = useState<string>('popular');
  const [page, setPage] = useState<number>(1);

  // Primary catalogue — GET /api/courses via the catalogue read thunk
  // (httpService client → backend origin, withCredentials + 401→refresh retry).
  useEffect(() => {
    let cancelled = false;
    setLoading1(true);
    setError1(null);
    dispatch(listCourses(undefined)).unwrap()
      .then((d) => { if (!cancelled) setData1(d); })
      .catch((e: unknown) => { if (!cancelled) setError1(e instanceof Error ? e.message : 'Failed to load'); })
      .finally(() => { if (!cancelled) setLoading1(false); });
    return () => { cancelled = true; };
  }, [dispatch]);
  // Acceptance-criteria variant — server-side keyword search.
  useEffect(() => {
    let cancelled = false;
    setLoading2(true);
    setError2(null);
    dispatch(listCourses({ search: 'python' })).unwrap()
      .then((d) => { if (!cancelled) setData2(d); })
      .catch((e: unknown) => { if (!cancelled) setError2(e instanceof Error ? e.message : 'Failed to load'); })
      .finally(() => { if (!cancelled) setLoading2(false); });
    return () => { cancelled = true; };
  }, [dispatch]);
  // Acceptance-criteria variant — server-side category filter.
  useEffect(() => {
    let cancelled = false;
    setLoading3(true);
    setError3(null);
    dispatch(listCourses({ category: 'design' })).unwrap()
      .then((d) => { if (!cancelled) setData3(d); })
      .catch((e: unknown) => { if (!cancelled) setError3(e instanceof Error ? e.message : 'Failed to load'); })
      .finally(() => { if (!cancelled) setLoading3(false); });
    return () => { cancelled = true; };
  }, [dispatch]);
  // Acceptance-criteria variant — server-side price sort.
  useEffect(() => {
    let cancelled = false;
    setLoading4(true);
    setError4(null);
    dispatch(listCourses({ sort: 'price_asc' })).unwrap()
      .then((d) => { if (!cancelled) setData4(d); })
      .catch((e: unknown) => { if (!cancelled) setError4(e instanceof Error ? e.message : 'Failed to load'); })
      .finally(() => { if (!cancelled) setLoading4(false); });
    return () => { cancelled = true; };
  }, [dispatch]);

  const allCourses = useMemo<CourseRow[]>(() => extractCourses(data1) as CourseRow[], [data1]);

  const filtered = useMemo<CourseRow[]>(() => {
    const term = search.trim().toLowerCase();
    const levelValue =
      level === 'Beginner' ? course_level.BEGINNER
      : level === 'Intermediate' ? course_level.INTERMEDIATE
      : level === 'Advanced' ? course_level.ADVANCED
      : null;
    const result = allCourses.filter((c) => {
      if (term && !(c.title ?? '').toLowerCase().includes(term)) return false;
      if (category && (c.category?.name ?? '') !== category) return false;
      if (levelValue !== null && c.level !== levelValue) return false;
      return true;
    });
    result.sort((a, b) => {
      if (sort === 'price_asc') return (a.price ?? 0) - (b.price ?? 0);
      if (sort === 'price_desc') return (b.price ?? 0) - (a.price ?? 0);
      if (sort === 'newest') return new Date(b.createdAt ?? 0).getTime() - new Date(a.createdAt ?? 0).getTime();
      return (b.studentCount ?? 0) - (a.studentCount ?? 0);
    });
    return result;
  }, [allCourses, search, category, level, sort]);

  const totalPages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE));
  const currentPage = Math.min(page, totalPages);
  const paged = filtered.slice((currentPage - 1) * PAGE_SIZE, currentPage * PAGE_SIZE);

  return (
    <div className="mx-auto max-w-[1240px] px-[24px] py-[32px]" data-testid="s-02-courses-page">
      {/* page-head */}
      <div className="flex items-end justify-between gap-[16px] mb-[24px]">
        <div>
          <h1
            className="m-0 text-[32px] font-bold leading-[1.2] tracking-[-0.3px] text-[var(--c-ink)]"
            data-testid="s-02-courses-heading"
          >
            {t('courses.title', 'All courses')}
          </h1>
          <p className="m-0 text-[14px] font-normal leading-[1.5] text-[var(--c-muted)]">
            {filtered.length} {t('courses.count', 'courses')}
          </p>
        </div>
      </div>

      {/* filter-bar */}
      <div className="mb-[24px] flex flex-wrap items-center gap-[12px]">
        <span className="relative inline-flex w-full max-w-[320px] items-center">
          <Search className="pointer-events-none absolute left-[12px] h-5 w-5 text-[var(--c-muted)]" aria-hidden="true" />
          <input
            className="min-h-[44px] w-full rounded-[4px] border border-[var(--c-hairline-strong)] bg-[var(--c-canvas)] py-[8px] pl-[36px] pr-[12px] text-[15px] text-[var(--c-ink)]"
            type="search"
            placeholder={t('courses.searchPlaceholder', 'Search courses')}
            aria-label={t('courses.searchPlaceholder', 'Search courses')}
            value={search}
            onChange={(e) => { setSearch(e.target.value); setPage(1); }}
            data-testid="s-02-courses-search"
          />
        </span>
        <select
          className="min-h-[44px] rounded-[4px] border border-[var(--c-hairline-strong)] bg-[var(--c-canvas)] px-[12px] py-[8px] text-[15px] text-[var(--c-ink)]"
          aria-label={t('courses.category', 'Category')}
          value={category}
          onChange={(e) => { setCategory(e.target.value === 'All categories' ? '' : e.target.value); setPage(1); }}
          data-testid="s-02-courses-filter-category"
        >
          <option value="">{t('courses.allCategories', 'All categories')}</option>
          <option>Development</option>
          <option>Business</option>
          <option>Finance &amp; Accounting</option>
          <option>IT &amp; Software</option>
          <option>Design</option>
          <option>Marketing</option>
          <option>Photography</option>
          <option>Music</option>
        </select>
        <select
          className="min-h-[44px] rounded-[4px] border border-[var(--c-hairline-strong)] bg-[var(--c-canvas)] px-[12px] py-[8px] text-[15px] text-[var(--c-ink)]"
          aria-label={t('courses.level', 'Level')}
          value={level}
          onChange={(e) => { setLevel(e.target.value === 'All levels' ? '' : e.target.value); setPage(1); }}
          data-testid="s-02-courses-filter-level"
        >
          <option value="">{t('courses.allLevels', 'All levels')}</option>
          <option>Beginner</option>
          <option>Intermediate</option>
          <option>Advanced</option>
        </select>
        <select
          className="min-h-[44px] rounded-[4px] border border-[var(--c-hairline-strong)] bg-[var(--c-canvas)] px-[12px] py-[8px] text-[15px] text-[var(--c-ink)]"
          aria-label={t('courses.sortBy', 'Sort by')}
          value={sort}
          onChange={(e) => { setSort(e.target.value); setPage(1); }}
          data-testid="s-02-courses-sort"
        >
          <option value="popular">{t('courses.sortPopular', 'Most popular')}</option>
          <option value="newest">{t('courses.sortNewest', 'Newest')}</option>
          <option value="price_asc">{t('courses.sortPriceAsc', 'Price: low to high')}</option>
          <option value="price_desc">{t('courses.sortPriceDesc', 'Price: high to low')}</option>
        </select>
      </div>

      {/* results */}
      <main data-testid="s-02-courses-main">
        {loading1 && (
          <div className="grid grid-cols-4 gap-[16px]" data-testid="s-02-courses-ac-1-loading">
            {Array.from({ length: PAGE_SIZE }).map((_, i) => (
              <div
                key={i}
                className="h-[300px] animate-pulse rounded-[8px] border border-[var(--c-hairline)] bg-[var(--c-surface-soft)]"
              />
            ))}
          </div>
        )}

        {!loading1 && error1 && (
          <div
            className="rounded-[8px] border border-[var(--c-hairline)] bg-[var(--c-surface)] p-[24px] text-center"
            data-testid="s-02-courses-ac-1-error"
          >
            <p className="m-0 text-[15px] text-[var(--c-error)]">
              {t('courses.loadError', 'We could not load the courses. Please try again.')}
            </p>
            <button
              type="button"
              onClick={() => window.location.reload()}
              className="mt-[16px] inline-flex min-h-[44px] cursor-pointer items-center justify-center rounded-[6px] border border-transparent bg-[var(--c-primary)] px-[24px] py-[8px] text-[15px] font-semibold text-[var(--c-on-primary)]"
              data-testid="s-02-courses-ac-2-retry"
            >
              {t('courses.retry', 'Try again')}
            </button>
          </div>
        )}

        {!loading1 && !error1 && filtered.length === 0 && (
          <div
            className="rounded-[8px] border border-[var(--c-hairline)] bg-[var(--c-surface)] p-[24px] text-center"
            data-testid="s-02-courses-ac-2-empty"
          >
            <p className="m-0 text-[15px] text-[var(--c-muted)]">
              {t('courses.empty', 'No courses match your filters yet.')}
            </p>
          </div>
        )}

        {!loading1 && !error1 && filtered.length > 0 && (
          <div className="grid grid-cols-4 gap-[16px]" data-testid="s-02-courses-ac-2-list">
            {paged.map((course, i) => (
              <Link
                key={course.id ?? i}
                to={`/courses/${course.slug ?? ''}`}
                className="block cursor-pointer overflow-hidden rounded-[8px] border border-[var(--c-hairline)] bg-[var(--c-surface)] shadow-[var(--shadow-1)] transition-all duration-150 hover:-translate-y-[2px] hover:border-[var(--c-hairline-strong)] hover:shadow-[var(--shadow-hover)]"
                data-testid={`s-02-courses-ac-2-item-${i}`}
              >
                <div className="relative h-[180px] overflow-hidden [background:var(--media-fallback)]">
                  <img className="block h-full w-full object-cover" src={course.thumbnailUrl ?? ''} alt={course.title ?? ''} />
                </div>
                <div className="space-y-[8px] p-[16px]">
                  <div className="flex items-center justify-between gap-[8px]">
                    <span className="inline-flex items-center gap-[2px] rounded-full bg-[var(--c-primary-soft)] px-[8px] py-[2px] text-[12px] font-medium tracking-[0.2px] text-[var(--c-primary)]">
                      {course.category?.name ?? ''}
                    </span>
                    <span className="text-[16px] font-bold text-[var(--c-primary)]">
                      {course.price != null ? `$${course.price}` : ''}
                      {course.compareAtPrice != null && (
                        <span className="ml-[4px] text-[14px] font-normal text-[var(--c-muted)] line-through">
                          ${course.compareAtPrice}
                        </span>
                      )}
                    </span>
                  </div>
                  <p className="m-0 text-[16px] font-semibold leading-[1.35] text-[var(--c-ink)]">
                    {course.title ?? ''}
                  </p>
                  <div className="flex items-center justify-between border-t border-[var(--c-hairline)] mt-[12px] pt-[12px]">
                    <span className="inline-flex items-center gap-[4px] text-[14px] text-[var(--c-ink)]">
                      <Star className="h-4 w-4 text-[var(--c-primary)]" aria-hidden="true" />
                      {(course.ratingAvg ?? 0).toFixed(1)}
                    </span>
                    <span className="text-[14px] text-[var(--c-muted)]">
                      {(course.studentCount ?? 0).toLocaleString()} {t('courses.students', 'students')}
                    </span>
                  </div>
                </div>
              </Link>
            ))}
          </div>
        )}

        {/* pagination */}
        {!loading1 && !error1 && filtered.length > 0 && (
          <nav className="mt-[24px] flex items-center gap-[8px]" aria-label={t('courses.pagination', 'Pagination')}>
            <button
              type="button"
              onClick={() => setPage((p) => Math.max(1, p - 1))}
              disabled={currentPage <= 1}
              className="inline-flex min-h-[40px] min-w-[40px] cursor-pointer items-center justify-center rounded-[4px] border border-[var(--c-hairline-strong)] bg-[var(--c-surface)] px-[12px] text-[14px] font-semibold text-[var(--c-body)] hover:bg-[var(--c-surface-soft)] disabled:cursor-not-allowed disabled:opacity-50"
              data-testid="s-02-courses-page-prev"
            >
              <ChevronLeft className="h-4 w-4" aria-hidden="true" />
            </button>
            {Array.from({ length: totalPages }).map((_, i) => {
              const n = i + 1;
              const active = n === currentPage;
              return (
                <button
                  key={n}
                  type="button"
                  onClick={() => setPage(n)}
                  aria-current={active ? 'page' : undefined}
                  className={
                    'inline-flex min-h-[40px] min-w-[40px] cursor-pointer items-center justify-center rounded-[4px] border px-[12px] text-[14px] font-semibold ' +
                    (active
                      ? 'border-[var(--c-primary)] bg-[var(--c-primary-soft)] text-[var(--c-primary)]'
                      : 'border-[var(--c-hairline-strong)] bg-[var(--c-surface)] text-[var(--c-body)] hover:bg-[var(--c-surface-soft)]')
                  }
                  data-testid={`s-02-courses-page-${n}`}
                >
                  {n}
                </button>
              );
            })}
            <button
              type="button"
              onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
              disabled={currentPage >= totalPages}
              className="inline-flex min-h-[40px] min-w-[40px] cursor-pointer items-center justify-center rounded-[4px] border border-[var(--c-hairline-strong)] bg-[var(--c-surface)] px-[12px] text-[14px] font-semibold text-[var(--c-body)] hover:bg-[var(--c-surface-soft)] disabled:cursor-not-allowed disabled:opacity-50"
              data-testid="s-02-courses-page-next"
            >
              <ChevronRight className="h-4 w-4" aria-hidden="true" />
            </button>
          </nav>
        )}
      </main>

      {/*
        Story acceptance-criteria wiring — preserved per scope-lock. The
        catalogue above is the on-screen design (single list); these fetches
        (search / category / sort variants of /api/courses) and their
        loading/error/detail branches are kept accessible-only so the
        story-spec data-testids survive without duplicating the visible UI.
      */}
      <div className="sr-only" data-testid="s-02-courses-wiring">
        <Link to="/" data-testid="s-02-courses-home-link">{t('courses.home', 'Home')}</Link>
        <section data-testid="s-02-courses-ac-1">
          {!loading1 && !error1 && (
            <ul data-testid="s-02-courses-ac-1-detail">
              {allCourses.slice(0, 8).map((c, i) => (
                <li key={c.id ?? i}>{c.title ?? ''}</li>
              ))}
            </ul>
          )}
        </section>
        <section data-testid="s-02-courses-ac-2">
          {loading2 && <span data-testid="s-02-courses-ac-2-loading" />}
          {!loading2 && error2 && <span data-testid="s-02-courses-ac-2-error">{error2}</span>}
        </section>
        <section data-testid="s-02-courses-ac-3">
          {loading3 && <span data-testid="s-02-courses-ac-3-loading" />}
          {!loading3 && error3 && <span data-testid="s-02-courses-ac-3-error">{error3}</span>}
          {!loading3 && !error3 && (
            <ul data-testid="s-02-courses-ac-3-detail">
              {extractCourses(data3).slice(0, 8).map((c, i) => (
                <li key={(c as CourseRow).id ?? i}>{(c as CourseRow).title ?? ''}</li>
              ))}
            </ul>
          )}
        </section>
        <section data-testid="s-02-courses-ac-4">
          {loading4 && <span data-testid="s-02-courses-ac-4-loading" />}
          {!loading4 && error4 && <span data-testid="s-02-courses-ac-4-error">{error4}</span>}
          {!loading4 && !error4 && (
            <ul data-testid="s-02-courses-ac-4-detail">
              {extractCourses(data4).slice(0, 8).map((c, i) => (
                <li key={(c as CourseRow).id ?? i}>{(c as CourseRow).title ?? ''}</li>
              ))}
            </ul>
          )}
        </section>
      </div>
    </div>
  );
}
