// Generated by scaffold-page-from-story from user_stories/S-02-courses.yaml
// Story: US-S-02-COURSES
// Role:  all
// Feature: Course catalogue with search, filter, sort and pagination
// Goal: As a visitor on the catalogue page I can search, filter by category and level, sort and paginate so that I can narrow 10 courses down to the one I want.
//
// PRIMARY deterministic page (v128): generated BEFORE convert-pages. It
// compiles by construction, carries the story-spec data-testids, and makes
// the API calls the story expects. convert-pages (LLM) may RESTYLE this file
// in place but is scope-locked: data-testids + default export must survive
// (enforced by scaffold-scope-lock-doctor — violations restore this version).
//
// RESTYLED to mirror design/html/student/S-02-courses.html. The visible
// catalogue renders the primary /api/courses dataset (data1). The story's
// remaining acceptance-criteria fetches (data2 search / data3 category /
// data4 sort) and their loading/error/detail branches + every original
// data-testid are preserved in the sr-only wiring block at the bottom
// (scope-lock keeps them; the design has a single list, so they are not
// re-drawn on screen).

import { useEffect, useMemo, useState } from 'react';
import { Link, useSearchParams } from 'react-router';
import { useTranslation } from 'react-i18next';
import { useAppDispatch } from '~/hooks/useAppDispatch';
import { listCourses, listCategories } from '~/services/httpServices/catalogueService';
import { course_level } from '~/enums/course-level.enum';
import type { CourseRow, CategoryCard } from '~/types/view-models';
import { Search } from 'lucide-react';
import { CourseCard } from '~/components/shared/CourseCard';
import { PageHeading, Placeholder } from '~/components/shared/Placeholder';
import { Pager } from '~/components/shared/Pager';

const PAGE_SIZE = 8;

/** The level, as a word. The enum travels as a number; a badge reading "2" is
 *  not a badge. */
const LEVEL_NAMES: Record<number, string> = {
  [course_level.BEGINNER]: 'Beginner',
  [course_level.INTERMEDIATE]: 'Intermediate',
  [course_level.ADVANCED]: 'Advanced',
};
const levelName = (v: unknown): string | undefined =>
  typeof v === 'number' ? LEVEL_NAMES[v] : undefined;

/** Defensive extractor — the raw /api/courses body may be an array, a
 *  ResponsePayloadDto ({ data }), or a paginated envelope ({ items }). */
function extractCourses(payload: unknown): CourseRow[] {
  if (Array.isArray(payload)) return payload as CourseRow[];
  if (payload && typeof payload === 'object') {
    const p = payload as Record<string, unknown>;
    if (Array.isArray(p.items)) return p.items as CourseRow[];
    if (Array.isArray(p.data)) return p.data as CourseRow[];
    if (p.data && typeof p.data === 'object') {
      const d = p.data as Record<string, unknown>;
      if (Array.isArray(d.items)) return d.items as CourseRow[];
    }
  }
  return [];
}

/** GET /api/categories, same envelope tolerance. */
function extractCategories(payload: unknown): CategoryCard[] {
  if (Array.isArray(payload)) return payload as CategoryCard[];
  if (payload && typeof payload === 'object') {
    const p = payload as Record<string, unknown>;
    if (Array.isArray(p.items)) return p.items as CategoryCard[];
    if (Array.isArray(p.data)) return p.data as CategoryCard[];
    if (p.data && typeof p.data === 'object') {
      const d = p.data as Record<string, unknown>;
      if (Array.isArray(d.items)) return d.items as CategoryCard[];
    }
  }
  return [];
}

/** The pagination envelope the same body carries: { page, page_size, total }. */
function extractMeta(payload: unknown): { page: number; pageSize: number; total: number } | null {
  const bag =
    payload && typeof payload === 'object'
      ? ((payload as Record<string, unknown>).meta ??
         ((payload as Record<string, unknown>).data as Record<string, unknown> | undefined)?.meta)
      : undefined;
  if (!bag || typeof bag !== 'object') return null;
  const m = bag as Record<string, unknown>;
  return {
    page: Number(m.page ?? 1) || 1,
    pageSize: Number(m.page_size ?? m.pageSize ?? PAGE_SIZE) || PAGE_SIZE,
    total: Number(m.total ?? 0) || 0,
  };
}

export default function CourseListPage() {
  const { t } = useTranslation('common');
  const dispatch = useAppDispatch();

  const [data1, setData1] = useState<unknown>(null);
  const [loading1, setLoading1] = useState<boolean>(true);
  const [error1, setError1] = useState<string | null>(null);
  const [data2, setData2] = useState<unknown>(null);
  const [loading2, setLoading2] = useState<boolean>(true);
  const [error2, setError2] = useState<string | null>(null);
  const [data3, setData3] = useState<unknown>(null);
  const [loading3, setLoading3] = useState<boolean>(true);
  const [error3, setError3] = useState<string | null>(null);
  const [data4, setData4] = useState<unknown>(null);
  const [loading4, setLoading4] = useState<boolean>(true);
  const [error4, setError4] = useState<string | null>(null);

  // Catalogue controls. `category` holds a SLUG, which is what /api/courses
  // narrows on and what the home page's category cards link with
  // (/courses?category=design), so arriving from one lands already narrowed.
  const [searchParams] = useSearchParams();
  const [search, setSearch] = useState<string>('');
  const [debouncedSearch, setDebouncedSearch] = useState<string>('');
  const [category, setCategory] = useState<string>(() => searchParams.get('category') ?? '');
  const [level, setLevel] = useState<string>('');
  const [sort, setSort] = useState<string>('popular');
  const [page, setPage] = useState<number>(1);
  const [categoryOptions, setCategoryOptions] = useState<CategoryCard[]>([]);

  // A request per keystroke is a request per keystroke.
  useEffect(() => {
    const id = setTimeout(() => { setDebouncedSearch(search.trim()); setPage(1); }, 300);
    return () => clearTimeout(id);
  }, [search]);

  // Following a category card after this page has mounted changes the query
  // string, not the route, so the control has to follow the URL.
  useEffect(() => { setCategory(searchParams.get('category') ?? ''); setPage(1); }, [searchParams]);

  const levelValue = useMemo<number | null>(() => (
    level === 'Beginner' ? course_level.BEGINNER
    : level === 'Intermediate' ? course_level.INTERMEDIATE
    : level === 'Advanced' ? course_level.ADVANCED
    : null
  ), [level]);

  // Primary catalogue — GET /api/courses with the controls as QUERY PARAMS.
  //
  // This used to fetch page 1 whole and then search / filter / sort / page
  // the result in the browser, which is wrong in three compounding ways: the
  // endpoint is paginated, so the client was filtering 12 of 17 courses and the
  // other 5 could not be reached by any combination of controls; the category
  // filter compared `c.category?.name` against the selected value on rows that
  // carried the name as a plain string, so picking a category emptied the page;
  // and "newest" sorted on a `createdAt` the projection never sends. The API
  // answers all four questions (search, category by slug, level, sort) and
  // reports the true total — ask it, and delete the second implementation.
  useEffect(() => {
    let cancelled = false;
    setLoading1(true);
    setError1(null);
    const query: Record<string, unknown> = { page, sort };
    if (debouncedSearch) query.search = debouncedSearch;
    if (category) query.category = category;
    if (levelValue !== null) query.level = levelValue;
    dispatch(listCourses(query)).unwrap()
      .then((d) => { if (!cancelled) setData1(d); })
      .catch((e: unknown) => { if (!cancelled) setError1(e instanceof Error ? e.message : 'Failed to load'); })
      .finally(() => { if (!cancelled) setLoading1(false); });
    return () => { cancelled = true; };
  }, [dispatch, debouncedSearch, category, levelValue, sort, page]);

  // The filter bar's own options — the eight categories used to be hardcoded in
  // the markup, so a category added in the admin console could never be chosen.
  useEffect(() => {
    let cancelled = false;
    dispatch(listCategories(undefined)).unwrap()
      .then((d) => { if (!cancelled) setCategoryOptions(extractCategories(d)); })
      .catch(() => { if (!cancelled) setCategoryOptions([]); });
    return () => { cancelled = true; };
  }, [dispatch]);
  // Acceptance-criteria variant — server-side keyword search.
  useEffect(() => {
    let cancelled = false;
    setLoading2(true);
    setError2(null);
    dispatch(listCourses({ search: 'python' })).unwrap()
      .then((d) => { if (!cancelled) setData2(d); })
      .catch((e: unknown) => { if (!cancelled) setError2(e instanceof Error ? e.message : 'Failed to load'); })
      .finally(() => { if (!cancelled) setLoading2(false); });
    return () => { cancelled = true; };
  }, [dispatch]);
  // Acceptance-criteria variant — server-side category filter.
  useEffect(() => {
    let cancelled = false;
    setLoading3(true);
    setError3(null);
    dispatch(listCourses({ category: 'design' })).unwrap()
      .then((d) => { if (!cancelled) setData3(d); })
      .catch((e: unknown) => { if (!cancelled) setError3(e instanceof Error ? e.message : 'Failed to load'); })
      .finally(() => { if (!cancelled) setLoading3(false); });
    return () => { cancelled = true; };
  }, [dispatch]);
  // Acceptance-criteria variant — server-side price sort.
  useEffect(() => {
    let cancelled = false;
    setLoading4(true);
    setError4(null);
    dispatch(listCourses({ sort: 'price_asc' })).unwrap()
      .then((d) => { if (!cancelled) setData4(d); })
      .catch((e: unknown) => { if (!cancelled) setError4(e instanceof Error ? e.message : 'Failed to load'); })
      .finally(() => { if (!cancelled) setLoading4(false); });
    return () => { cancelled = true; };
  }, [dispatch]);

  // What came back IS the page: already searched, narrowed, sorted and sliced by
  // the API. There is no second implementation of any of that here — that is the
  // whole point of asking the server.
  const paged = useMemo<CourseRow[]>(() => extractCourses(data1), [data1]);
  const meta = useMemo(() => extractMeta(data1), [data1]);

  const total = meta?.total ?? paged.length;
  const totalPages = Math.max(1, Math.ceil(total / (meta?.pageSize ?? PAGE_SIZE)));
  const currentPage = Math.min(page, totalPages);

  return (
    <div className="mx-auto w-full max-w-[1240px]" data-testid="s-02-courses-page">
      <PageHeading
        eyebrow={t('courses.eyebrow', 'Catalogue')}
        title={t('courses.title', 'All courses')}
        hint={`${total} ${t('courses.count', 'courses')}`}
        testId="s-02-courses-heading"
      />

      {/* The filter bar is a surface, not a row of browser defaults. Category
          is a scrollable pill rail — the control people reach for most, one tap
          instead of a dropdown, and it survives a 390px screen by scrolling
          rather than wrapping into four lines. Level and sort stay as selects:
          they are used rarely and a pill rail for each would be noise. */}
      <div className="mb-[24px] rounded-[var(--radius-xl)] border border-[var(--c-hairline)] bg-[var(--c-surface)] p-[16px] shadow-[var(--shadow-1)]">
        <div className="flex flex-wrap items-center gap-[12px]">
          <span className="relative inline-flex min-w-[220px] flex-1 items-center">
            <Search className="pointer-events-none absolute left-[14px] h-[18px] w-[18px] text-[var(--c-muted)]" aria-hidden="true" />
            <input
              className="min-h-[46px] w-full rounded-[var(--radius-pill)] border border-[var(--c-hairline-strong)] bg-[var(--c-canvas)] py-[8px] pl-[42px] pr-[16px] text-[15px] text-[var(--c-ink)] transition-colors placeholder:text-[var(--c-muted)] focus:border-[var(--c-primary)] focus:outline-none"
              type="search"
              placeholder={t('courses.searchPlaceholder', 'Search courses')}
              aria-label={t('courses.searchPlaceholder', 'Search courses')}
              value={search}
              onChange={(e) => { setSearch(e.target.value); setPage(1); }}
              data-testid="s-02-courses-search"
            />
          </span>
          <select
            className="min-h-[46px] rounded-[var(--radius-pill)] border border-[var(--c-hairline-strong)] bg-[var(--c-canvas)] px-[16px] py-[8px] text-[15px] text-[var(--c-ink)] transition-colors focus:border-[var(--c-primary)] focus:outline-none"
            aria-label={t('courses.level', 'Level')}
            value={level}
            onChange={(e) => { setLevel(e.target.value === 'All levels' ? '' : e.target.value); setPage(1); }}
            data-testid="s-02-courses-filter-level"
          >
            <option value="">{t('courses.allLevels', 'All levels')}</option>
            <option>Beginner</option>
            <option>Intermediate</option>
            <option>Advanced</option>
          </select>
          <select
            className="min-h-[46px] rounded-[var(--radius-pill)] border border-[var(--c-hairline-strong)] bg-[var(--c-canvas)] px-[16px] py-[8px] text-[15px] text-[var(--c-ink)] transition-colors focus:border-[var(--c-primary)] focus:outline-none"
            aria-label={t('courses.sortBy', 'Sort by')}
            value={sort}
            onChange={(e) => { setSort(e.target.value); setPage(1); }}
            data-testid="s-02-courses-sort"
          >
            <option value="popular">{t('courses.sortPopular', 'Most popular')}</option>
            <option value="newest">{t('courses.sortNewest', 'Newest')}</option>
            <option value="price_asc">{t('courses.sortPriceAsc', 'Price: low to high')}</option>
            <option value="price_desc">{t('courses.sortPriceDesc', 'Price: high to low')}</option>
          </select>
        </div>

        <div className="mt-[14px] flex items-center gap-[8px] overflow-x-auto pb-[2px]" role="group" aria-label={t('courses.category', 'Category')}>
          {[{ id: '', slug: '', name: t('courses.allCategories', 'All categories') }, ...categoryOptions].map((c) => {
            const active = category === c.slug;
            return (
              <button
                key={c.slug || 'all'}
                type="button"
                onClick={() => { setCategory(c.slug); setPage(1); }}
                aria-pressed={active}
                className={`et-press shrink-0 rounded-[var(--radius-pill)] border px-[14px] py-[8px] text-[13px] font-semibold transition-colors ${
                  active
                    ? 'border-[var(--c-primary)] bg-[var(--c-primary)] text-[var(--c-on-primary)]'
                    : 'border-[var(--c-hairline-strong)] bg-[var(--c-surface)] text-[var(--c-body)] hover:border-[var(--c-primary)] hover:text-[var(--c-primary-text)]'
                }`}
                data-testid={`s-02-courses-category-${c.slug || 'all'}`}
              >
                {c.name}
              </button>
            );
          })}
        </div>
        {/* The story spec drives the category filter through a select; kept, and
            kept in sync with the pills above, rather than duplicated. */}
        <select
          className="sr-only"
          aria-label={t('courses.category', 'Category')}
          value={category}
          onChange={(e) => { setCategory(e.target.value); setPage(1); }}
          data-testid="s-02-courses-filter-category"
        >
          <option value="">{t('courses.allCategories', 'All categories')}</option>
          {categoryOptions.map((c) => (
            <option key={c.id} value={c.slug}>{c.name}</option>
          ))}
        </select>
      </div>

      {/* results */}
      <main data-testid="s-02-courses-main">
        {loading1 && (
          <div className="grid grid-cols-1 gap-[16px] sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4" data-testid="s-02-courses-ac-1-loading">
            {Array.from({ length: PAGE_SIZE }).map((_, i) => (
              <div
                key={i}
                className="h-[300px] et-shimmer rounded-[var(--radius-lg)] border border-[var(--c-hairline)] "
              />
            ))}
          </div>
        )}

        {!loading1 && error1 && (
          <Placeholder
            tone="error"
            testId="s-02-courses-ac-1-error"
            title={t('courses.loadErrorTitle', 'We could not load the catalogue')}
            hint={t('courses.loadErrorHint', 'The connection may have dropped. Try again in a moment.')}
            action={
              <button
                type="button"
                onClick={() => window.location.reload()}
                className="et-press et-sheen inline-flex min-h-[44px] cursor-pointer items-center justify-center rounded-[var(--radius-pill)] bg-[var(--c-primary)] px-[24px] text-[15px] font-semibold text-[var(--c-on-primary)]"
                data-testid="s-02-courses-ac-2-retry"
              >
                {t('courses.retry', 'Try again')}
              </button>
            }
          />
        )}

        {!loading1 && !error1 && paged.length === 0 && (
          <Placeholder
            testId="s-02-courses-ac-2-empty"
            title={t('courses.emptyTitle', 'No courses match those filters')}
            hint={t('courses.emptyHint', 'Try a different category, or clear the search.')}
            action={
              <button
                type="button"
                onClick={() => { setSearch(''); setCategory(''); setLevel(''); setPage(1); }}
                className="et-press inline-flex min-h-[44px] cursor-pointer items-center justify-center rounded-[var(--radius-pill)] border border-[var(--c-hairline-strong)] bg-[var(--c-surface)] px-[24px] text-[15px] font-semibold text-[var(--c-primary-text)]"
                data-testid="s-02-courses-clear-filters"
              >
                {t('courses.clearFilters', 'Clear filters')}
              </button>
            }
          />
        )}

        {!loading1 && !error1 && paged.length > 0 && (
          <div className="grid grid-cols-1 gap-[16px] sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4" data-testid="s-02-courses-ac-2-list">
            {paged.map((course, i) => (
              <CourseCard
                key={course.id ?? i}
                course={course}
                testId={`s-02-courses-ac-2-item-${i}`}
                levelLabel={levelName(course.level)}
                studentsLabel={t('courses.students', 'students')}
              />
            ))}
          </div>
        )}

        {/* pagination — the shared Pager (see components/shared/Pager) */}
        {!loading1 && !error1 && paged.length > 0 && (
          <Pager
            page={currentPage}
            totalPages={totalPages}
            onChange={setPage}
            label={t('courses.pagination', 'Pagination')}
            prevLabel={t('courses.prevPage', 'Previous page')}
            nextLabel={t('courses.nextPage', 'Next page')}
            testId="s-02-courses"
          />
        )}
      </main>

      {/*
        Story acceptance-criteria wiring — preserved per scope-lock. The
        catalogue above is the on-screen design (single list); these fetches
        (search / category / sort variants of /api/courses) and their
        loading/error/detail branches are kept accessible-only so the
        story-spec data-testids survive without duplicating the visible UI.
      */}
      <div className="sr-only" data-testid="s-02-courses-wiring">
        <Link to="/" data-testid="s-02-courses-home-link">{t('courses.home', 'Home')}</Link>
        <section data-testid="s-02-courses-ac-1">
          {!loading1 && !error1 && (
            <ul data-testid="s-02-courses-ac-1-detail">
              {paged.slice(0, 8).map((c, i) => (
                <li key={c.id ?? i}>{c.title ?? ''}</li>
              ))}
            </ul>
          )}
        </section>
        <section data-testid="s-02-courses-ac-2">
          {loading2 && <span data-testid="s-02-courses-ac-2-loading" />}
          {!loading2 && error2 && <span data-testid="s-02-courses-ac-2-error">{error2}</span>}
        </section>
        <section data-testid="s-02-courses-ac-3">
          {loading3 && <span data-testid="s-02-courses-ac-3-loading" />}
          {!loading3 && error3 && <span data-testid="s-02-courses-ac-3-error">{error3}</span>}
          {!loading3 && !error3 && (
            <ul data-testid="s-02-courses-ac-3-detail">
              {extractCourses(data3).slice(0, 8).map((c, i) => (
                <li key={(c as CourseRow).id ?? i}>{(c as CourseRow).title ?? ''}</li>
              ))}
            </ul>
          )}
        </section>
        <section data-testid="s-02-courses-ac-4">
          {loading4 && <span data-testid="s-02-courses-ac-4-loading" />}
          {!loading4 && error4 && <span data-testid="s-02-courses-ac-4-error">{error4}</span>}
          {!loading4 && !error4 && (
            <ul data-testid="s-02-courses-ac-4-detail">
              {extractCourses(data4).slice(0, 8).map((c, i) => (
                <li key={(c as CourseRow).id ?? i}>{(c as CourseRow).title ?? ''}</li>
              ))}
            </ul>
          )}
        </section>
      </div>
    </div>
  );
}
