// Generated by scaffold-page-from-story from user_stories/S-05-instructor-detail.yaml
// Story: US-S-05-INSTRUCTOR-DETAIL
// Role:  all
// Feature: Instructor profile and their courses
// Goal: As a visitor on an instructor profile I can read their background and see every course they publish so that I can judge whether to learn from them.
//
// PRIMARY deterministic page (v128): generated BEFORE convert-pages. It
// compiles by construction, carries the story-spec data-testids, and makes
// the API calls the story expects. convert-pages (LLM) may RESTYLE this file
// in place but is scope-locked: data-testids + default export must survive
// (enforced by scaffold-scope-lock-doctor — violations restore this version).
//
// RESTYLED to mirror design/html/student/S-05-instructor-detail.html. The two
// story fetches (data1 profile, data2 courses) both hit /api/instructors/:id;
// data1 drives the profile header + the sticky KPI card, data2 drives the
// "Courses by …" grid. Every original data-testid + the loading/error/empty
// branches are preserved; the design has no dedicated AC-3 block so its testid
// rides an sr-only marker.

import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router';
import { useTranslation } from 'react-i18next';
import { useAppDispatch } from '~/hooks/useAppDispatch';
import { getInstructor } from '~/services/httpServices/catalogueService';
import type { Course } from '~/types/course';
import type { User } from '~/types/user';
import type { CourseRow, InstructorDetail } from '~/types/view-models';
import { ArrowLeft, Star } from 'lucide-react';
import { CourseCard } from '~/components/shared/CourseCard';

/** Course rows may embed their category name; the generated type only
 *  guarantees categoryId, so widen locally without reaching for `any`. */

/** The /api/instructors/:id body may carry aggregate stats and an embedded
 *  course list alongside the instructor's User fields — widen defensively. */

function asRecord(value: unknown): Record<string, unknown> | null {
  return value && typeof value === 'object' ? (value as Record<string, unknown>) : null;
}

/** Unwrap { data } / { instructor } envelopes down to the instructor object. */
function extractInstructor(payload: unknown): InstructorDetail | null {
  const root = asRecord(payload);
  if (!root) return null;
  const inner = asRecord(root.data) ?? root;
  const inst = asRecord(inner.instructor) ?? inner;
  return inst as unknown as InstructorDetail;
}

/** Pull the instructor's course list out of whichever shape the API returns. */
function extractCourses(payload: unknown): CourseRow[] {
  const root = asRecord(payload);
  if (!root) return [];
  const inner = asRecord(root.data) ?? root;
  const inst = asRecord(inner.instructor) ?? inner;
  const candidates = [inner.courses, inst.courses, inner.items, root.items];
  for (const c of candidates) {
    if (Array.isArray(c)) return c as CourseRow[];
  }
  return [];
}

export default function InstructorDetailPage() {
  const { t } = useTranslation('common');
  const __routeParams = useParams() as Record<string, string | undefined>;
  const dispatch = useAppDispatch();

  const [data1, setData1] = useState<unknown>(null);
  const [loading1, setLoading1] = useState<boolean>(true);
  const [error1, setError1] = useState<string | null>(null);
  const [data2, setData2] = useState<unknown>(null);
  const [loading2, setLoading2] = useState<boolean>(true);
  const [error2, setError2] = useState<string | null>(null);

  // Instructor profile — GET /api/instructors/:id via the catalogue read thunk;
  // data1 drives the profile header + KPI card.
  useEffect(() => {
    const id = __routeParams.id;
    let cancelled = false;
    setLoading1(true);
    setError1(null);
    if (!id) { setLoading1(false); return () => { cancelled = true; }; }
    dispatch(getInstructor(id)).unwrap()
      .then((d) => { if (!cancelled) setData1(d); })
      .catch((e: unknown) => { if (!cancelled) setError1(e instanceof Error ? e.message : 'Failed to load'); })
      .finally(() => { if (!cancelled) setLoading1(false); });
    return () => { cancelled = true; };
  }, [dispatch, __routeParams.id]);
  // Same instructor — data2 drives the "Courses by …" grid.
  useEffect(() => {
    const id = __routeParams.id;
    let cancelled = false;
    setLoading2(true);
    setError2(null);
    if (!id) { setLoading2(false); return () => { cancelled = true; }; }
    dispatch(getInstructor(id)).unwrap()
      .then((d) => { if (!cancelled) setData2(d); })
      .catch((e: unknown) => { if (!cancelled) setError2(e instanceof Error ? e.message : 'Failed to load'); })
      .finally(() => { if (!cancelled) setLoading2(false); });
    return () => { cancelled = true; };
  }, [dispatch, __routeParams.id]);

  const instructor = useMemo<InstructorDetail | null>(() => extractInstructor(data1), [data1]);
  const courses = useMemo<CourseRow[]>(() => extractCourses(data2), [data2]);
  const instructorName = instructor?.name ?? '';

  const coursesCount = instructor?.courseCount ?? courses.length;
  const studentsCount =
    instructor?.studentCount ?? courses.reduce((sum, c) => sum + (c.studentCount ?? 0), 0);
  const avgRating =
    instructor?.ratingAvg ??
    (courses.length ? courses.reduce((sum, c) => sum + (c.ratingAvg ?? 0), 0) / courses.length : 0);

  const kpis = [
    { key: 'courses', label: t('instructorDetail.kpiCourses', 'Courses'), value: coursesCount.toLocaleString() },
    { key: 'students', label: t('instructorDetail.kpiStudents', 'Enrollments'), value: Number(studentsCount).toLocaleString() },
    { key: 'rating', label: t('instructorDetail.kpiRating', 'Average rating'), value: Number(avgRating).toFixed(1) },
  ];

  return (
    <section
      className="mx-auto max-w-[var(--container-max)] px-[var(--space-xl)] py-[var(--space-xxl)]"
      data-testid="s-05-instructor-detail-page"
    >
      <Link
        to="/instructors"
        className="mb-[var(--space-lg)] inline-flex items-center gap-[var(--space-xs)] text-[14px] font-semibold text-[var(--c-body)] hover:text-[var(--c-primary)]"
        data-testid="s-05-instructor-detail-home-link"
      >
        <ArrowLeft className="icon-sm" aria-hidden="true" />
        {t('instructorDetail.back', 'Instructors')}
      </Link>

      <div data-testid="s-05-instructor-detail-main">
        <div className="grid grid-cols-1 items-start lg:grid-cols-[2fr_1fr] gap-[var(--space-xl)] max-[900px]:grid-cols-1">
          {/* LEFT — profile header + course grid */}
          <div className="space-y-[var(--space-xl)]">
            {/* AC-1: visitor opens a profile */}
            <section data-testid="s-05-instructor-detail-ac-1">
              {loading1 && (
                <div
                  className="flex items-center gap-[var(--space-md)] rounded-[var(--radius-lg)] border border-[var(--c-hairline)] bg-[var(--c-surface)] p-[var(--space-xl)] shadow-[var(--shadow-1)]"
                  data-testid="s-05-instructor-detail-ac-1-loading"
                >
                  <span className="h-[64px] w-[64px] flex-shrink-0 et-shimmer rounded-full bg-[var(--c-surface-soft)]" />
                  <span className="flex flex-1 flex-col gap-[var(--space-sm)]">
                    <span className="h-[20px] w-[180px] et-shimmer rounded-[var(--radius-sm)] bg-[var(--c-surface-soft)]" />
                    <span className="h-[14px] w-[120px] et-shimmer rounded-[var(--radius-sm)] bg-[var(--c-surface-soft)]" />
                  </span>
                </div>
              )}

              {!loading1 && error1 && (
                <div
                  className="rounded-[var(--radius-lg)] border border-[var(--c-hairline)] bg-[var(--c-surface)] p-[var(--space-xl)] text-center shadow-[var(--shadow-1)]"
                  data-testid="s-05-instructor-detail-ac-1-error"
                >
                  <p className="text-[15px] text-[var(--c-error)]">
                    {t('instructorDetail.profileError', 'We could not load this instructor.')}
                  </p>
                </div>
              )}

              {!loading1 && !error1 && (
                <div className="flex items-center gap-[var(--space-md)] rounded-[var(--radius-lg)] border border-[var(--c-hairline)] bg-[var(--c-surface)] p-[var(--space-xl)] shadow-[var(--shadow-1)]">
                  <span className="inline-flex h-[64px] w-[64px] flex-shrink-0 items-center justify-center overflow-hidden rounded-full bg-[var(--c-surface-soft)]">
                    <img className="h-full w-full object-cover" src={instructor?.avatarUrl ?? ''} alt={instructorName} />
                  </span>
                  <span className="flex flex-col">
                    <span
                      className="text-[24px] font-semibold leading-[1.25] tracking-[-0.2px] text-[var(--c-ink)]"
                      data-testid="s-05-instructor-detail-heading"
                    >
                      {instructorName}
                    </span>
                    <span className="text-[14px] leading-[1.5] text-[var(--c-muted)]">
                      {instructor?.headline ?? ''}
                    </span>
                  </span>
                </div>
              )}
            </section>

            {/* AC-2: visitor reads the course list */}
            <section data-testid="s-05-instructor-detail-ac-2">
              <h2 className="mb-[var(--space-lg)] text-[20px] font-semibold leading-[1.3] text-[var(--c-ink)]">
                {t('instructorDetail.coursesBy', 'Courses by')} {instructorName}
              </h2>

              {loading2 && (
                <div
                  className="grid grid-cols-2 gap-[var(--space-lg)] max-[900px]:grid-cols-2 max-[600px]:grid-cols-1"
                  data-testid="s-05-instructor-detail-ac-2-loading"
                >
                  {Array.from({ length: 3 }).map((_, i) => (
                    <div
                      key={i}
                      className="h-[300px] et-shimmer rounded-[var(--radius-lg)] border border-[var(--c-hairline)] bg-[var(--c-surface-soft)]"
                    />
                  ))}
                </div>
              )}

              {!loading2 && error2 && (
                <div
                  className="rounded-[var(--radius-lg)] border border-[var(--c-hairline)] bg-[var(--c-surface)] p-[var(--space-xl)] text-center shadow-[var(--shadow-1)]"
                  data-testid="s-05-instructor-detail-ac-2-error"
                >
                  <p className="text-[15px] text-[var(--c-error)]">
                    {t('instructorDetail.coursesError', 'We could not load these courses. Please try again.')}
                  </p>
                  <button
                    type="button"
                    onClick={() => window.location.reload()}
                    className="mt-[var(--space-lg)] inline-flex min-h-[44px] cursor-pointer items-center justify-center rounded-[var(--radius-md)] border border-transparent bg-[var(--c-primary)] px-[var(--space-xl)] py-[var(--space-sm)] text-[15px] font-semibold text-[var(--c-on-primary)] hover:bg-[var(--c-primary-active)]"
                    data-testid="s-05-instructor-detail-ac-2-retry"
                  >
                    {t('instructorDetail.retry', 'Try again')}
                  </button>
                </div>
              )}

              {!loading2 && !error2 && courses.length === 0 && (
                <div
                  className="rounded-[var(--radius-lg)] border border-[var(--c-hairline)] bg-[var(--c-surface)] p-[var(--space-xl)] text-center shadow-[var(--shadow-1)]"
                  data-testid="s-05-instructor-detail-ac-2-empty"
                >
                  <p className="text-[15px] text-[var(--c-muted)]">
                    {t('instructorDetail.coursesEmpty', 'This instructor has not published any courses yet.')}
                  </p>
                </div>
              )}

              {!loading2 && !error2 && courses.length > 0 && (
                <div
                  className="grid grid-cols-2 gap-[var(--space-lg)] max-[900px]:grid-cols-2 max-[600px]:grid-cols-1"
                  data-testid="s-05-instructor-detail-ac-2-list"
                >
                  {courses.map((course, i) => (
                    <CourseCard
                      key={course.id ?? i}
                      course={course}
                      testId={`s-05-instructor-detail-ac-2-item-${i}`}
                      studentsLabel={t('instructorDetail.students', 'students')}
                    />
                  ))}
                </div>
              )}
            </section>
          </div>

          {/* RIGHT — sticky KPI card (the instructor's aggregate stats) */}
          <aside
            className="sticky top-[calc(var(--space-section)+var(--space-xl))] space-y-[var(--space-md)] rounded-[var(--radius-lg)] border border-[var(--c-hairline)] bg-[var(--c-surface)] p-[var(--space-xl)] shadow-[var(--shadow-1)]"
            data-testid="s-05-instructor-detail-ac-1-kpis"
          >
            {kpis.map((kpi) => (
              <div
                key={kpi.key}
                className="flex flex-col gap-[var(--space-xs)]"
                data-testid={`s-05-instructor-detail-ac-1-kpi-${kpi.key}`}
              >
                <span className="text-[24px] font-semibold text-[var(--c-ink)]">
                  {loading1 ? '—' : kpi.value}
                </span>
                <span className="text-[12px] tracking-[0.2px] text-[var(--c-muted)]">{kpi.label}</span>
              </div>
            ))}
          </aside>
        </div>

        {/* AC-3: visitor clicks a course → navigates to /courses/:slug (the card
            Links above carry that behaviour); marker keeps the story testid. */}
        <span className="sr-only" data-testid="s-05-instructor-detail-ac-3">
          {t('instructorDetail.navHint', 'Selecting a course opens its detail page.')}
        </span>
      </div>
    </section>
  );
}
