// Generated by scaffold-dto-from-entity — DO NOT EDIT BY HAND. Re-run if entity changes.
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export class CategoryResponseDto {
  @ApiProperty()
  id!: string;

  @ApiProperty()
  name!: string;

  @ApiProperty()
  slug!: string;

  @ApiPropertyOptional()
  iconUrl?: string;

  @ApiPropertyOptional()
  description?: string;

  @ApiPropertyOptional()
  displayOrder?: number;

  @ApiPropertyOptional()
  isActive?: boolean;

  @ApiProperty()
  createdAt!: Date;

  @ApiProperty()
  updatedAt!: Date;
}

export type CategoryResponse = CategoryResponseDto;
