/** Generated by scaffold-dashboard-pages. */
import { route, layout } from '@react-router/dev/routes';

export const adminOverviewRoutes = [
  layout("components/layouts/AdminLayout.tsx", { id: "adminoverview-admin-layout" }, [

  // [design-route-retarget] design/manifest.json declares "pages/admin/adm-01-dashboard.tsx" for "admin"; was pages/admin-overview/AdminOverviewPage.tsx
  route('admin', 'pages/admin/adm-01-dashboard.tsx'),
  ]),
];
