// Generated by scaffold-page-from-story — routes for stub pages emitted by scaffold-page-from-story.
//
// Each entry maps story.acceptance_criteria[0].ui_route → page path.
// scaffold-convert-wire-routes aggregates this into top-level routes.ts.
// SAFE TO DELETE: regenerated on next pipeline run if no stubs are emitted.

import { route } from '@react-router/dev/routes';

export const safetyNetRoutes = [
  route("admin/login", "pages/admin/adm-00-login.tsx", { id: "safety-net-us-adm-00-login" }),
  route("admin/courses", "pages/admin/adm-02-courses.tsx", { id: "safety-net-us-adm-02-courses" }),
  route("admin/courses/:id", "pages/admin/adm-03-course-detail.tsx", { id: "safety-net-us-adm-03-course-detail" }),
  route("admin/categories", "pages/admin/adm-04-categories.tsx", { id: "safety-net-us-adm-04-categories" }),
  route("admin/users", "pages/admin/adm-05-users.tsx", { id: "safety-net-us-adm-05-users" }),
  route("admin/orders", "pages/admin/adm-06-orders.tsx", { id: "safety-net-us-adm-06-orders" }),
  route("admin/orders/:id", "pages/admin/adm-07-order-detail.tsx", { id: "safety-net-us-adm-07-order-detail" }),
  route("admin/enrollments", "pages/admin/adm-08-enrollments.tsx", { id: "safety-net-us-adm-08-enrollments" }),
  route("admin/coupons", "pages/admin/adm-09-coupons.tsx", { id: "safety-net-us-adm-09-coupons" }),
];
