/**
 * Generated by scaffold-story-specs from user_stories/ADM-03-course-detail.yaml
 *
 * Story: US-ADM-03-COURSE-DETAIL
 * Role:  admin
 * Feature: Course editor with sections and lessons
 * Goal: As an operator I can edit one course and manage its lessons so that a published course can actually be filled with content. 
 */
import { test, expect } from '@playwright/test';

// Pre-authenticate as role=admin (storageState captures JWT cookies from global-setup)
test.use({ storageState: 'tests/storageState-99.json' });

// Resolve :param routes to a real resource id (v129: literal ':id' nav → bad UUID → empty page).
const __API_BASE = process.env.API_URL || 'http://localhost:3000/api';
const __RESOLVE_OVERRIDES = {};
async function resolveRoute(page, route) {
  if (!/\/:[A-Za-z_]/.test(route)) return route;
  const segs = route.split('/').filter(Boolean);
  const idIdx = segs.findIndex(function (s) { return s.charAt(0) === ':'; });
  let listSegs = segs.slice(0, idIdx);
  if (['admin', 'worker', 'company', 'staff', 'operator'].indexOf(listSegs[0]) >= 0) listSegs = listSegs.slice(1);
  const listPath = '/' + listSegs.join('/');
  // v148: the resource LIST endpoint isn't always /<resource>. It can be
  //   /<resource>/nearby (geo list, e.g. instructors), /my/<resource> (owned,
  //   e.g. bookings), or /<resource>/me. The old code only tried /<resource>;
  //   when that 404s it fell back to 'unknown' → /<resource>/unknown → detail
  //   404s → the page errors → FALSE failure even though the page is fine.
  //   Try several candidates and use the first that yields a real id.
  const __ovr = (__RESOLVE_OVERRIDES && __RESOLVE_OVERRIDES[listPath]) ? [].concat(__RESOLVE_OVERRIDES[listPath]) : [];
  const __cands = __ovr.concat([listPath, listPath + '/nearby?lat=37.5&lng=127&radiusKm=30', '/my' + listPath, listPath + '/me']);
  let id = '';
  for (const __lp of __cands) {
    try {
      const r = await page.request.get(__API_BASE + __lp);
      if (!r.ok()) continue;
      const j = await r.json().catch(function () { return null; });
      const items = (j && j.data && (j.data.items || j.data)) || (j && j.items) || [];
      if (Array.isArray(items) && items[0] && typeof items[0] === 'object') {
        // v147: list items don't always key the PK as `id` — chat rooms use
        // `roomId`, some use `<resource>Id`. Take `id`, else the first own
        // field whose name ends in `id`/`Id` (skipping foreign keys like
        // `bookingId` only if a primary `*roomId/*Id` named after the route
        // exists — but first own id-field is a safe, general default).
        const __row = items[0];
        let __id = __row.id;
        if (__id === undefined || __id === null) {
          const __idKey = Object.keys(__row).find(function (k) { return /(^|[a-z])id$/i.test(k) && (typeof __row[k] === 'string' || typeof __row[k] === 'number'); });
          if (__idKey) __id = __row[__idKey];
        }
        if (__id !== undefined && __id !== null) { id = String(__id); break; }
      }
    } catch (e) { /* try next candidate */ }
  }
  return route.replace(/:[A-Za-z_]+/g, id || 'unknown');
}

async function __vis(loc) { try { return await loc.isVisible(); } catch { return false; } }
async function __txt(loc) { try { return (await loc.textContent()) || ''; } catch { return ''; } }

async function gotoStory(page, route, primary) {
  const resp = await page.goto(route);
  const nf = await __vis(page.locator('[data-testid*="not-found" i], [data-testid*="notfound" i]').first());
  if (nf && primary && primary !== route) { return await page.goto(primary); }
  return resp;
}

test.describe('US-ADM-03-COURSE-DETAIL — Course editor with sections and lessons', () => {
  test.afterEach(async ({ page, context }, testInfo) => {
    if (testInfo.status !== testInfo.expectedStatus) { try { await page.screenshot({ path: testInfo.outputPath('failure.png') }); } catch { /* best-effort */ } }
    try { await context.clearPermissions(); } catch { /* best-effort */ }
  });

  test('AC-1 — Admin opens a course', async ({ page }) => {
    const __apiErrs = [];
    const __apiOk = [];
    page.on('response', (r) => { try { const u = new URL(r.url()); if (u.pathname.indexOf('/api') === 0) { const s = r.status(); const rec = r.request().method() + ' ' + u.pathname; if (s >= 500) __apiErrs.push(rec + ' \u2192 ' + s); else if (s >= 200 && s < 300) __apiOk.push(rec); } } catch (e) {} });
    const __route = await resolveRoute(page, '/admin/courses/:id');
    const __resp = await gotoStory(page, __route, '');
    await page.waitForLoadState('networkidle', { timeout: 5_000 }).catch(() => {});
    expect(__apiErrs, 'a server-side /api error fired during this story (5xx — root cause, not a UI mismatch): ' + JSON.stringify(__apiErrs)).toEqual([]);
    expect(__resp ? __resp.status() : 0).toBeLessThan(400);
    const __errVisible = async (sel) => { const l = page.locator(sel).first(); if (!(await __vis(l))) return false; const t = ((await __txt(l)) || '').trim(); return t.length > 0; };
    const __own = await __vis(page.locator('[data-testid^="adm-03-course-detail" i]').first());
    const __err = await __errVisible('[data-testid^="adm-03-course-detail" i][data-testid*="error" i]');
    let __pass = __own && !__err;
    if (!__pass) {
      const __mounted = await page.evaluate(() => {
        const els = Array.from(document.querySelectorAll('[data-testid]'));
        const c = {};
        for (const el of els) { const t = el.getAttribute('data-testid') || ''; const m = t.match(/^(.+?)-(page|main|root|screen|view|container|wrapper)$/); if (m) c[m[1]] = (c[m[1]] || 0) + 1; }
        const k = Object.keys(c); return k.length ? k.sort((a, b) => c[b] - c[a])[0] : null;
      });
      const __authExpected = true;
      const __authBounce = __authExpected && /^\/(login|sign-?in|signup|sign-?up|register|forgot|reset)(\/|$)/i.test(new URL(page.url()).pathname);
      const __isNotFound = !__mounted || /not-?found|^404/i.test(__mounted);
      if (!__isNotFound && !__authBounce) {
        const __altErr = await __errVisible('[data-testid^="' + __mounted + '" i][data-testid*="error" i]');
        __pass = !__altErr;
      }
    }
    expect(__pass, 'expected the "adm-03-course-detail" page (or the page its route mounts) to render its own content without an error state (got 404 / auth-bounce / blank / error)').toBe(true);
    // P1-5: the story declares `GET /api/admin/courses/:id` — the page must have actually fetched it (2xx).
    // Resource-stem match (prefix/param/plural tolerant); a mounted page that never calls the backend fails here.
    const __epRe = /\/cours[a-z]*(?:[\/?]|$)/i;
    const __fired = __apiOk.some((x) => x.indexOf('GET ') === 0 && __epRe.test(x.slice(4)));
    expect(__fired, 'declared read endpoint never fired with 2xx (hollow page? wrong API path?) — 2xx GETs seen: ' + JSON.stringify(__apiOk.filter(x => x.indexOf("GET ") === 0))).toBe(true);
  });

  test('AC-2 — Admin edits the price and saves', async ({ page }) => {
    const __apiErrs = [];
    const __apiOk = [];
    page.on('response', (r) => { try { const u = new URL(r.url()); if (u.pathname.indexOf('/api') === 0) { const s = r.status(); const rec = r.request().method() + ' ' + u.pathname; if (s >= 500) __apiErrs.push(rec + ' \u2192 ' + s); else if (s >= 200 && s < 300) __apiOk.push(rec); } } catch (e) {} });
    const __route = await resolveRoute(page, '/admin/courses/:id');
    const __resp = await gotoStory(page, __route, '');
    await page.waitForLoadState('networkidle', { timeout: 5_000 }).catch(() => {});
    expect(__apiErrs, 'a server-side /api error fired during this story (5xx — root cause, not a UI mismatch): ' + JSON.stringify(__apiErrs)).toEqual([]);
    expect(__resp ? __resp.status() : 0).toBeLessThan(400);
    const __errVisible = async (sel) => { const l = page.locator(sel).first(); if (!(await __vis(l))) return false; const t = ((await __txt(l)) || '').trim(); return t.length > 0; };
    const __own = await __vis(page.locator('[data-testid^="adm-03-course-detail" i]').first());
    const __err = await __errVisible('[data-testid^="adm-03-course-detail" i][data-testid*="error" i]');
    let __pass = __own && !__err;
    if (!__pass) {
      const __mounted = await page.evaluate(() => {
        const els = Array.from(document.querySelectorAll('[data-testid]'));
        const c = {};
        for (const el of els) { const t = el.getAttribute('data-testid') || ''; const m = t.match(/^(.+?)-(page|main|root|screen|view|container|wrapper)$/); if (m) c[m[1]] = (c[m[1]] || 0) + 1; }
        const k = Object.keys(c); return k.length ? k.sort((a, b) => c[b] - c[a])[0] : null;
      });
      const __authExpected = true;
      const __authBounce = __authExpected && /^\/(login|sign-?in|signup|sign-?up|register|forgot|reset)(\/|$)/i.test(new URL(page.url()).pathname);
      const __isNotFound = !__mounted || /not-?found|^404/i.test(__mounted);
      if (!__isNotFound && !__authBounce) {
        const __altErr = await __errVisible('[data-testid^="' + __mounted + '" i][data-testid*="error" i]');
        __pass = !__altErr;
      }
    }
    expect(__pass, 'expected the "adm-03-course-detail" page (or the page its route mounts) to render its own content without an error state (got 404 / auth-bounce / blank / error)').toBe(true);
  });

  test('AC-3 — Admin adds a lesson', async ({ page }) => {
    const __apiErrs = [];
    const __apiOk = [];
    page.on('response', (r) => { try { const u = new URL(r.url()); if (u.pathname.indexOf('/api') === 0) { const s = r.status(); const rec = r.request().method() + ' ' + u.pathname; if (s >= 500) __apiErrs.push(rec + ' \u2192 ' + s); else if (s >= 200 && s < 300) __apiOk.push(rec); } } catch (e) {} });
    const __route = await resolveRoute(page, '/admin/courses/:id');
    const __resp = await gotoStory(page, __route, '');
    await page.waitForLoadState('networkidle', { timeout: 5_000 }).catch(() => {});
    expect(__apiErrs, 'a server-side /api error fired during this story (5xx — root cause, not a UI mismatch): ' + JSON.stringify(__apiErrs)).toEqual([]);
    expect(__resp ? __resp.status() : 0).toBeLessThan(400);
    const __errVisible = async (sel) => { const l = page.locator(sel).first(); if (!(await __vis(l))) return false; const t = ((await __txt(l)) || '').trim(); return t.length > 0; };
    const __own = await __vis(page.locator('[data-testid^="adm-03-course-detail" i]').first());
    const __err = await __errVisible('[data-testid^="adm-03-course-detail" i][data-testid*="error" i]');
    let __pass = __own && !__err;
    if (!__pass) {
      const __mounted = await page.evaluate(() => {
        const els = Array.from(document.querySelectorAll('[data-testid]'));
        const c = {};
        for (const el of els) { const t = el.getAttribute('data-testid') || ''; const m = t.match(/^(.+?)-(page|main|root|screen|view|container|wrapper)$/); if (m) c[m[1]] = (c[m[1]] || 0) + 1; }
        const k = Object.keys(c); return k.length ? k.sort((a, b) => c[b] - c[a])[0] : null;
      });
      const __authExpected = true;
      const __authBounce = __authExpected && /^\/(login|sign-?in|signup|sign-?up|register|forgot|reset)(\/|$)/i.test(new URL(page.url()).pathname);
      const __isNotFound = !__mounted || /not-?found|^404/i.test(__mounted);
      if (!__isNotFound && !__authBounce) {
        const __altErr = await __errVisible('[data-testid^="' + __mounted + '" i][data-testid*="error" i]');
        __pass = !__altErr;
      }
    }
    expect(__pass, 'expected the "adm-03-course-detail" page (or the page its route mounts) to render its own content without an error state (got 404 / auth-bounce / blank / error)').toBe(true);
  });

  test('AC-4 — Admin deletes a lesson', async ({ page }) => {
    const __apiErrs = [];
    const __apiOk = [];
    page.on('response', (r) => { try { const u = new URL(r.url()); if (u.pathname.indexOf('/api') === 0) { const s = r.status(); const rec = r.request().method() + ' ' + u.pathname; if (s >= 500) __apiErrs.push(rec + ' \u2192 ' + s); else if (s >= 200 && s < 300) __apiOk.push(rec); } } catch (e) {} });
    const __route = await resolveRoute(page, '/admin/courses/:id');
    const __resp = await gotoStory(page, __route, '');
    await page.waitForLoadState('networkidle', { timeout: 5_000 }).catch(() => {});
    expect(__apiErrs, 'a server-side /api error fired during this story (5xx — root cause, not a UI mismatch): ' + JSON.stringify(__apiErrs)).toEqual([]);
    expect(__resp ? __resp.status() : 0).toBeLessThan(400);
    const __errVisible = async (sel) => { const l = page.locator(sel).first(); if (!(await __vis(l))) return false; const t = ((await __txt(l)) || '').trim(); return t.length > 0; };
    const __own = await __vis(page.locator('[data-testid^="adm-03-course-detail" i]').first());
    const __err = await __errVisible('[data-testid^="adm-03-course-detail" i][data-testid*="error" i]');
    let __pass = __own && !__err;
    if (!__pass) {
      const __mounted = await page.evaluate(() => {
        const els = Array.from(document.querySelectorAll('[data-testid]'));
        const c = {};
        for (const el of els) { const t = el.getAttribute('data-testid') || ''; const m = t.match(/^(.+?)-(page|main|root|screen|view|container|wrapper)$/); if (m) c[m[1]] = (c[m[1]] || 0) + 1; }
        const k = Object.keys(c); return k.length ? k.sort((a, b) => c[b] - c[a])[0] : null;
      });
      const __authExpected = true;
      const __authBounce = __authExpected && /^\/(login|sign-?in|signup|sign-?up|register|forgot|reset)(\/|$)/i.test(new URL(page.url()).pathname);
      const __isNotFound = !__mounted || /not-?found|^404/i.test(__mounted);
      if (!__isNotFound && !__authBounce) {
        const __altErr = await __errVisible('[data-testid^="' + __mounted + '" i][data-testid*="error" i]');
        __pass = !__altErr;
      }
    }
    expect(__pass, 'expected the "adm-03-course-detail" page (or the page its route mounts) to render its own content without an error state (got 404 / auth-bounce / blank / error)').toBe(true);
    // Nav/mutation AC → the page must expose an interactive control to act through.
    //   We do NOT assert the destination link by href: RR7 navigates via
    //   onClick={navigate()} (no <a href>), so an href/dest-slug check false-fails
    //   working navigation. We also never match link COPY. Verifying the exact
    //   destination would require CLICKING a story-specific control (out of scope
    //   for generated specs); the render gate + a present control is the honest floor.
    const __ctrl = (await page.locator('button:visible, [role="button"]:visible, [type="submit"]:visible, a[href]:visible, input:visible, textarea:visible, select:visible').count().catch(() => 0)) > 0;
    expect(__ctrl, 'page exposes no interactive control to act through').toBe(true);
  });
});