// Generated by scaffold-zod-schema-from-dto — DO NOT EDIT BY HAND. Re-run when DTOs change.
import { z } from 'zod';
import { course_status } from '~/enums/course-status.enum';
import { order_status } from '~/enums/order-status.enum';
import { user_role } from '~/enums/user-role.enum';
import { user_status } from '~/enums/user-status.enum';

export const adminCategoryQuerySchema = z.object({
  search: z.string().max(100).optional(),
  sort: z.string().optional(),
  page: z.number().min(1).optional(),
});

export type AdminCategoryQueryInput = z.infer<typeof adminCategoryQuerySchema>;

export const adminCouponQuerySchema = z.object({
  search: z.string().max(32).optional(),
  sort: z.string().optional(),
  page: z.number().min(1).optional(),
});

export type AdminCouponQueryInput = z.infer<typeof adminCouponQuerySchema>;

export const adminCourseQuerySchema = z.object({
  search: z.string().max(100).optional(),
  category: z.string().optional(),
  status: z.nativeEnum(course_status).optional(),
  sort: z.string().optional(),
  page: z.number().min(1).optional(),
});

export type AdminCourseQueryInput = z.infer<typeof adminCourseQuerySchema>;

export const adminEnrollmentQuerySchema = z.object({
  search: z.string().max(100).optional(),
  sort: z.string().optional(),
  page: z.number().min(1).optional(),
});

export type AdminEnrollmentQueryInput = z.infer<typeof adminEnrollmentQuerySchema>;

export const adminOrderQuerySchema = z.object({
  search: z.string().max(100).optional(),
  status: z.nativeEnum(order_status).optional(),
  dateFrom: z.string().optional(),
  dateTo: z.string().optional(),
  sort: z.string().optional(),
  page: z.number().min(1).optional(),
});

export type AdminOrderQueryInput = z.infer<typeof adminOrderQuerySchema>;

export const adminUserQuerySchema = z.object({
  search: z.string().max(100).optional(),
  role: z.nativeEnum(user_role).optional(),
  status: z.nativeEnum(user_status).optional(),
  sort: z.string().optional(),
  page: z.number().min(1).optional(),
});

export type AdminUserQueryInput = z.infer<typeof adminUserQuerySchema>;
