// Generated by scaffold-zod-schema-from-dto — DO NOT EDIT BY HAND. Re-run when DTOs change.
import { z } from 'zod';

export const addCartItemSchema = z.object({
  courseId: z.string().uuid(),
});

export type AddCartItemInput = z.infer<typeof addCartItemSchema>;

export const applyCouponSchema = z.object({
  code: z.string(),
});

export type ApplyCouponInput = z.infer<typeof applyCouponSchema>;

export const cartResponseSchema = z.object({
  id: z.string(),
  userId: z.string(),
  couponId: z.string().optional(),
  subtotal: z.unknown().optional(),
  discountTotal: z.unknown().optional(),
  createdAt: z.unknown(),
  updatedAt: z.unknown(),
});

export type CartResponseInput = z.infer<typeof cartResponseSchema>;

export const createCartSchema = z.object({
  subtotal: z.number(),
  discountTotal: z.number(),
  couponId: z.string().uuid().optional(),
});

export type CreateCartInput = z.infer<typeof createCartSchema>;

export const updateCartItemQuantitySchema = z.object({
  quantity: z.number().min(1),
});

export type UpdateCartItemQuantityInput = z.infer<typeof updateCartItemQuantitySchema>;
