// Generated by scaffold-zod-schema-from-dto — DO NOT EDIT BY HAND. Re-run when DTOs change.
import { z } from 'zod';
import { lesson_type } from '~/enums/lesson-type.enum';

export const createLessonSchema = z.object({
  sectionId: z.string().uuid(),
  title: z.string(),
  contentType: z.nativeEnum(lesson_type).optional(),
  videoUrl: z.string().optional(),
  content: z.string().optional(),
  durationMinutes: z.number().optional(),
  displayOrder: z.number().optional(),
  isPreview: z.boolean().optional(),
  isPublished: z.boolean().optional(),
});

export type CreateLessonInput = z.infer<typeof createLessonSchema>;

export const lessonResponseSchema = z.object({
  id: z.string(),
  sectionId: z.string(),
  title: z.string(),
  contentType: z.unknown().optional(),
  videoUrl: z.string().optional(),
  content: z.string().optional(),
  durationMinutes: z.unknown().optional(),
  displayOrder: z.unknown().optional(),
  isPreview: z.unknown().optional(),
  isPublished: z.unknown().optional(),
  createdAt: z.unknown(),
  updatedAt: z.unknown(),
});

export type LessonResponseInput = z.infer<typeof lessonResponseSchema>;
