// Generated by scaffold-zod-schema-from-dto — DO NOT EDIT BY HAND. Re-run when DTOs change.
import { z } from 'zod';

export const createOrderItemSchema = z.object({
  orderId: z.string().uuid(),
  courseId: z.string().uuid(),
  titleSnapshot: z.string(),
  unitPrice: z.number(),
  quantity: z.number().optional(),
});

export type CreateOrderItemInput = z.infer<typeof createOrderItemSchema>;

export const orderItemResponseSchema = z.object({
  id: z.string(),
  orderId: z.string(),
  courseId: z.string(),
  titleSnapshot: z.string(),
  unitPrice: z.unknown(),
  quantity: z.unknown().optional(),
  createdAt: z.unknown(),
  updatedAt: z.unknown(),
});

export type OrderItemResponseInput = z.infer<typeof orderItemResponseSchema>;
