// Generated by scaffold-zod-schema-from-dto — DO NOT EDIT BY HAND. Re-run when DTOs change.
import { z } from 'zod';

export const createUserSchema = z.object({
  email: z.string().email(),
  passwordHash: z.string(),
  fullName: z.string(),
  role: z.unknown().optional(),
  status: z.unknown().optional(),
  headline: z.string().optional(),
  bio: z.string().optional(),
  avatarUrl: z.string().optional(),
  country: z.string().optional(),
  emailVerified: z.boolean().optional(),
});

export type CreateUserInput = z.infer<typeof createUserSchema>;

export const userResponseSchema = z.object({
  id: z.string(),
  email: z.string(),
  fullName: z.string(),
  role: z.unknown().optional(),
  status: z.unknown().optional(),
  headline: z.string().optional(),
  bio: z.string().optional(),
  avatarUrl: z.string().optional(),
  country: z.string().optional(),
  emailVerified: z.unknown().optional(),
  createdAt: z.unknown(),
  updatedAt: z.unknown(),
});

export type UserResponseInput = z.infer<typeof userResponseSchema>;
