// Generated by scaffold-table-columns-from-entity — DO NOT EDIT BY HAND. Re-run if entity changes.
import type { Column } from '~/types/table';
import type { CartResponse } from '~/types/cart';

export const cartColumns: Column<CartResponse>[] = [
  {
    key: 'userId',
    header: 'User Id',
  },
  {
    key: 'couponId',
    header: 'Coupon Id',
  },
  {
    key: 'subtotal',
    header: 'Subtotal',
  },
  {
    key: 'discountTotal',
    header: 'Discount Total',
  },
];
