// Generated by scaffold-table-columns-from-entity — DO NOT EDIT BY HAND. Re-run if entity changes.
import type { Column } from '~/types/table';
import type { LessonProgressResponse } from '~/types/lesson-progress';

export const lessonProgressColumns: Column<LessonProgressResponse>[] = [
  {
    key: 'enrollmentId',
    header: 'Enrollment Id',
  },
  {
    key: 'lessonId',
    header: 'Lesson Id',
  },
  {
    key: 'isCompleted',
    header: 'Is Completed',
    render: (row) => (row.isCompleted ? '✓' : '—'),
  },
  {
    key: 'watchedSeconds',
    header: 'Watched Seconds',
  },
  {
    key: 'completedAt',
    header: 'Completed At',
    render: (row) => row.completedAt ? new Date(row.completedAt as string).toLocaleDateString() : '',
  },
];
