// Generated by scaffold-table-columns-from-entity — DO NOT EDIT BY HAND. Re-run if entity changes.
import type { Column } from '~/types/table';
import type { OrderResponse } from '~/types/order';
import { formatDate } from '~/utils/date';

export const orderColumns: Column<OrderResponse>[] = [
  {
    key: 'orderNumber',
    header: 'Order Number',
  },
  {
    key: 'userId',
    header: 'User Id',
  },
  {
    key: 'couponId',
    header: 'Coupon Id',
  },
  {
    key: 'subtotal',
    header: 'Subtotal',
  },
  {
    key: 'discountTotal',
    header: 'Discount Total',
  },
  {
    key: 'total',
    header: 'Total',
  },
  {
    key: 'status',
    header: 'Status',
  },
  {
    key: 'paymentMethod',
    header: 'Payment Method',
  },
  {
    key: 'billingName',
    header: 'Billing Name',
  },
  {
    key: 'billingEmail',
    header: 'Billing Email',
  },
  {
    key: 'billingCountry',
    header: 'Billing Country',
  },
  {
    key: 'placedAt',
    header: 'Placed At',
    render: (row) => formatDate(row.placedAt),
  },
  {
    key: 'paidAt',
    header: 'Paid At',
    render: (row) => formatDate(row.paidAt),
  },
];
