/**
 * Generated by scaffold-listing-primitives. Selection state for a listing.
 *
 * RowSelect and BulkActions are two ends of one piece of state, so it lives here
 * instead of being re-derived per page. Keyed by row id (string), which is what
 * every bulk endpoint takes.
 *
 * Usage:
 *   const sel = useRowSelection(items.map((i) => i.id));
 *   <RowSelect checked={sel.allSelected} indeterminate={sel.someSelected} onChange={sel.toggleAll} testId="user-list-all" />
 *   <RowSelect checked={sel.isSelected(row.id)} onChange={() => sel.toggle(row.id)} testId={`user-list-${row.id}`} />
 *   <BulkActions count={sel.count} onClear={sel.clear} actions={[…]} testId="user-list" />
 */
import { useCallback, useMemo, useState } from 'react';

export interface RowSelection {
  selected: string[];
  count: number;
  allSelected: boolean;
  /** Some but not all — drives the header checkbox's indeterminate state. */
  someSelected: boolean;
  isSelected: (id: string) => boolean;
  toggle: (id: string) => void;
  toggleAll: () => void;
  clear: () => void;
}

export function useRowSelection(ids: string[]): RowSelection {
  const [selected, setSelected] = useState<string[]>([]);

  // Rows leave on page change / filter change; keeping ids that are no longer on
  // screen would make the count lie and submit records the user cannot see.
  const visible = useMemo(() => selected.filter((id) => ids.includes(id)), [selected, ids]);

  const isSelected = useCallback((id: string) => visible.includes(id), [visible]);

  const toggle = useCallback((id: string) => {
    setSelected((prev) => (prev.includes(id) ? prev.filter((x) => x !== id) : [...prev, id]));
  }, []);

  const toggleAll = useCallback(() => {
    setSelected((prev) => (ids.every((id) => prev.includes(id)) ? [] : [...ids]));
  }, [ids]);

  const clear = useCallback(() => setSelected([]), []);

  return {
    selected: visible,
    count: visible.length,
    allSelected: ids.length > 0 && ids.every((id) => visible.includes(id)),
    someSelected: visible.length > 0 && visible.length < ids.length,
    isSelected,
    toggle,
    toggleAll,
    clear,
  };
}
