/**
 * Generated by scaffold-entities from PROJECT_DATABASE.md table `carts`.
 * Edits to this file are preserved across re-runs ONLY when the table
 * definition is unchanged; otherwise re-run with --force to regenerate.
 */
import { Column, Entity, JoinColumn, ManyToOne } from 'typeorm';
import { BaseEntity } from '../../core/base/base.entity';
import { User } from '../user/user.entity';
import { Coupon } from '../coupon/coupon.entity';

@Entity('carts')
export class Cart extends BaseEntity {
  @Column({ name: 'user_id', type: 'uuid', unique: true })
  userId!: string;

  // `| null` is what the column IS (coupon_id uuid NULLABLE), and clearing a coupon means
  // writing NULL — `undefined` is ignored by TypeORM's update(). Typing it optional-only forced
  // a double cast at the one place that clears it.
  @Column({ name: 'coupon_id', type: 'uuid', nullable: true })
  couponId?: string | null;

  @Column({ type: 'decimal', precision: 10, scale: 2, transformer: { to: (v: number | null) => v, from: (v: string | null) => (v === null ? null : Number(v)) }, default: 0 })
  subtotal!: number;

  @Column({ name: 'discount_total', type: 'decimal', precision: 10, scale: 2, transformer: { to: (v: number | null) => v, from: (v: string | null) => (v === null ? null : Number(v)) }, default: 0 })
  discountTotal!: number;

  // ── Relations ──

  @ManyToOne(() => User, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'user_id' })
  user?: User;

  @ManyToOne(() => Coupon, { nullable: true, onDelete: 'SET NULL' })
  @JoinColumn({ name: 'coupon_id' })
  coupon?: Coupon;

}
