import { Body, Controller, Delete, Get, HttpCode, HttpStatus, Param, ParseUUIDPipe, Post, Query, UseGuards } from '@nestjs/common';
import { ApiTags, ApiOperation, ApiResponse } from '@nestjs/swagger';
import { BaseController } from '../../core/base/base.controller';
import { JwtAuthGuard } from '../../core/guards/jwt-auth.guard';
import { RolesGuard } from '../../core/guards/roles.guard';
import { Roles } from '../../core/decorators/roles.decorator';
import { user_role } from '../../common/enums/user-role.enum';
import { CurrentUser } from '../../core/decorators/current-user.decorator';
import { Cart } from './cart.entity';
import { CartService } from './cart.service';
import { CreateCartDto } from './dtos/create-cart.dto';
import { UpdateCartDto } from './dtos/update-cart.dto';

/**
 * Generic cart CRUD surface at /api/carts. Authenticated (JwtAuthGuard) — every
 * route re-checks the session. `create` binds the new cart to the session user
 * (a cart never carries a client-supplied owner); `findAll` returns the paginated
 * { items, meta } envelope; `remove` answers 204. findOne is inherited from
 * BaseController (200 / 404). The customer-facing cart operations live on the
 * /api/cart controller — see CartManagementController.
 */
@ApiTags('carts')
/**
 * ADMIN ONLY. This controller is BaseController's generated CRUD, and it carried
 * nothing but JwtAuthGuard — so any signed-in account could use it. Verified
 * against a running instance: a student could POST a 100%-off coupon, PATCH any
 * course's price, and read every cart, order line and lesson-progress row on the
 * platform.
 *
 * Nothing in either app calls these routes. The public catalogue is served by
 * CatalogueController (registered first, so it owns GET /api/courses and
 * GET /api/categories), the shopper's own cart by CartManagementController, and
 * the console by AdminConsoleController.
 */
@UseGuards(JwtAuthGuard, RolesGuard)
@Roles('admin', user_role.ADMIN)
@Controller('carts')
export class CartController extends BaseController<
  Cart,
  CreateCartDto,
  UpdateCartDto
> {
  constructor(protected readonly service: CartService) {
    super(service, CreateCartDto, UpdateCartDto);
  }

  // Generated by scaffold-owner-stamp-doctor — stamp owner FK(s) from the authenticated user
  @Post()
  async create(@Body() createDto: CreateCartDto, @CurrentUser('id') __ownerId?: string): Promise<Cart> {
    const __dto: any = createDto;
    __dto.userId = __dto.userId ?? __ownerId;
    return this.service.create(__dto);
  }



}
