// Generated by scaffold-charts-library — DO NOT EDIT BY HAND. Re-run to refresh.
import { CartesianGrid, Line, LineChart as ReLineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

export interface LineChartProps {
  data: Array<Record<string, number | string>>;
  xKey: string;
  yKey: string;
  height?: number;
  testId?: string;
}

export function LineChart({ data, xKey, yKey, height = 240, testId = 'line-chart' }: LineChartProps) {
  return (
    <div data-testid={testId} style={{ width: '100%', height }}>
      <ResponsiveContainer>
        <ReLineChart data={data}>
          <CartesianGrid strokeDasharray="3 3" />
          <XAxis dataKey={xKey} />
          <YAxis />
          <Tooltip />
          <Line type="monotone" dataKey={yKey} stroke="currentColor" className="text-primary" dot={false} />
        </ReLineChart>
      </ResponsiveContainer>
    </div>
  );
}
