// Generated by scaffold-charts-library — DO NOT EDIT BY HAND. Re-run to refresh.
import { Cell, Pie, PieChart as RePieChart, ResponsiveContainer, Tooltip } from 'recharts';

export interface PieDatum { name: string; value: number; fill?: string; }

export interface PieChartProps {
  data: PieDatum[];
  height?: number;
  testId?: string;
}

const PALETTE = ['#3b82f6', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6', '#06b6d4', '#84cc16', '#ec4899'];

export function PieChart({ data, height = 240, testId = 'pie-chart' }: PieChartProps) {
  return (
    <div data-testid={testId} style={{ width: '100%', height }}>
      <ResponsiveContainer>
        <RePieChart>
          <Pie data={data} dataKey="value" nameKey="name" innerRadius={40} outerRadius={80}>
            {data.map((d, i) => (
              <Cell key={d.name} fill={d.fill ?? PALETTE[i % PALETTE.length]} />
            ))}
          </Pie>
          <Tooltip />
        </RePieChart>
      </ResponsiveContainer>
    </div>
  );
}
