/**
 * Generated by scaffold-test-specs. Tests the canonical dashboard query
 * endpoint shipped by templates/modules/_dashboard/.
 *
 *   POST /api/dashboard/query — { entity, op, where?, group? }
 */
import supertest from 'supertest';
import {
  createTestApp,
  closeTestApp,
  type TestAppContext,
} from '../setup/test-app.factory';
import { cleanDatabase } from '../setup/test-database';
import { createTestUser } from '../fixtures/user.fixture';
import { loginAndGetCookie } from '../fixtures/auth.fixture';
import { RoleEnum } from '../../src/common/enums/role.enum';

describe('Dashboard Query E2E', () => {
  let ctx: TestAppContext;
  let cookie: string;

  beforeAll(async () => {
    ctx = await createTestApp();
  });

  beforeEach(async () => {
    await cleanDatabase(ctx.dataSource);
    // The signed-in user has to exist AFTER the truncate, not before it. This block used to
    // sit in beforeAll while cleanDatabase ran in beforeEach, so from the very first test the
    // cookie authenticated a user row that had just been deleted: every authenticated write
    // then failed the users FK and the exception filter mapped the constraint to 400. The
    // suites read as "the payload is wrong" — they were fine; the session's user was gone.
    const user = await createTestUser(ctx.dataSource, {
      email: 'dashboard-spec@test.com',
      role: RoleEnum.admin,
    });
    cookie = await loginAndGetCookie(ctx.app, user.email, user.password);
  });

  afterAll(async () => {
    await closeTestApp(ctx);
  });

  describe('POST /api/dashboard/query', () => {
    it('returns 401 without cookie', async () => {
      await supertest(ctx.app.getHttpServer())
        .post('/api/dashboard/query')
        .send({ entity: 'users', op: 'count' })
        .expect(401);
    });

    it('returns 400 for unknown entity', async () => {
      await supertest(ctx.app.getHttpServer())
        .post('/api/dashboard/query')
        .set('Cookie', cookie)
        .send({ entity: 'nonexistent_table_xyz', op: 'count' })
        .expect((res) => {
          if (![400, 422].includes(res.status)) {
            throw new Error(`Expected 400 for unknown entity, got ${res.status}`);
          }
        });
    });

    it('returns { value } for count op (no group)', async () => {
      await supertest(ctx.app.getHttpServer())
        .post('/api/dashboard/query')
        .set('Cookie', cookie)
        .send({ entity: 'categories', op: 'count' })
        .expect((res) => {
          if (res.status !== 200) {
            // Skip if entity wasn't actually scaffolded in this project; non-test failure.
            return;
          }
          // Every response passes through the app's envelope interceptor
          // ({ success, statusCode, message, data, … }), so the payload is under `data`.
          // Reading the root is why this assertion failed against a correct { value: 0 }.
          const payload = res.body?.data ?? res.body;
          if (typeof payload.value !== 'number' && !Array.isArray(payload.items)) {
            throw new Error(`Expected { value } or { items } shape, got ${JSON.stringify(res.body)}`);
          }
        });
    });

    it('rejects disallowed where op', async () => {
      await supertest(ctx.app.getHttpServer())
        .post('/api/dashboard/query')
        .set('Cookie', cookie)
        .send({
          entity: 'categories',
          op: 'count',
          where: [{ field: 'id', op: 'BADOPNOTALLOWED', value: 'x' }],
        })
        .expect((res) => {
          if (![400, 422].includes(res.status)) {
            throw new Error(`Expected 400 for disallowed op, got ${res.status}`);
          }
        });
    });
  });
});
