// Generated by scaffold-table-columns-from-entity — DO NOT EDIT BY HAND. Re-run if entity changes.
import type { Column } from '~/types/table';
import type { CourseResponse } from '~/types/course';

export const courseColumns: Column<CourseResponse>[] = [
  {
    key: 'title',
    header: 'Title',
  },
  {
    key: 'slug',
    header: 'Slug',
  },
  {
    key: 'summary',
    header: 'Summary',
  },
  {
    key: 'description',
    header: 'Description',
  },
  {
    key: 'thumbnailUrl',
    header: 'Thumbnail Url',
  },
  {
    key: 'price',
    header: 'Price',
  },
  {
    key: 'compareAtPrice',
    header: 'Compare At Price',
  },
  {
    key: 'level',
    header: 'Level',
  },
  {
    key: 'language',
    header: 'Language',
  },
  {
    key: 'durationMinutes',
    header: 'Duration Minutes',
  },
  {
    key: 'status',
    header: 'Status',
  },
  {
    key: 'categoryId',
    header: 'Category Id',
  },
  {
    key: 'instructorId',
    header: 'Instructor Id',
  },
  {
    key: 'ratingAvg',
    header: 'Rating Avg',
  },
  {
    key: 'ratingCount',
    header: 'Rating Count',
  },
  {
    key: 'studentCount',
    header: 'Student Count',
  },
  {
    key: 'publishedAt',
    header: 'Published At',
    render: (row) => row.publishedAt ? new Date(row.publishedAt as string).toLocaleDateString() : '',
  },
];
