// Generated by scaffold-table-columns-from-entity — DO NOT EDIT BY HAND. Re-run if entity changes.
import type { Column } from '~/types/table';
import type { CourseSectionResponse } from '~/types/course-section';

export const courseSectionColumns: Column<CourseSectionResponse>[] = [
  {
    key: 'courseId',
    header: 'Course Id',
  },
  {
    key: 'title',
    header: 'Title',
  },
  {
    key: 'summary',
    header: 'Summary',
  },
  {
    key: 'displayOrder',
    header: 'Display Order',
  },
];
