// Generated by scaffold-dto-from-entity — DO NOT EDIT BY HAND. Re-run if entity changes.
import {
  IsOptional, IsString, IsNumber, IsBoolean, IsEnum, IsEmail, IsDateString, IsArray, IsObject, IsUUID
} from 'class-validator';
import { Type } from 'class-transformer';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { course_level } from '../../../common/enums/course-level.enum';
import { course_status } from '../../../common/enums/course-status.enum';

export class CreateCourseDto {
  @ApiProperty()
  @IsString()
  title!: string;

  @ApiProperty()
  @IsString()
  slug!: string;

  @ApiPropertyOptional()
  @IsOptional() @IsString()
  summary?: string;

  @ApiPropertyOptional()
  @IsOptional() @IsString()
  description?: string;

  @ApiPropertyOptional()
  @IsOptional() @IsString()
  thumbnailUrl?: string;

  @ApiPropertyOptional()
  @IsOptional() @IsNumber()
  price?: number;

  @ApiPropertyOptional()
  @IsOptional() @IsNumber()
  compareAtPrice?: number;

  @ApiPropertyOptional({ enum: course_level, description: '1 beginner / 2 intermediate / 3 advanced' })
  @IsOptional() @Type(() => Number) @IsEnum(course_level)
  level?: course_level;

  @ApiProperty()
  @IsString()
  language!: string;

  @ApiPropertyOptional()
  @IsOptional() @IsNumber()
  durationMinutes?: number;

  @ApiPropertyOptional({ enum: course_status, description: '0 draft / 1 published / 2 archived' })
  @IsOptional() @Type(() => Number) @IsEnum(course_status)
  status?: course_status;

  @ApiProperty()
  @IsUUID()
  categoryId!: string;

  @ApiProperty()
  @IsUUID()
  instructorId!: string;

  @ApiPropertyOptional()
  @IsOptional() @IsNumber()
  ratingAvg?: number;

  @ApiPropertyOptional()
  @IsOptional() @IsNumber()
  ratingCount?: number;

  @ApiPropertyOptional()
  @IsOptional() @IsNumber()
  studentCount?: number;

  @ApiPropertyOptional()
  @IsOptional() @IsDateString()
  publishedAt?: Date;

}

export type CreateCourseRequest = CreateCourseDto;
