// Generated by scaffold-dto-from-entity — DO NOT EDIT BY HAND. Re-run if entity changes.
import { PartialType } from '@nestjs/swagger';
import { CreateCourseDto } from './create-course.dto';

export class UpdateCourseDto extends PartialType(CreateCourseDto) {}

export type UpdateCourseRequest = UpdateCourseDto;
