// Generated by scaffold-zod-schema-from-dto — DO NOT EDIT BY HAND. Re-run when DTOs change.
import { z } from 'zod';

export const authResponseSchema = z.object({
  user: z.unknown(),
  accessToken: z.string().optional(),
  refreshToken: z.string().optional(),
});

export type AuthResponseInput = z.infer<typeof authResponseSchema>;

export const loginSchema = z.object({
  email: z.string().email(),
  password: z.string().min(1),
});

export type LoginInput = z.infer<typeof loginSchema>;

export const signupSchema = z.object({
  email: z.string().email(),
  password: z.string().min(1).max(255),
  role: z.number().optional(),
  passwordConfirm: z.string().optional(),
});

export type SignupInput = z.infer<typeof signupSchema>;
