// Generated by scaffold-zod-schema-from-dto — DO NOT EDIT BY HAND. Re-run when DTOs change.
import { z } from 'zod';

export const catalogueCategoryQuerySchema = z.object({
  active: z.unknown().optional(),
});

export type CatalogueCategoryQueryInput = z.infer<typeof catalogueCategoryQuerySchema>;
