// Generated by scaffold-zod-schema-from-dto — DO NOT EDIT BY HAND. Re-run when DTOs change.
import { z } from 'zod';

export const categoryResponseSchema = z.object({
  id: z.string(),
  name: z.string(),
  slug: z.string(),
  iconUrl: z.string().optional(),
  description: z.string().optional(),
  displayOrder: z.unknown().optional(),
  isActive: z.unknown().optional(),
  createdAt: z.unknown(),
  updatedAt: z.unknown(),
});

export type CategoryResponseInput = z.infer<typeof categoryResponseSchema>;

export const createCategorySchema = z.object({
  name: z.string(),
  slug: z.string(),
  iconUrl: z.string().optional(),
  description: z.string().optional(),
  displayOrder: z.number().optional(),
  isActive: z.boolean().optional(),
});

export type CreateCategoryInput = z.infer<typeof createCategorySchema>;
