// Generated by scaffold-zod-schema-from-dto — DO NOT EDIT BY HAND. Re-run when DTOs change.
import { z } from 'zod';
import { order_status } from '~/enums/order-status.enum';

export const createOrderSchema = z.object({
  orderNumber: z.string().max(20),
  status: z.nativeEnum(order_status).optional(),
  couponId: z.string().uuid().optional(),
  subtotal: z.number().min(0).optional(),
  discountTotal: z.number().min(0).optional(),
  total: z.number().min(0).optional(),
  paymentMethod: z.string().max(30).optional(),
  billingName: z.string().max(120),
  billingEmail: z.string().email(),
  billingCountry: z.string().max(60).optional(),
  placedAt: z.string(),
});

export type CreateOrderInput = z.infer<typeof createOrderSchema>;

export const orderResponseSchema = z.object({
  id: z.string(),
  orderNumber: z.string(),
  userId: z.string(),
  couponId: z.string().optional(),
  subtotal: z.unknown().optional(),
  discountTotal: z.unknown().optional(),
  total: z.unknown().optional(),
  status: z.unknown().optional(),
  paymentMethod: z.string().optional(),
  billingName: z.string(),
  billingEmail: z.string(),
  billingCountry: z.string().optional(),
  placedAt: z.unknown(),
  paidAt: z.unknown().optional(),
  createdAt: z.unknown(),
  updatedAt: z.unknown(),
});

export type OrderResponseInput = z.infer<typeof orderResponseSchema>;
