// Generated by scaffold-dto-from-entity — DO NOT EDIT BY HAND. Re-run if entity changes.
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export class CourseSectionResponseDto {
  @ApiProperty()
  id!: string;

  @ApiProperty()
  courseId!: string;

  @ApiProperty()
  title!: string;

  @ApiPropertyOptional()
  summary?: string;

  @ApiPropertyOptional()
  displayOrder?: number;

  @ApiProperty()
  createdAt!: Date;

  @ApiProperty()
  updatedAt!: Date;
}

export type CourseSectionResponse = CourseSectionResponseDto;
