// Generated by scaffold-dto-from-entity — DO NOT EDIT BY HAND. Re-run if entity changes.
import { PartialType } from '@nestjs/swagger';
import { CreateCourseSectionDto } from './create-course-section.dto';

export class UpdateCourseSectionDto extends PartialType(CreateCourseSectionDto) {}

export type UpdateCourseSectionRequest = UpdateCourseSectionDto;
