/**
 * Generated by scaffold-fixtures-per-entity. Inserts a CartItem row
 * directly via the repository. Useful for tests that need a pre-seeded record
 * without going through the full HTTP create flow.
 */
import { DataSource } from 'typeorm';

export interface CreateCartItemInput {
  [key: string]: unknown;
}

export async function createTestCartItem(
  dataSource: DataSource,
  overrides: CreateCartItemInput = {},
): Promise<Record<string, unknown>> {
  const meta = dataSource.entityMetadatas.find(
    (m) => m.name === 'CartItem' || m.tableName === 'cartItems',
  );
  if (!meta) {
    throw new Error('createTestCartItem: CartItem entity not registered with the DataSource');
  }
  const repo = dataSource.getRepository(meta.target);
  const row: Record<string, unknown> = {
    quantity: 0,
    unitPrice: 0,
    ...overrides,
  };
  const saved = await repo.save(row as never);
  return saved as unknown as Record<string, unknown>;
}
