// Generated by scaffold-test-fixtures-from-dto — DO NOT EDIT BY HAND. Re-run when DTOs change.

/**
 * Returns a payload that satisfies every class-validator constraint on CreateCategoryDto.
 * Use in e2e tests:
 *   await request(app).post('/categorys').send(validCreateCategoryPayload());
 */
export function validCreateCategoryPayload(overrides: Partial<Record<string, unknown>> = {}): Record<string, unknown> {
  return {
    name: 'fixturen',
    slug: 'fixtures',
    ...overrides,
  };
}
