// Generated by scaffold-test-fixtures-from-dto — DO NOT EDIT BY HAND. Re-run when DTOs change.
import { discount_type } from '../../src/common/enums/discount-type.enum';

/**
 * Returns a payload that satisfies every class-validator constraint on CreateCouponDto.
 * Use in e2e tests:
 *   await request(app).post('/coupons').send(validCreateCouponPayload());
 */
export function validCreateCouponPayload(overrides: Partial<Record<string, unknown>> = {}): Record<string, unknown> {
  return {
    code: 'fixturec',
    discountValue: 1,
    ...overrides,
  };
}
