/**
 * Generated by scaffold-fixtures-per-entity. Inserts a Coupon row
 * directly via the repository. Useful for tests that need a pre-seeded record
 * without going through the full HTTP create flow.
 */
import { DataSource } from 'typeorm';

export interface CreateCouponInput {
  [key: string]: unknown;
}

export async function createTestCoupon(
  dataSource: DataSource,
  overrides: CreateCouponInput = {},
): Promise<Record<string, unknown>> {
  const meta = dataSource.entityMetadatas.find(
    (m) => m.name === 'Coupon' || m.tableName === 'coupons',
  );
  if (!meta) {
    throw new Error('createTestCoupon: Coupon entity not registered with the DataSource');
  }
  const repo = dataSource.getRepository(meta.target);
  const row: Record<string, unknown> = {
    code: 'test-code',
    discountType: 'test-discountType',
    discountValue: 0,
    maxUses: 0,
    usedCount: 0,
    validFrom: new Date(),
    validUntil: new Date(),
    isActive: false,
    ...overrides,
  };
  const saved = await repo.save(row as never);
  return saved as unknown as Record<string, unknown>;
}
