/**
 * Generated by scaffold-fixtures-per-entity. Inserts a Course row
 * directly via the repository. Useful for tests that need a pre-seeded record
 * without going through the full HTTP create flow.
 */
import { DataSource } from 'typeorm';

export interface CreateCourseInput {
  [key: string]: unknown;
}

export async function createTestCourse(
  dataSource: DataSource,
  overrides: CreateCourseInput = {},
): Promise<Record<string, unknown>> {
  const meta = dataSource.entityMetadatas.find(
    (m) => m.name === 'Course' || m.tableName === 'courses',
  );
  if (!meta) {
    throw new Error('createTestCourse: Course entity not registered with the DataSource');
  }
  const repo = dataSource.getRepository(meta.target);
  const row: Record<string, unknown> = {
    title: 'test-title',
    slug: 'test-slug',
    summary: 'test-summary',
    description: 'test-description',
    thumbnailUrl: 'test-thumbnailUrl',
    price: 0,
    compareAtPrice: 0,
    level: 'test-level',
    language: 'test-language',
    durationMinutes: 0,
    status: 'test-status',
    ratingAvg: 0,
    ratingCount: 0,
    studentCount: 0,
    publishedAt: new Date(),
    ...overrides,
  };
  const saved = await repo.save(row as never);
  return saved as unknown as Record<string, unknown>;
}
