/**
 * Generated by scaffold-fixtures-per-entity. Inserts a CourseSection row
 * directly via the repository. Useful for tests that need a pre-seeded record
 * without going through the full HTTP create flow.
 */
import { DataSource } from 'typeorm';

export interface CreateCourseSectionInput {
  [key: string]: unknown;
}

export async function createTestCourseSection(
  dataSource: DataSource,
  overrides: CreateCourseSectionInput = {},
): Promise<Record<string, unknown>> {
  const meta = dataSource.entityMetadatas.find(
    (m) => m.name === 'CourseSection' || m.tableName === 'courseSections',
  );
  if (!meta) {
    throw new Error('createTestCourseSection: CourseSection entity not registered with the DataSource');
  }
  const repo = dataSource.getRepository(meta.target);
  const row: Record<string, unknown> = {
    title: 'test-title',
    summary: 'test-summary',
    displayOrder: 0,
    ...overrides,
  };
  const saved = await repo.save(row as never);
  return saved as unknown as Record<string, unknown>;
}
