// Generated by scaffold-test-fixtures-from-dto — DO NOT EDIT BY HAND. Re-run when DTOs change.

/**
 * Returns a payload that satisfies every class-validator constraint on CreateLessonProgressDto.
 * Use in e2e tests:
 *   await request(app).post('/lesson-progresss').send(validCreateLessonProgressPayload());
 */
export function validCreateLessonProgressPayload(overrides: Partial<Record<string, unknown>> = {}): Record<string, unknown> {
  return {
    enrollmentId: '00000000-0000-4000-8000-000000000000',
    lessonId: '00000000-0000-4000-8000-000000000000',
    ...overrides,
  };
}
