/**
 * Generated by scaffold-fixtures-per-entity. Inserts a Lesson row
 * directly via the repository. Useful for tests that need a pre-seeded record
 * without going through the full HTTP create flow.
 */
import { DataSource } from 'typeorm';

export interface CreateLessonInput {
  [key: string]: unknown;
}

export async function createTestLesson(
  dataSource: DataSource,
  overrides: CreateLessonInput = {},
): Promise<Record<string, unknown>> {
  const meta = dataSource.entityMetadatas.find(
    (m) => m.name === 'Lesson' || m.tableName === 'lessons',
  );
  if (!meta) {
    throw new Error('createTestLesson: Lesson entity not registered with the DataSource');
  }
  const repo = dataSource.getRepository(meta.target);
  const row: Record<string, unknown> = {
    title: 'test-title',
    contentType: 'test-contentType',
    videoUrl: 'test-videoUrl',
    content: 'test-content',
    durationMinutes: 0,
    displayOrder: 0,
    isPreview: false,
    isPublished: false,
    ...overrides,
  };
  const saved = await repo.save(row as never);
  return saved as unknown as Record<string, unknown>;
}
