/**
 * Generated by scaffold-fixtures-per-entity. Inserts a Order row
 * directly via the repository. Useful for tests that need a pre-seeded record
 * without going through the full HTTP create flow.
 */
import { DataSource } from 'typeorm';

export interface CreateOrderInput {
  [key: string]: unknown;
}

export async function createTestOrder(
  dataSource: DataSource,
  overrides: CreateOrderInput = {},
): Promise<Record<string, unknown>> {
  const meta = dataSource.entityMetadatas.find(
    (m) => m.name === 'Order' || m.tableName === 'orders',
  );
  if (!meta) {
    throw new Error('createTestOrder: Order entity not registered with the DataSource');
  }
  const repo = dataSource.getRepository(meta.target);
  const row: Record<string, unknown> = {
    orderNumber: 'test-orderNumber',
    subtotal: 0,
    discountTotal: 0,
    total: 0,
    status: 'test-status',
    paymentMethod: 'test-paymentMethod',
    billingName: 'test-billingName',
    billingEmail: 'test-billingEmail',
    billingCountry: 'test-billingCountry',
    placedAt: new Date(),
    paidAt: new Date(),
    ...overrides,
  };
  const saved = await repo.save(row as never);
  return saved as unknown as Record<string, unknown>;
}
