// Generated by scaffold-rich-text-editor — DO NOT EDIT BY HAND. Re-run to refresh.
import { useEditor, EditorContent } from '@tiptap/react';
import StarterKit from '@tiptap/starter-kit';
import { Button } from '~/components/ui/button';
import { Bold, Italic, List, ListOrdered, Quote, Strikethrough, Redo, Undo } from 'lucide-react';
import { cn } from '~/lib/utils';

export interface RichTextEditorProps {
  value?: string;
  onChange?: (html: string) => void;
  placeholder?: string;
  className?: string;
  testId?: string;
}

export function RichTextEditor({ value = '', onChange, placeholder = 'Write something…', className, testId = 'rich-text-editor' }: RichTextEditorProps) {
  const editor = useEditor({
    extensions: [StarterKit],
    // This app is server-rendered; tiptap must not render during SSR or the
    // client hydrates onto markup ProseMirror did not produce.
    immediatelyRender: false,
    content: value,
    editorProps: { attributes: { class: 'lesson-prose max-w-none focus:outline-none min-h-[120px] p-3 text-[14px]', placeholder } },
    onUpdate: ({ editor }) => { onChange?.(editor.getHTML()); },
  });

  if (!editor) return null;

  return (
    <div className={cn('rounded-md border', className)} data-testid={testId}>
      <div className="flex flex-wrap items-center gap-1 border-b p-2">
        <Button type="button" size="sm" variant="ghost" onClick={() => editor.chain().focus().toggleBold().run()} data-testid={`${testId}-bold`}><Bold className="h-4 w-4" /></Button>
        <Button type="button" size="sm" variant="ghost" onClick={() => editor.chain().focus().toggleItalic().run()} data-testid={`${testId}-italic`}><Italic className="h-4 w-4" /></Button>
        <Button type="button" size="sm" variant="ghost" onClick={() => editor.chain().focus().toggleStrike().run()} data-testid={`${testId}-strike`}><Strikethrough className="h-4 w-4" /></Button>
        <Button type="button" size="sm" variant="ghost" onClick={() => editor.chain().focus().toggleBlockquote().run()} data-testid={`${testId}-quote`}><Quote className="h-4 w-4" /></Button>
        <Button type="button" size="sm" variant="ghost" onClick={() => editor.chain().focus().toggleBulletList().run()} data-testid={`${testId}-ul`}><List className="h-4 w-4" /></Button>
        <Button type="button" size="sm" variant="ghost" onClick={() => editor.chain().focus().toggleOrderedList().run()} data-testid={`${testId}-ol`}><ListOrdered className="h-4 w-4" /></Button>
        <div className="mx-1 h-5 w-px bg-border" />
        <Button type="button" size="sm" variant="ghost" onClick={() => editor.chain().focus().undo().run()} data-testid={`${testId}-undo`}><Undo className="h-4 w-4" /></Button>
        <Button type="button" size="sm" variant="ghost" onClick={() => editor.chain().focus().redo().run()} data-testid={`${testId}-redo`}><Redo className="h-4 w-4" /></Button>
      </div>
      <EditorContent editor={editor} />
    </div>
  );
}
