// Generated by scaffold-service-from-controller — DO NOT EDIT BY HAND. Re-run when backend controllers change.
import { createAsyncThunk } from '@reduxjs/toolkit';
import { get } from '~/services/httpMethods/get';
import { post } from '~/services/httpMethods/post';
import { put } from '~/services/httpMethods/put';
import { patch } from '~/services/httpMethods/patch';
import { del } from '~/services/httpMethods/del';
import type * as UserTypes from '~/types/user';

function __cleanQuery(q?: Record<string, unknown>): Record<string, unknown> | undefined {
  if (!q || typeof q !== 'object') return undefined;
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(q)) {
    const t = typeof v;
    if (v != null && (t === 'string' || t === 'number' || t === 'boolean')) out[k] = v;
  }
  return Object.keys(out).length ? out : undefined;
}

export const list = createAsyncThunk(
  'user/list',
  async (query?: Record<string, unknown>) => {
    const res = await get('/admin/users', { params: __cleanQuery(query) });
    return res;
  },
);

export const detail = createAsyncThunk(
  'user/detail',
  async (id: string, query?: Record<string, unknown>) => {
    const res = await get(`/admin/users/${id}`, { params: __cleanQuery(query) });
    return res;
  },
);

// v103: aliases for naming conventions LLM-emitted pages tend to use.
// No runtime cost — same function reference re-exported under a verb-prefixed name.
export const fetchDetail = detail;

// v152: entity-canonical CRUD surface — the contract scaffold-crud-pages
// imports for every entity. Synthesized (not aliased) so ids and generated
// request INTERFACES stay assignable. See emitCanonicalCrudSurface().
export const fetchAdminUsersList = createAsyncThunk(
  'adminUsers/fetchAdminUsersList',
  async (params?: Record<string, unknown>) => {
    const res = await get<unknown>('/admin/users', { params: __cleanQuery(params) });
    return res;
  },
);

export const fetchAdminUsersById = createAsyncThunk(
  'adminUsers/fetchAdminUsersById',
  async (id: string) => {
    const res = await get<unknown>(`/admin/users/${id}`);
    return res;
  },
);

export async function createAdminUsers(data: unknown): Promise<unknown> {
  const res = await post<unknown>('/admin/users', data as Record<string, unknown>);
  return res;
}

export async function updateAdminUsers(id: string, data: unknown): Promise<unknown> {
  const res = await patch<unknown>(`/admin/users/${id}`, data as Record<string, unknown>);
  return res;
}

export async function deleteAdminUsers(id: string): Promise<void> {
  await del<void>(`/admin/users/${id}`);
}
