/** Generated by scaffold-auth-pages. */
import { createAsyncThunk } from '@reduxjs/toolkit';
import { get, post } from '~/services/httpMethods';
import type { AuthResponse, AuthUser, LoginRequest, SignupRequest } from '~/types/auth';

const BASE = '/auth';

export const loginThunk = createAsyncThunk<AuthResponse, LoginRequest>(
  'auth/login',
  (body) => post<AuthResponse>(`${BASE}/login`, body),
);

export const signupThunk = createAsyncThunk<AuthResponse, SignupRequest>(
  'auth/signup',
  (body) => post<AuthResponse>(`${BASE}/signup`, body),
);

export const fetchMeThunk = createAsyncThunk<AuthUser>(
  'auth/me',
  () => get<AuthUser>(`${BASE}/me`),
);

export function logout(): Promise<void> {
  return post<void>(`${BASE}/logout`, {});
}

export function refresh(): Promise<AuthResponse> {
  return post<AuthResponse>(`${BASE}/refresh`, {});
}

export function requestPasswordReset(body: { email: string }): Promise<void> {
  return post<void>(`${BASE}/forgot-password`, body);
}

export function resetPassword(body: { token: string; password: string }): Promise<void> {
  return post<void>(`${BASE}/reset-password`, body);
}

