// Generated by scaffold-service-from-controller — DO NOT EDIT BY HAND. Re-run when backend controllers change.
import { createAsyncThunk } from '@reduxjs/toolkit';
import { get } from '~/services/httpMethods/get';
import { post } from '~/services/httpMethods/post';
import { put } from '~/services/httpMethods/put';
import { patch } from '~/services/httpMethods/patch';
import { del } from '~/services/httpMethods/del';
import type * as CartTypes from '~/types/cart';

function __cleanQuery(q?: Record<string, unknown>): Record<string, unknown> | undefined {
  if (!q || typeof q !== 'object') return undefined;
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(q)) {
    const t = typeof v;
    if (v != null && (t === 'string' || t === 'number' || t === 'boolean')) out[k] = v;
  }
  return Object.keys(out).length ? out : undefined;
}

export const getCart = createAsyncThunk(
  'cart/getCart',
  async (query?: Record<string, unknown>) => {
    const res = await get('/cart', { params: __cleanQuery(query) });
    return res;
  },
);

export async function addItem(data: Record<string, unknown>): Promise<unknown> {
  const res = await post(`/cart/items`, data);
  return res;
}

export async function updateItem(id: string, data: Record<string, unknown>): Promise<unknown> {
  const res = await patch(`/cart/items/${id}`, data);
  return res;
}

export async function removeItem(id: string): Promise<unknown> {
  const res = await del(`/cart/items/${id}`);
  return res;
}

export async function clear(): Promise<unknown> {
  const res = await del(`/cart`);
  return res;
}

export async function applyCoupon(data: Record<string, unknown>): Promise<unknown> {
  const res = await post(`/cart/coupon`, data);
  return res;
}

// v103: aliases for naming conventions LLM-emitted pages tend to use.
// No runtime cost — same function reference re-exported under a verb-prefixed name.
export const fetchGetCart = getCart;
export const createAddItem = addItem;
export const deleteRemoveItem = removeItem;
export const deleteClear = clear;

// v152: entity-canonical CRUD surface — the contract scaffold-crud-pages
// imports for every entity. Synthesized (not aliased) so ids and generated
// request INTERFACES stay assignable. See emitCanonicalCrudSurface().
export const fetchCartManagementList = createAsyncThunk(
  'cartManagement/fetchCartManagementList',
  async (params?: Record<string, unknown>) => {
    const res = await get<unknown>('/cart', { params: __cleanQuery(params) });
    return res;
  },
);

export const fetchCartManagementById = createAsyncThunk(
  'cartManagement/fetchCartManagementById',
  async (id: string) => {
    const res = await get<unknown>(`/cart/${id}`);
    return res;
  },
);

export async function createCartManagement(data: unknown): Promise<unknown> {
  const res = await post<unknown>('/cart', data as Record<string, unknown>);
  return res;
}

export async function updateCartManagement(id: string, data: unknown): Promise<unknown> {
  const res = await patch<unknown>(`/cart/${id}`, data as Record<string, unknown>);
  return res;
}

export async function deleteCartManagement(id: string): Promise<void> {
  await del<void>(`/cart/${id}`);
}
