// Generated by scaffold-service-from-controller — DO NOT EDIT BY HAND. Re-run when backend controllers change.
import { createAsyncThunk } from '@reduxjs/toolkit';
import { get } from '~/services/httpMethods/get';
import { post } from '~/services/httpMethods/post';
import { put } from '~/services/httpMethods/put';
import { patch } from '~/services/httpMethods/patch';
import { del } from '~/services/httpMethods/del';
import type {
  CreateCategoryRequest,
  UpdateCategoryRequest,
  CategoryResponse,
} from '~/types/category';

function __cleanQuery(q?: Record<string, unknown>): Record<string, unknown> | undefined {
  if (!q || typeof q !== 'object') return undefined;
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(q)) {
    const t = typeof v;
    if (v != null && (t === 'string' || t === 'number' || t === 'boolean')) out[k] = v;
  }
  return Object.keys(out).length ? out : undefined;
}

export const fetchCategories = createAsyncThunk(
  'category/fetchAll',
  async (params?: Record<string, unknown>) => {
    const res = await get<{ items: CategoryResponse[]; total: number; page: number; limit: number; totalPages: number }>('/categories', { params: __cleanQuery(params) });
    return res;
  },
);

export const fetchCategoryById = createAsyncThunk(
  'category/fetchById',
  async (id: string) => {
    const res = await get<CategoryResponse>(`/categories/${id}`);
    return res;
  },
);

export async function createCategory(data: CreateCategoryRequest): Promise<CategoryResponse> {
  const res = await post<CategoryResponse>('/categories', data);
  return res;
}

export async function updateCategory(id: string, data: UpdateCategoryRequest): Promise<CategoryResponse> {
  const res = await patch<CategoryResponse>(`/categories/${id}`, data);
  return res;
}

export async function deleteCategory(id: string): Promise<void> {
  await del<void>(`/categories/${id}`);
}

// LLM-friendly aliases — same thunk under common alternate names.
export const fetchCategoryList = fetchCategories;
export const fetchCategory = fetchCategoryById;
export const removeCategory = deleteCategory;

// v118/v120 scaffold-frontend-contract-doctor R4 — stub exports for page/slice-
// imported symbols this service never defined (crud-page ↔ service-from-controller
// name drift). Thunk-used names (referenced as .fulfilled/.pending/.rejected in a
// slice) MUST be createAsyncThunk or addCase crashes SSR; others are any plain fns.
export type FetchCategoryListParams = Record<string, unknown>;
