// Generated by scaffold-service-from-controller — DO NOT EDIT BY HAND. Re-run when backend controllers change.
import { createAsyncThunk } from '@reduxjs/toolkit';
import { get } from '~/services/httpMethods/get';
import { post } from '~/services/httpMethods/post';
import { put } from '~/services/httpMethods/put';
import { patch } from '~/services/httpMethods/patch';
import { del } from '~/services/httpMethods/del';
import type {
  CreateCourseSectionRequest,
  UpdateCourseSectionRequest,
  CourseSectionResponse,
} from '~/types/course-section';

function __cleanQuery(q?: Record<string, unknown>): Record<string, unknown> | undefined {
  if (!q || typeof q !== 'object') return undefined;
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(q)) {
    const t = typeof v;
    if (v != null && (t === 'string' || t === 'number' || t === 'boolean')) out[k] = v;
  }
  return Object.keys(out).length ? out : undefined;
}

export const fetchCourseSections = createAsyncThunk(
  'courseSection/fetchAll',
  async (params?: Record<string, unknown>) => {
    const res = await get<{ items: CourseSectionResponse[]; total: number; page: number; limit: number; totalPages: number }>('/course-sections', { params: __cleanQuery(params) });
    return res;
  },
);

export const fetchCourseSectionById = createAsyncThunk(
  'courseSection/fetchById',
  async (id: string) => {
    const res = await get<CourseSectionResponse>(`/course-sections/${id}`);
    return res;
  },
);

export async function createCourseSection(data: CreateCourseSectionRequest): Promise<CourseSectionResponse> {
  const res = await post<CourseSectionResponse>('/course-sections', data);
  return res;
}

export async function updateCourseSection(id: string, data: UpdateCourseSectionRequest): Promise<CourseSectionResponse> {
  const res = await patch<CourseSectionResponse>(`/course-sections/${id}`, data);
  return res;
}

export async function deleteCourseSection(id: string): Promise<void> {
  await del<void>(`/course-sections/${id}`);
}

// LLM-friendly aliases — same thunk under common alternate names.
export const fetchCourseSectionList = fetchCourseSections;
export const fetchCourseSection = fetchCourseSectionById;
export const removeCourseSection = deleteCourseSection;

// v118/v120 scaffold-frontend-contract-doctor R4 — stub exports for page/slice-
// imported symbols this service never defined (crud-page ↔ service-from-controller
// name drift). Thunk-used names (referenced as .fulfilled/.pending/.rejected in a
// slice) MUST be createAsyncThunk or addCase crashes SSR; others are any plain fns.
export type FetchCourseSectionListParams = Record<string, unknown>;
