// Generated by scaffold-service-from-controller — DO NOT EDIT BY HAND. Re-run when backend controllers change.
import { createAsyncThunk } from '@reduxjs/toolkit';
import { get } from '~/services/httpMethods/get';
import { post } from '~/services/httpMethods/post';
import { put } from '~/services/httpMethods/put';
import { patch } from '~/services/httpMethods/patch';
import { del } from '~/services/httpMethods/del';
import type * as OrderTypes from '~/types/order';
import type { OrderResponse } from '~/types/order';

function __cleanQuery(q?: Record<string, unknown>): Record<string, unknown> | undefined {
  if (!q || typeof q !== 'object') return undefined;
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(q)) {
    const t = typeof v;
    if (v != null && (t === 'string' || t === 'number' || t === 'boolean')) out[k] = v;
  }
  return Object.keys(out).length ? out : undefined;
}

export async function create(data: Record<string, unknown>): Promise<unknown> {
  const res = await post(`/orders`, data);
  return res;
}

export const findAll = createAsyncThunk(
  'order/findAll',
  async (query?: Record<string, unknown>) => {
    const res = await get('/orders', { params: __cleanQuery(query) });
    return res;
  },
);

export const findOne = createAsyncThunk(
  'order/findOne',
  async (id: string, query?: Record<string, unknown>) => {
    const res = await get(`/orders/${id}`, { params: __cleanQuery(query) });
    return res;
  },
);

export async function pay(id: string, data: Record<string, unknown>): Promise<unknown> {
  const res = await post(`/orders/${id}/pay`, data);
  return res;
}

export async function remove(id: string): Promise<unknown> {
  const res = await del(`/orders/${id}`);
  return res;
}

// v103: aliases for naming conventions LLM-emitted pages tend to use.
// No runtime cost — same function reference re-exported under a verb-prefixed name.
export const fetchFindAll = findAll;
export const fetchFindOne = findOne;
export const createPay = pay;
export const deleteRemove = remove;

// v152: entity-canonical CRUD surface — the contract scaffold-crud-pages
// imports for every entity. Synthesized (not aliased) so ids and generated
// request INTERFACES stay assignable. See emitCanonicalCrudSurface().
export const fetchOrderList = createAsyncThunk(
  'order/fetchOrderList',
  async (params?: Record<string, unknown>) => {
    const res = await get<{ items: OrderResponse[]; total: number; page: number; limit: number; totalPages: number }>('/orders', { params: __cleanQuery(params) });
    return res;
  },
);

export const fetchOrderById = createAsyncThunk(
  'order/fetchOrderById',
  async (id: string) => {
    const res = await get<OrderResponse>(`/orders/${id}`);
    return res;
  },
);

export async function createOrder(data: unknown): Promise<OrderResponse> {
  const res = await post<OrderResponse>('/orders', data as Record<string, unknown>);
  return res;
}

export async function updateOrder(id: string, data: unknown): Promise<OrderResponse> {
  const res = await patch<OrderResponse>(`/orders/${id}`, data as Record<string, unknown>);
  return res;
}

export async function deleteOrder(id: string): Promise<void> {
  await del<void>(`/orders/${id}`);
}

// v118/v120 scaffold-frontend-contract-doctor R4 — stub exports for page/slice-
// imported symbols this service never defined (crud-page ↔ service-from-controller
// name drift). Thunk-used names (referenced as .fulfilled/.pending/.rejected in a
// slice) MUST be createAsyncThunk or addCase crashes SSR; others are any plain fns.
export type FetchOrderListParams = Record<string, unknown>;
