// Generated by scaffold-service-from-controller — DO NOT EDIT BY HAND. Re-run when backend controllers change.
import { createAsyncThunk } from '@reduxjs/toolkit';
import { get } from '~/services/httpMethods/get';
import { post } from '~/services/httpMethods/post';
import { put } from '~/services/httpMethods/put';
import { patch } from '~/services/httpMethods/patch';
import { del } from '~/services/httpMethods/del';
import type {
  CreateOrderItemRequest,
  UpdateOrderItemRequest,
  OrderItemResponse,
} from '~/types/order-item';

function __cleanQuery(q?: Record<string, unknown>): Record<string, unknown> | undefined {
  if (!q || typeof q !== 'object') return undefined;
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(q)) {
    const t = typeof v;
    if (v != null && (t === 'string' || t === 'number' || t === 'boolean')) out[k] = v;
  }
  return Object.keys(out).length ? out : undefined;
}

export const fetchOrderItems = createAsyncThunk(
  'orderItem/fetchAll',
  async (params?: Record<string, unknown>) => {
    const res = await get<{ items: OrderItemResponse[]; total: number; page: number; limit: number; totalPages: number }>('/order-items', { params: __cleanQuery(params) });
    return res;
  },
);

export const fetchOrderItemById = createAsyncThunk(
  'orderItem/fetchById',
  async (id: string) => {
    const res = await get<OrderItemResponse>(`/order-items/${id}`);
    return res;
  },
);

export async function createOrderItem(data: CreateOrderItemRequest): Promise<OrderItemResponse> {
  const res = await post<OrderItemResponse>('/order-items', data);
  return res;
}

export async function updateOrderItem(id: string, data: UpdateOrderItemRequest): Promise<OrderItemResponse> {
  const res = await patch<OrderItemResponse>(`/order-items/${id}`, data);
  return res;
}

export async function deleteOrderItem(id: string): Promise<void> {
  await del<void>(`/order-items/${id}`);
}

// LLM-friendly aliases — same thunk under common alternate names.
export const fetchOrderItemList = fetchOrderItems;
export const fetchOrderItem = fetchOrderItemById;
export const removeOrderItem = deleteOrderItem;

// v118/v120 scaffold-frontend-contract-doctor R4 — stub exports for page/slice-
// imported symbols this service never defined (crud-page ↔ service-from-controller
// name drift). Thunk-used names (referenced as .fulfilled/.pending/.rejected in a
// slice) MUST be createAsyncThunk or addCase crashes SSR; others are any plain fns.
export type FetchOrderItemListParams = Record<string, unknown>;
