// Generated by scaffold-admin-crud — admin read surface over CourseService
import { Controller, Get, Post, Body, Param, Query, ParseUUIDPipe, UseGuards, HttpCode, HttpStatus } from '@nestjs/common';
import { ApiTags, ApiOperation } from '@nestjs/swagger';
import { JwtAuthGuard } from '../../core/guards/jwt-auth.guard';
import { RolesGuard } from '../../core/guards/roles.guard';
import { Roles } from '../../core/decorators/roles.decorator';
import { CourseService } from './course.service';
import { CreateLessonDto } from '../lesson/dtos/create-lesson.dto';

@ApiTags('admin/courses')
@Controller('admin/courses')
@UseGuards(JwtAuthGuard, RolesGuard)
@Roles('admin', '99')
export class AdminCoursesController {
  constructor(private readonly service: CourseService) {}

  @Get()
  @ApiOperation({ summary: 'Admin: list all courses' })
  async list(@Query() query: Record<string, unknown>) {
    const items = await this.service.findAll();
    return { items, total: items.length };
  }

  @Get(':id')
  @ApiOperation({ summary: 'Admin: get one courses by id' })
  async detail(@Param('id', ParseUUIDPipe) id: string) {
    return this.service.findByIdOrFail(id);
  }

  @Post(':id/lessons')
  @HttpCode(HttpStatus.CREATED)
  @ApiOperation({ summary: 'Admin: add a lesson to a course' })
  async addLesson(
    @Param('id', ParseUUIDPipe) id: string,
    @Body() dto: CreateLessonDto,
  ) {
    return this.service.addLesson(id, dto);
  }
}
