// Generated by scaffold-auth-module
/** Generated by scaffold-auth-module. */
import { ApiProperty } from '@nestjs/swagger';

/**
 * AuthResponseDto — what /auth/signup, /auth/login, /auth/refresh emit
 * BEFORE SetTokenInterceptor runs. The interceptor reads accessToken /
 * refreshToken, sets httpOnly cookies, and strips them from the JSON body
 * that goes to the client. Clients see only { user }.
 */
export class AuthResponseDto {
  @ApiProperty({ description: 'Current user (without password)' })
  user!: Record<string, unknown>;

  // accessToken + refreshToken are present on the controller-return
  // object but stripped by SetTokenInterceptor before responding.
  accessToken?: string;
  refreshToken?: string;
}
