// Generated by scaffold-auth-module
/** Generated by scaffold-auth-module. Field set comes from SPEC.yaml auth.signup_fields. */
import { ApiProperty } from '@nestjs/swagger';
import { IsEmail, IsNotEmpty, IsOptional, IsString, MaxLength, MinLength } from 'class-validator';

/**
 * The password policy, in ONE place. Password rules are asked for by more than one DTO — signup,
 * reset-confirm, change-password — and an LLM writing the second one imports them from here, which
 * is the right instinct: two regexes for one policy is two policies. It only failed to compile
 * because the template kept the rule inline and exported nothing.
 */
export const PASSWORD_PATTERN = /^(?=.*[A-Za-z])(?=.*\d).{8,64}$/;
export const PASSWORD_MESSAGE = 'Password must be 8-64 characters and include letters and numbers';

export class SignupDto {
  @ApiProperty()
  @IsString()
  @IsNotEmpty()
  @MinLength(2)
  @MaxLength(120)
  fullName!: string;

  @ApiProperty()
  @IsEmail()
  @IsNotEmpty()
  @MaxLength(255)
  email!: string;

  @ApiProperty()
  @IsString()
  @MaxLength(255)
  @IsNotEmpty()
  password!: string;

  @ApiProperty({ description: 'Password confirmation (must match password)', example: 'CorrectHorseBatteryStaple1!', required: false })
  @IsOptional()
  @IsString()
  passwordConfirm?: string;

}
