/**
 * Generated by scaffold-entities from PROJECT_DATABASE.md table `lesson_progress`.
 * Edits to this file are preserved across re-runs ONLY when the table
 * definition is unchanged; otherwise re-run with --force to regenerate.
 */
import { Column, Entity, Index, JoinColumn, ManyToOne } from 'typeorm';
import { BaseEntity } from '../../core/base/base.entity';
import { Enrollment } from '../enrollment/enrollment.entity';
import { Lesson } from '../lesson/lesson.entity';

@Index('UQ_lesson_progress_enrollment_id_lesson_id', ['enrollmentId', 'lessonId'], { unique: true })
@Entity('lesson_progress')
export class LessonProgress extends BaseEntity {
  @Column({ name: 'enrollment_id', type: 'uuid' })
  enrollmentId!: string;

  @Column({ name: 'lesson_id', type: 'uuid' })
  lessonId!: string;

  @Column({ name: 'is_completed', type: 'boolean', default: false })
  isCompleted!: boolean;

  @Column({ name: 'watched_seconds', type: 'int', default: 0 })
  watchedSeconds!: number;

  @Column({ name: 'completed_at', type: 'timestamptz', nullable: true })
  completedAt?: Date;

  // ── Relations ──

  @ManyToOne(() => Enrollment, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'enrollment_id' })
  enrollment?: Enrollment;

  @ManyToOne(() => Lesson, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'lesson_id' })
  lesson?: Lesson;

}
