// Generated by scaffold-toast-system — DO NOT EDIT BY HAND. Re-run to refresh.
import { toast as sonnerToast } from 'sonner';

// Thin typed facade so the LLM has ONE place to call toasts from.
// All call sites should: import { toast } from '~/lib/toast'.
export const toast = {
  success: (msg: string, opts?: Parameters<typeof sonnerToast.success>[1]) => sonnerToast.success(msg, opts),
  error: (msg: string, opts?: Parameters<typeof sonnerToast.error>[1]) => sonnerToast.error(msg, opts),
  info: (msg: string, opts?: Parameters<typeof sonnerToast.info>[1]) => sonnerToast.info(msg, opts),
  warning: (msg: string, opts?: Parameters<typeof sonnerToast.warning>[1]) => sonnerToast.warning(msg, opts),
  promise: <T,>(p: Promise<T>, msgs: { loading: string; success: string; error: string }) => sonnerToast.promise(p, msgs),
};
