// Generated by scaffold-modal-manager — DO NOT EDIT BY HAND. Re-run to refresh.
import { useCallback, useRef, useState, type ReactNode } from 'react';
import { ConfirmContext, type ConfirmOptions } from '~/hooks/useConfirm';
import { ConfirmModal } from '~/components/modals/ConfirmModal';

export function ConfirmProvider({ children }: { children: ReactNode }) {
  const [opts, setOpts] = useState<ConfirmOptions | null>(null);
  const resolveRef = useRef<((v: boolean) => void) | null>(null);

  const confirm = useCallback((o: ConfirmOptions) => {
    setOpts(o);
    return new Promise<boolean>((resolve) => { resolveRef.current = resolve; });
  }, []);

  const handle = (value: boolean) => () => {
    setOpts(null);
    resolveRef.current?.(value);
    resolveRef.current = null;
  };

  return (
    <ConfirmContext.Provider value={confirm}>
      {children}
      {opts && (
        <ConfirmModal
          open
          {...opts}
          onConfirm={handle(true)}
          onCancel={handle(false)}
        />
      )}
    </ConfirmContext.Provider>
  );
}
