/**
 * Generated by scaffold-unit-tests for CartItemService.
 * Asserts BaseService inheritance contracts. Override or extend in
 * a sibling .spec.ts to test custom service methods.
 */
import { NotFoundException } from '@nestjs/common';
import { CartItemService } from '../../src/modules/cart-item/cart-item.service';

describe('CartItemService unit', () => {
  let service: CartItemService;
  let mockRepo: {
    findById: jest.Mock;
    findAll: jest.Mock;
    create: jest.Mock;
    update: jest.Mock;
    softDelete: jest.Mock;
  };

  beforeEach(() => {
    mockRepo = {
      findById: jest.fn(),
      findAll: jest.fn(),
      create: jest.fn(),
      update: jest.fn(),
      softDelete: jest.fn(),
    };
    // BaseService takes (repository, entityName)
    service = new CartItemService(mockRepo as never);
  });

  it('findByIdOrFail throws NotFoundException when repo returns null', async () => {
    mockRepo.findById.mockResolvedValue(null);
    await expect(service.findByIdOrFail?.('missing-id') ?? Promise.reject(new Error('no method'))).rejects.toBeDefined();
  });

  it('findByIdOrFail returns entity when repo resolves', async () => {
    const mock = { id: 'abc' };
    mockRepo.findById.mockResolvedValue(mock);
    if (typeof service.findByIdOrFail === 'function') {
      const result = await service.findByIdOrFail('abc');
      expect(result).toBe(mock);
    }
  });

  it('findAll delegates to repository.findAll', async () => {
    mockRepo.findAll.mockResolvedValue([]);
    if (typeof service.findAll === 'function') {
      await service.findAll();
      expect(mockRepo.findAll).toHaveBeenCalled();
    }
  });
});
