import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { TokenModule } from './infrastructure/token/token.module';
import jwtConfig from './config/jwt.config';
import { AdminConsoleModule } from './modules/admin-console/admin-console.module';
import { AuthModule } from './modules/auth/auth.module';
import { CartItemModule } from './modules/cart-item/cart-item.module';
import { CartModule } from './modules/cart/cart.module';
import { CatalogueModule } from './modules/catalogue/catalogue.module';
import { CategoryModule } from './modules/category/category.module';
import { CouponModule } from './modules/coupon/coupon.module';
import { CourseModule } from './modules/course/course.module';
import { CourseSectionModule } from './modules/course-section/course-section.module';
import { DashboardModule } from './modules/dashboard/dashboard.module';
import { EnrollmentModule } from './modules/enrollment/enrollment.module';
import { HealthModule } from './modules/health/health.module';
import { LessonModule } from './modules/lesson/lesson.module';
import { LessonProgressModule } from './modules/lesson-progress/lesson-progress.module';
import { OrderItemModule } from './modules/order-item/order-item.module';
import { OrderModule } from './modules/order/order.module';
import { UserModule } from './modules/user/user.module';
import { FileStorageModule } from './infrastructure/file-storage/file-storage.module';
import { MailModule } from './infrastructure/mail/mail.module';
import { buildDbConnection, buildDbPaths } from './database/connection.options';

/**
 * AppModule — generated by normalize-app-module.js.
 * Custom imports/providers go between NORMALIZE_KEEP_TOP/BOTTOM markers.
 * Anything outside the markers is regenerated.
 */
@Module({
  imports: [ConfigModule.forRoot({ isGlobal: true, load: [jwtConfig] }),
    TypeOrmModule.forRootAsync({
      imports: [ConfigModule],
      inject: [ConfigService],
      useFactory: makeTypeOrmConfig,
    }),
    // FIRST, deliberately. CatalogueController owns the PUBLIC read surface at the root
    // (`courses`, `courses/:slug`, `categories`, `instructors`) and the per-entity CRUD
    // controllers declare the same paths behind a guard. Nest resolves whichever registered
    // first, and registration follows DEPENDENCY order, not this list — once CartModule began
    // importing CourseModule, CourseController registered ahead of the catalogue and
    // `GET /api/courses` started answering 401 to guests. Keeping the catalogue at the head of
    // the graph makes the public surface win regardless of what the other modules import.
    CatalogueModule,
    TokenModule,
    AdminConsoleModule,
    AuthModule,
    CartItemModule,
    CartModule,
    CategoryModule,
    CouponModule,
    CourseModule,
    CourseSectionModule,
    DashboardModule,
    EnrollmentModule,
    HealthModule,
    LessonModule,
    LessonProgressModule,
    OrderItemModule,
    OrderModule,
    UserModule, FileStorageModule, MailModule],
})
export class AppModule {}

function makeTypeOrmConfig(config: ConfigService) {
  // Connection details from database/connection.options.ts — the same builder the
  // migration CLI uses. This function used to read POSTGRES_* only, so a deployment
  // configured the way every hosted Postgres hands it to you (one DATABASE_URL) ran its
  // migrations against the real database while the app connected to localhost.
  const paths = buildDbPaths(__dirname);
  return {
    type: 'postgres' as const,
    ...buildDbConnection((k: string) => config.get<string>(k) ?? process.env[k]),
    autoLoadEntities: true,
    entities: paths.entities,
    synchronize: process.env.TYPEORM_SYNCHRONIZE === 'true' || process.env.NODE_ENV === 'test',
    migrationsRun: process.env.MIGRATIONS_AUTO_RUN !== 'false',
    migrations: paths.migrations,
  };
}
