import './patch-typeorm-migration-order';
// Generated by scaffold-data-source.
//
// Canonical TypeORM DataSource. Used by:
//   - npm scripts: `typeorm migration:run`, `migration:generate`
//   - seed.ts standalone connection (it builds its own; this is the CLI entry)
//
// Connection config: DATABASE_URL takes precedence; otherwise individual
// vars are read from process.env with POSTGRES_* preferred over DB_* so the
// CLI/migration path matches the app.module.ts forRootAsync runtime config.
//
// NOTE: exactly ONE DataSource instance is exported (AppDataSource). The
// TypeORM CLI rejects a file that exports more than one DataSource, so do NOT
// add `export default` here.
import 'reflect-metadata';
import * as path from 'path';
import { DataSource, DataSourceOptions } from 'typeorm';
import { config as dotenv } from 'dotenv';

dotenv();

const SRC = path.resolve(__dirname, '..');

function buildOptions(): DataSourceOptions {
  const url = process.env.DATABASE_URL || process.env.DB_URL;
  const common = {
    type: 'postgres' as const,
    entities: [path.join(SRC, 'modules/**/*.entity.{ts,js}')],
    migrations: [path.join(SRC, 'database/migrations/*.{ts,js}')],
    synchronize: process.env.TYPEORM_SYNCHRONIZE === 'true',
    migrationsRun: process.env.MIGRATIONS_AUTO_RUN !== 'false',
    logging: process.env.TYPEORM_LOGGING === 'true',
  };
  if (url) {
    return { ...common, url };
  }
  return {
    ...common,
    host: process.env.POSTGRES_HOST || process.env.DB_HOST || 'localhost',
    port: parseInt(process.env.POSTGRES_PORT || process.env.DB_PORT || '5432', 10),
    username: process.env.POSTGRES_USER || process.env.DB_USERNAME || process.env.DB_USER || 'postgres',
    password: process.env.POSTGRES_PASSWORD || process.env.DB_PASSWORD || 'postgres',
    database: process.env.POSTGRES_DATABASE || process.env.DB_DATABASE || process.env.DB_NAME || 'app',
  };
}

export const dataSourceOptions: DataSourceOptions = buildOptions();
export const AppDataSource = new DataSource(dataSourceOptions);
