/**
 * Generated by core-templates. Generic dashboard query endpoint.
 *
 *   POST /dashboard/query   { entity, op: 'count', where?, group? }
 *
 * The service uses TypeORM's metadata to resolve entity by tableName and
 * builds a QueryBuilder. Operations supported:
 *   - count                          → { value: number }
 *   - count + group:<field>          → { items: [{ key, count }] }
 *   - count + group:day + window:Nd  → { items: [{ key: 'YYYY-MM-DD', count }] }
 *
 * Frontend dashboard pages POST DSL strings parsed client-side into this
 * structured shape. Endpoint is JWT-guarded (RoleGuard layered by caller
 * if dashboard requires admin role — see frontend role_required flag).
 */
import { Body, Controller, HttpCode, HttpStatus, Post, UseGuards } from '@nestjs/common';
import { ApiOperation, ApiResponse, ApiTags } from '@nestjs/swagger';

import { JwtAuthGuard } from '../../core/guards/jwt-auth.guard';
import { DashboardQueryDto, DashboardResult } from './dtos/dashboard-query.dto';
import { DashboardService } from './dashboard.service';

@ApiTags('dashboard')
@Controller('dashboard')
@UseGuards(JwtAuthGuard)
export class DashboardController {
  constructor(private readonly service: DashboardService) {}

  @Post('query')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Run a dashboard KPI/chart query' })
  @ApiResponse({ status: 200, description: '{ value } or { items }' })
  query(@Body() body: DashboardQueryDto): Promise<DashboardResult> {
    return this.service.query(body);
  }
}
