/** Generated by scaffold-convert-wire-routes. */
import { type RouteConfig, layout, route } from '@react-router/dev/routes';

// scaffold-routes-imports-start
import { adminRoutes } from './routes/admin.routes';
import { adminOverviewRoutes } from './routes/admin-overview.routes';
import { authRoutes } from './routes/auth.routes';
import { publicRoutes } from './routes/public.routes';
import { safetyNetRoutes } from './routes/safety-net.routes';
// scaffold-routes-imports-end

// Aggregated route config. Edit the per-feature *.routes.ts files,
// not this file — the convert-wire-routes scaffold regenerates it on
// each frontend phase.
// Every route renders INSIDE the shared chrome (sidebar + top bar). The generated route
// files are flat, so pages/layout.tsx wrapped nothing and each admin screen rendered its
// content with no chrome at all — the design declares that chrome Layout-owned
// (data-shell="sidebar"/"topbar"), and nesting the routes is what makes it so.
export default [
  layout('pages/layout.tsx', [
    // scaffold-routes-spread-start
    ...adminRoutes,
    ...adminOverviewRoutes,
    ...authRoutes,
    ...publicRoutes,
    ...safetyNetRoutes,
    // scaffold-routes-spread-end
  ]),
  route('*', 'pages/not-found.tsx'),
] satisfies RouteConfig;
