/**
 * Generated by scaffold-entities from PROJECT_DATABASE.md table `lessons`.
 * Edits to this file are preserved across re-runs ONLY when the table
 * definition is unchanged; otherwise re-run with --force to regenerate.
 */
import { Column, Entity, Index, JoinColumn, ManyToOne } from 'typeorm';
import { BaseEntity } from '../../core/base/base.entity';
import { CourseSection } from '../course-section/course-section.entity';
import { lesson_type } from '../../common/enums/lesson-type.enum';

@Index('IDX_lessons_section_id_display_order', ['sectionId', 'displayOrder'])
@Entity('lessons')
export class Lesson extends BaseEntity {
  @Column({ name: 'section_id', type: 'uuid' })
  sectionId!: string;

  @Column({ type: 'varchar', length: 200 })
  title!: string;

  @Column({ name: 'content_type', type: 'int', default: 1 })
  contentType!: lesson_type;

  @Column({ name: 'video_url', type: 'varchar', length: 500, nullable: true })
  videoUrl?: string;

  @Column({ type: 'text', nullable: true })
  content?: string;

  @Column({ name: 'duration_minutes', type: 'int', default: 0 })
  durationMinutes!: number;

  @Column({ name: 'display_order', type: 'int', default: 0 })
  displayOrder!: number;

  @Column({ name: 'is_preview', type: 'boolean', default: false })
  isPreview!: boolean;

  @Column({ name: 'is_published', type: 'boolean', default: true })
  isPublished!: boolean;

  // ── Relations ──

  @ManyToOne(() => CourseSection, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'section_id' })
  section?: CourseSection;

}
