/**
 * Generated by scaffold-data-table. Reusable admin-style table.
 *
 * Drop into any page with a list of records. Wires sort/pagination via
 * URL search params (RR7 useSearchParams), exposes a `columns` config
 * for fully type-safe rendering, and ships with empty/loading/error
 * states + data-testid coverage out of the box.
 *
 * Usage:
 *   <DataTable
 *     data={items}
 *     columns={[
 *       { key: 'email', label: 'Email', sortable: true },
 *       { key: 'createdAt', label: 'Created', sortable: true, format: 'date' },
 *     ]}
 *     loading={loading}
 *     error={error}
 *     pagination={pagination}
 *     testId="user-list"
 *     rowAction={(row) => <Link to={row.id}>Edit</Link>}
 *   />
 */
import { useTranslation } from 'react-i18next';
import { useSearchParams } from 'react-router';

type Format = 'text' | 'date' | 'currency' | 'number';

export interface DataTableColumn<T> {
  key: keyof T & string;
  label: string;
  sortable?: boolean;
  format?: Format;
  render?: (row: T) => React.ReactNode;
  width?: string;
}

export interface PaginationState {
  page: number;
  limit: number;
  total: number;
  totalPages: number;
}

export interface DataTableProps<T extends Record<string, unknown>> {
  data: T[];
  columns: DataTableColumn<T>[];
  loading?: boolean;
  error?: string | null;
  pagination?: PaginationState;
  testId: string;
  rowAction?: (row: T) => React.ReactNode;
  rowKey?: (row: T) => string;
  emptyMessage?: string;
}

function defaultFormat(value: unknown, format?: Format): string {
  if (value === null || value === undefined) return '';
  if (format === 'date') {
    try { return new Date(String(value)).toLocaleString(); } catch { return String(value); }
  }
  if (format === 'currency') return new Intl.NumberFormat(undefined, { style: 'currency', currency: 'USD' }).format(Number(value));
  if (format === 'number') return new Intl.NumberFormat().format(Number(value));
  return String(value);
}

export function DataTable<T extends Record<string, unknown>>({
  data,
  columns,
  loading,
  error,
  pagination,
  testId,
  rowAction,
  rowKey,
  emptyMessage,
}: DataTableProps<T>) {
  const { t } = useTranslation('common');
  const [params, setParams] = useSearchParams();
  const sortParam = params.get('sort') ?? '';

  function toggleSort(field: string) {
    const next = new URLSearchParams(params);
    if (sortParam === field) next.set('sort', '-' + field);
    else if (sortParam === '-' + field) next.delete('sort');
    else next.set('sort', field);
    next.delete('page');
    setParams(next);
  }

  function changePage(delta: number) {
    if (!pagination) return;
    const next = new URLSearchParams(params);
    const newPage = Math.max(1, pagination.page + delta);
    next.set('page', String(newPage));
    setParams(next);
  }

  if (loading && data.length === 0) {
    return <div className="p-6" data-testid={testId + '-loading'}>{t('actions.loading')}</div>;
  }
  if (error) {
    return <div className="p-6 text-destructive" data-testid={testId + '-error'}>{error}</div>;
  }

  if (data.length === 0) {
    return (
      <div className="rounded-lg border p-12 text-center" data-testid={testId + '-empty'}>
        <p className="text-lg font-medium">{emptyMessage ?? t('empty.title')}</p>
      </div>
    );
  }

  return (
    <div data-testid={testId}>
      <table className="w-full border-collapse" data-testid={testId + '-table'}>
        <thead>
          <tr className="border-b text-left text-sm text-muted-foreground">
            {columns.map((col) => (
              <th
                key={col.key}
                className={col.sortable ? 'py-2 pr-4 cursor-pointer select-none' : 'py-2 pr-4'}
                onClick={col.sortable ? () => toggleSort(col.key) : undefined}
                data-testid={testId + '-th-' + col.key}
                style={col.width ? { width: col.width } : undefined}
              >
                {col.label}
                {col.sortable && (
                  <span>
                    {sortParam === col.key ? ' ↑' : sortParam === '-' + col.key ? ' ↓' : ''}
                  </span>
                )}
              </th>
            ))}
            {rowAction && <th className="py-2 pr-4" data-testid={testId + '-th-actions'}>{t('actions.actions') ?? 'Actions'}</th>}
          </tr>
        </thead>
        <tbody>
          {data.map((row, idx) => {
            const k = rowKey ? rowKey(row) : String((row as Record<string, unknown>).id ?? idx);
            return (
              <tr key={k} className="border-b" data-testid={testId + '-row-' + k}>
                {columns.map((col) => (
                  <td key={col.key} className="py-3 pr-4" data-testid={testId + '-cell-' + k + '-' + col.key}>
                    {col.render ? col.render(row) : defaultFormat(row[col.key], col.format)}
                  </td>
                ))}
                {rowAction && <td className="py-3 pr-4">{rowAction(row)}</td>}
              </tr>
            );
          })}
        </tbody>
      </table>

      {pagination && (
        <nav className="mt-4 flex items-center justify-between" data-testid={testId + '-pagination'} aria-label="pagination">
          <span className="text-sm text-muted-foreground" data-testid={testId + '-pagination-info'}>
            {t('pagination.page')} {pagination.page} / {pagination.totalPages || 1}
          </span>
          <div className="flex gap-2">
            <button
              type="button"
              className="border rounded px-3 py-1 disabled:opacity-50"
              onClick={() => changePage(-1)}
              disabled={pagination.page <= 1}
              data-testid={testId + '-prev'}
            >
              {t('pagination.prev')}
            </button>
            <button
              type="button"
              className="border rounded px-3 py-1 disabled:opacity-50"
              onClick={() => changePage(1)}
              disabled={pagination.page >= pagination.totalPages}
              data-testid={testId + '-next'}
            >
              {t('pagination.next')}
            </button>
          </div>
        </nav>
      )}
    </div>
  );
}
