// Generated by scaffold-dto-from-entity — DO NOT EDIT BY HAND. Re-run if entity changes.
import { PartialType } from '@nestjs/swagger';
import { CreateLessonDto } from './create-lesson.dto';

export class UpdateLessonDto extends PartialType(CreateLessonDto) {}

export type UpdateLessonRequest = UpdateLessonDto;
