/** Generated by scaffold-component-tests for app/pages/s-04-instructors.tsx */
import { describe, expect, it } from 'vitest';
import { render, screen } from '@testing-library/react';
import { MemoryRouter } from 'react-router';
import { Provider } from 'react-redux';
import { configureStore } from '@reduxjs/toolkit';
import { I18nextProvider } from 'react-i18next';
import i18n from '~/i18n';
import Page from '~/pages/s-04-instructors';

function wrap(ui: React.ReactNode) {
  const store = configureStore({ reducer: () => ({ auth: { user: null } }) });
  return (
    <Provider store={store}>
      <I18nextProvider i18n={i18n}>
        <MemoryRouter>{ui}</MemoryRouter>
      </I18nextProvider>
    </Provider>
  );
}

describe('s-04-instructors', () => {
  it('renders without crashing', () => {
    expect(() => render(wrap(<Page />))).not.toThrow();
  });

  it('renders root data-testid (s-04-instructors-page)', () => {
    render(wrap(<Page />));
    const root = screen.queryByTestId('s-04-instructors-page') ||
                 screen.queryByTestId('s-04-instructors-loading') ||
                 screen.queryByTestId('s-04-instructors-error');
    expect(root).toBeTruthy();
  });
});
