/** Generated by scaffold-crud-pages. Query hooks for LessonProgress.
 *
 * Every read is a `useQuery`, every write a `useMutation` that invalidates the
 * domain on success. Nothing here re-fetches by hand — the invalidation IS the
 * refresh, which is what keeps two screens from disagreeing about one record.
 */
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { qk } from '~/queries/keys';
import {
  fetchLessonProgressList,
  fetchLessonProgressById,
  createLessonProgress,
  updateLessonProgress,
  deleteLessonProgress,
  type FetchLessonProgressListParams,
} from '~/services/httpServices/lessonProgressService';
import type { CreateLessonProgressRequest, UpdateLessonProgressRequest } from '~/types/lesson-progress';

const DOMAIN = 'lessonProgress';

export function useLessonProgressList(params?: FetchLessonProgressListParams) {
  return useQuery({
    queryKey: qk.list(DOMAIN, params),
    queryFn: () => fetchLessonProgressList(params),
  });
}

export function useLessonProgress(id: string | undefined) {
  return useQuery({
    queryKey: qk.detail(DOMAIN, id ?? ''),
    queryFn: () => fetchLessonProgressById(id as string),
    enabled: Boolean(id),
  });
}

export function useCreateLessonProgress() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (body: CreateLessonProgressRequest) => createLessonProgress(body),
    onSuccess: () => qc.invalidateQueries({ queryKey: qk.all(DOMAIN) }),
  });
}

export function useUpdateLessonProgress() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: ({ id, body }: { id: string; body: UpdateLessonProgressRequest }) =>
      updateLessonProgress(id, body),
    onSuccess: (_data, { id }) => {
      qc.invalidateQueries({ queryKey: qk.detail(DOMAIN, id) });
      qc.invalidateQueries({ queryKey: qk.list(DOMAIN) });
    },
  });
}

export function useDeleteLessonProgress() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (id: string) => deleteLessonProgress(id),
    onSuccess: () => qc.invalidateQueries({ queryKey: qk.all(DOMAIN) }),
  });
}
