/**
 * Generated by scaffold-entities from PROJECT_DATABASE.md table `enrollments`.
 * Edits to this file are preserved across re-runs ONLY when the table
 * definition is unchanged; otherwise re-run with --force to regenerate.
 */
import { Column, Entity, Index, JoinColumn, ManyToOne } from 'typeorm';
import { BaseEntity } from '../../core/base/base.entity';
import { User } from '../user/user.entity';
import { Course } from '../course/course.entity';
import { Order } from '../order/order.entity';
import { Lesson } from '../lesson/lesson.entity';
import { enrollment_status } from '../../common/enums/enrollment-status.enum';

@Index('UQ_enrollments_user_id_course_id', ['userId', 'courseId'], { unique: true })
@Entity('enrollments')
export class Enrollment extends BaseEntity {
  @Column({ name: 'user_id', type: 'uuid' })
  userId!: string;

  @Column({ name: 'course_id', type: 'uuid' })
  courseId!: string;

  @Column({ name: 'order_id', type: 'uuid', nullable: true })
  orderId?: string;

  @Column({ type: 'int', default: 1 })
  status!: enrollment_status;

  @Column({ name: 'progress_percent', type: 'int', default: 0 })
  progressPercent!: number;

  @Column({ name: 'last_lesson_id', type: 'uuid', nullable: true })
  lastLessonId?: string;

  @Column({ name: 'enrolled_at', type: 'timestamptz' })
  enrolledAt!: Date;

  @Column({ name: 'completed_at', type: 'timestamptz', nullable: true })
  completedAt?: Date;

  // ── Relations ──

  @ManyToOne(() => User, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'user_id' })
  user?: User;

  @ManyToOne(() => Course, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'course_id' })
  course?: Course;

  @ManyToOne(() => Order, { nullable: true, onDelete: 'SET NULL' })
  @JoinColumn({ name: 'order_id' })
  order?: Order;

  @ManyToOne(() => Lesson, { nullable: true, onDelete: 'SET NULL' })
  @JoinColumn({ name: 'last_lesson_id' })
  lastLesson?: Lesson;

}
