// Generated by scaffold-dto-from-entity — DO NOT EDIT BY HAND. Re-run if entity changes.
import {
  IsOptional, IsString, IsNumber, IsBoolean, IsEnum, IsEmail, IsDateString, IsArray, IsObject,
  IsNotEmpty, MaxLength,
} from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { user_role } from '../../../common/enums/user-role.enum';
import { user_status } from '../../../common/enums/user-status.enum';

export class CreateUserDto {
  @ApiProperty()
  @IsEmail()
  email!: string;

  @ApiProperty()
  @IsString()
  passwordHash!: string;

  @ApiProperty()
  @IsString()
  // PATCH /users/me inherits this through PartialType, so an empty string was
  // a valid name: saving the profile with the field cleared answered 200 and
  // left the account with no name anywhere it is displayed.
  @IsNotEmpty()
  @MaxLength(120)
  fullName!: string;

  @ApiPropertyOptional()
  @IsOptional()
  role?: user_role;

  @ApiPropertyOptional()
  @IsOptional()
  status?: user_status;

  @ApiPropertyOptional()
  @IsOptional() @IsString()
  headline?: string;

  @ApiPropertyOptional()
  @IsOptional() @IsString()
  bio?: string;

  @ApiPropertyOptional()
  @IsOptional() @IsString()
  avatarUrl?: string;

  @ApiPropertyOptional()
  @IsOptional() @IsString()
  country?: string;

  @ApiPropertyOptional()
  @IsOptional() @IsBoolean()
  emailVerified?: boolean;

}

export type CreateUserRequest = CreateUserDto;
