/**
 * Generated by scaffold-api-client-types from backend module 'admin-console'.
 * Derived from 6 DTOs. DO NOT EDIT BY HAND —
 * re-run scaffold-api-client-types when backend DTOs change.
 */

import type { course_level } from '~/enums/course-level.enum';
import type { course_status } from '~/enums/course-status.enum';
import type { discount_type } from '~/enums/discount-type.enum';
import type { lesson_type } from '~/enums/lesson-type.enum';
import type { order_status } from '~/enums/order-status.enum';
import type { user_role } from '~/enums/user-role.enum';
import type { user_status } from '~/enums/user-status.enum';
export interface AdminCategoryQueryDto {
  search?: string;
  sort?: string;
  page?: number;
}

export type AdminCategoryQuery = AdminCategoryQueryDto;

export interface CreateAdminCategoryDto {
  name: string;
  slug: string;
  iconUrl?: string;
  description?: string;
  displayOrder?: number;
  isActive?: boolean;
}

export type CreateAdminCategory = CreateAdminCategoryDto;
export type CreateAdminCategoryRequest = CreateAdminCategoryDto;

export interface UpdateAdminCategoryDto {
  name?: string;
  slug?: string;
  iconUrl?: string;
  description?: string;
  displayOrder?: number;
  isActive?: boolean;
}

export type UpdateAdminCategory = UpdateAdminCategoryDto;
export type UpdateAdminCategoryRequest = UpdateAdminCategoryDto;

export interface AdminCouponQueryDto {
  search?: string;
  sort?: string;
  page?: number;
}

export type AdminCouponQuery = AdminCouponQueryDto;

export interface CreateAdminCouponDto {
  code: string;
  discountType: discount_type;
  discountValue: number;
  maxUses?: number;
  validFrom?: string;
  validUntil?: string;
  isActive?: boolean;
}

export type CreateAdminCoupon = CreateAdminCouponDto;
export type CreateAdminCouponRequest = CreateAdminCouponDto;

export interface UpdateAdminCouponDto {
  code?: string;
  discountType?: discount_type;
  discountValue?: number;
  maxUses?: number;
  validFrom?: string;
  validUntil?: string;
  isActive?: boolean;
}

export type UpdateAdminCoupon = UpdateAdminCouponDto;
export type UpdateAdminCouponRequest = UpdateAdminCouponDto;

export interface AdminCourseQueryDto {
  search?: string;
  category?: string;
  status?: course_status;
  sort?: string;
  page?: number;
}

export type AdminCourseQuery = AdminCourseQueryDto;

export interface CreateAdminCourseDto {
  title: string;
  slug?: string;
  summary?: string;
  description?: string;
  thumbnailUrl?: string;
  price: number;
  compareAtPrice?: number;
  level: course_level;
  language?: string;
  durationMinutes?: number;
  status: course_status;
  categoryId: string;
  instructorId: string;
}

export type CreateAdminCourse = CreateAdminCourseDto;
export type CreateAdminCourseRequest = CreateAdminCourseDto;

export interface UpdateAdminCourseDto {
  title?: string;
  slug?: string;
  summary?: string;
  description?: string;
  thumbnailUrl?: string;
  price?: number;
  compareAtPrice?: number;
  level?: course_level;
  language?: string;
  durationMinutes?: number;
  status?: course_status;
  categoryId?: string;
  instructorId?: string;
}

export type UpdateAdminCourse = UpdateAdminCourseDto;
export type UpdateAdminCourseRequest = UpdateAdminCourseDto;

export interface CreateAdminLessonDto {
  sectionId: string;
  title: string;
  contentType: lesson_type;
  videoUrl?: string;
  content?: string;
  durationMinutes?: number;
  displayOrder?: number;
  isPreview?: boolean;
  isPublished?: boolean;
}

export type CreateAdminLesson = CreateAdminLessonDto;
export type CreateAdminLessonRequest = CreateAdminLessonDto;

export interface AdminEnrollmentQueryDto {
  search?: string;
  sort?: string;
  page?: number;
}

export type AdminEnrollmentQuery = AdminEnrollmentQueryDto;

export interface AdminOrderQueryDto {
  search?: string;
  status?: order_status;
  dateFrom?: string;
  dateTo?: string;
  sort?: string;
  page?: number;
}

export type AdminOrderQuery = AdminOrderQueryDto;

export interface UpdateOrderStatusDto {
  status: order_status;
}

export type UpdateOrderStatus = UpdateOrderStatusDto;
export type UpdateOrderStatusRequest = UpdateOrderStatusDto;

export interface AdminUserQueryDto {
  search?: string;
  role?: user_role;
  status?: user_status;
  sort?: string;
  page?: number;
}

export type AdminUserQuery = AdminUserQueryDto;

export interface CreateAdminUserDto {
  fullName: string;
  email: string;
  password: string;
  role: user_role;
  status: user_status;
}

export type CreateAdminUser = CreateAdminUserDto;
export type CreateAdminUserRequest = CreateAdminUserDto;

export interface UpdateAdminUserDto {
  fullName?: string;
  email?: string;
  role?: user_role;
  status?: user_status;
}

export type UpdateAdminUser = UpdateAdminUserDto;
export type UpdateAdminUserRequest = UpdateAdminUserDto;
