/**
 * Generated by scaffold-api-client-types from backend module 'auth'.
 * Derived from 3 DTOs. DO NOT EDIT BY HAND —
 * re-run scaffold-api-client-types when backend DTOs change.
 */
export interface AuthResponseDto {
  user?: AuthUser;
  accessToken?: string;
  refreshToken?: string;
  error?: string;
  message?: string;
  data?: unknown;
}

export type AuthResponse = AuthResponseDto;
export type Auth = AuthResponseDto;

export interface LoginDto {
  email: string;
  password: string;
}

export type Login = LoginDto;
export type LoginRequest = LoginDto;

export interface SignupDto {
  fullName: string;
  email: string;
  password: string;
  role?: number;
  passwordConfirm?: string;
}

export type Signup = SignupDto;

// v93 fallback aliases (LLM-emitted pages expect these symbols)
export type LoginResponse = AuthResponseDto;
export type SignupRequest = SignupDto;

// v100: Redux state shape (preserves the template-shipped contract).
// Without these, guards/slices/pages that read state.auth.* fail TS2339.
// scaffold-frontend-contract-doctor R1: RULE-B8 — the role travels as the numeric JWT
// claim OR as the internal name from GET /api/me, so both shapes are assignable.
export type Role = 1 | 2 | 99 | number | 'admin' | 'instructor' | 'student';

export interface AuthUser {
  id: string;
  email: string;
  name?: string;
  role: Role;
  createdAt?: string;
  [k: string]: unknown;
}

export interface AuthState {
  user: AuthUser | null;
  isAuthenticated: boolean;
  isLoading: boolean;
  authChecked: boolean;
  error: string | null;
  loading?: boolean;
}
