/**
 * Generated by scaffold-api-client-types from backend module 'catalogue'.
 * Derived from 1 DTOs. DO NOT EDIT BY HAND —
 * re-run scaffold-api-client-types when backend DTOs change.
 */

import type { course_level } from '~/enums/course-level.enum';

// Unions the backend DTOs declare alongside their classes.
export type CourseSort = 'popular' | 'newest' | 'price_asc' | 'price_desc';
export interface CatalogueCategoryQueryDto {
  active?: boolean;
}

export type CatalogueCategoryQuery = CatalogueCategoryQueryDto;

export interface CatalogueCourseQueryDto {
  search?: string;
  category?: string;
  level?: course_level;
  sort?: CourseSort;
  page?: number;
}

export type CatalogueCourseQuery = CatalogueCourseQueryDto;

export interface CatalogueInstructorQueryDto {
  search?: string;
}

export type CatalogueInstructorQuery = CatalogueInstructorQueryDto;
