/**
 * Generated by scaffold-api-client-types from backend module 'dashboard'.
 * Derived from 1 DTOs. DO NOT EDIT BY HAND —
 * re-run scaffold-api-client-types when backend DTOs change.
 */
export interface DashboardWhereDto {
  field: string;
  op: string;
  value: unknown;
}

export type DashboardWhere = DashboardWhereDto;

export interface DashboardGroupDto {
  field: string;
  timestampField?: string;
  window?: { days: number };
}

export type DashboardGroup = DashboardGroupDto;

export interface DashboardQueryDto {
  entity: string;
  op: 'count';
  where?: DashboardWhereDto[];
  group?: DashboardGroupDto;
}

export type DashboardQuery = DashboardQueryDto;
