/**
 * Generated by scaffold-entities from PROJECT_DATABASE.md table `cart_items`.
 * Edits to this file are preserved across re-runs ONLY when the table
 * definition is unchanged; otherwise re-run with --force to regenerate.
 */
import { Column, Entity, Index, JoinColumn, ManyToOne } from 'typeorm';
import { BaseEntity } from '../../core/base/base.entity';
import { Cart } from '../cart/cart.entity';
import { Course } from '../course/course.entity';

@Index('UQ_cart_items_cart_id_course_id', ['cartId', 'courseId'], { unique: true })
@Entity('cart_items')
export class CartItem extends BaseEntity {
  @Column({ name: 'cart_id', type: 'uuid' })
  cartId!: string;

  @Column({ name: 'course_id', type: 'uuid' })
  courseId!: string;

  @Column({ type: 'int', default: 1 })
  quantity!: number;

  @Column({ name: 'unit_price', type: 'decimal', precision: 10, scale: 2, transformer: { to: (v: number | null) => v, from: (v: string | null) => (v === null ? null : Number(v)) } })
  unitPrice!: number;

  // ── Relations ──

  @ManyToOne(() => Cart, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'cart_id' })
  cart?: Cart;

  @ManyToOne(() => Course, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'course_id' })
  course?: Course;

}
