// Generated by scaffold-search-filter-bar — DO NOT EDIT BY HAND. Re-run to refresh.
import { useCallback, useMemo } from 'react';
import { useSearchParams } from 'react-router';

/**
 * Bind a single URL search param. Returns [value, setValue].
 * Setting to undefined / null removes the param.
 */
export function useUrlState<T extends string = string>(key: string, defaultValue?: T) {
  const [params, setParams] = useSearchParams();
  const value = useMemo<T | undefined>(() => (params.get(key) as T | null) ?? defaultValue, [params, key, defaultValue]);
  const set = useCallback((next: T | undefined | null) => {
    setParams((prev) => {
      const merged = new URLSearchParams(prev);
      if (next == null || next === '') merged.delete(key);
      else merged.set(key, String(next));
      return merged;
    });
  }, [key, setParams]);
  return [value, set] as const;
}
