/**
 * Generated by scaffold-data-table. Reusable admin-style table.
 *
 * Drop into any page with a list of records. Wires sort/pagination via
 * URL search params (RR7 useSearchParams), exposes a `columns` config
 * for fully type-safe rendering, and ships with empty/loading/error
 * states + data-testid coverage out of the box.
 *
 * Usage:
 *   <DataTable
 *     data={items}
 *     columns={[
 *       { key: 'email', label: 'Email', sortable: true },
 *       { key: 'createdAt', label: 'Created', sortable: true, format: 'date' },
 *     ]}
 *     loading={loading}
 *     error={error}
 *     pagination={pagination}
 *     testId="user-list"
 *     rowAction={(row) => <Link to={row.id}>Edit</Link>}
 *   />
 */
import { Fragment } from 'react';
import { useTranslation } from 'react-i18next';
import { Placeholder } from '~/components/shared/Placeholder';
import { useSearchParams } from 'react-router';

type Format = 'text' | 'date' | 'currency' | 'number';

export interface DataTableColumn<T> {
  key: keyof T & string;
  label: string;
  sortable?: boolean;
  format?: Format;
  render?: (row: T) => React.ReactNode;
  width?: string;
}

export interface PaginationState {
  page: number;
  limit: number;
  total: number;
  totalPages: number;
}

export interface DataTableProps<T extends Record<string, unknown>> {
  data: T[];
  columns: DataTableColumn<T>[];
  loading?: boolean;
  error?: string | null;
  pagination?: PaginationState;
  testId: string;
  rowAction?: (row: T) => React.ReactNode;
  rowKey?: (row: T) => string;
  emptyMessage?: string;
}

function defaultFormat(value: unknown, format?: Format): string {
  if (value === null || value === undefined) return '';
  if (format === 'date') {
    try { return new Date(String(value)).toLocaleString(); } catch { return String(value); }
  }
  if (format === 'currency') return new Intl.NumberFormat(undefined, { style: 'currency', currency: 'USD' }).format(Number(value));
  if (format === 'number') return new Intl.NumberFormat().format(Number(value));
  return String(value);
}

export function DataTable<T extends Record<string, unknown>>({
  data,
  columns,
  loading,
  error,
  pagination,
  testId,
  rowAction,
  rowKey,
  emptyMessage,
}: DataTableProps<T>) {
  const { t } = useTranslation('common');
  const [params, setParams] = useSearchParams();
  const sortParam = params.get('sort') ?? '';

  function toggleSort(field: string) {
    const next = new URLSearchParams(params);
    if (sortParam === field) next.set('sort', '-' + field);
    else if (sortParam === '-' + field) next.delete('sort');
    else next.set('sort', field);
    next.delete('page');
    setParams(next);
  }

  function changePage(delta: number) {
    if (!pagination) return;
    const next = new URLSearchParams(params);
    const newPage = Math.max(1, pagination.page + delta);
    next.set('page', String(newPage));
    setParams(next);
  }

  if (loading && data.length === 0) {
    // Rows the shape of the rows that are coming, not the word "Loading...".
    return (
      <div className="space-y-2 p-4" data-testid={testId + '-loading'} aria-busy="true">
        <span className="sr-only">{t('actions.loading')}</span>
        {Array.from({ length: 6 }).map((_, i) => (
          <div key={i} className="et-shimmer h-[44px] rounded-[var(--radius-md)]" />
        ))}
      </div>
    );
  }
  if (error) {
    return <Placeholder tone="error" testId={testId + '-error'} title={error} />;
  }

  if (data.length === 0) {
    return (
      <Placeholder
        testId={testId + '-empty'}
        title={emptyMessage ?? t('empty.title')}
        hint={t('empty.description', { defaultValue: '' }) || undefined}
      />
    );
  }

  return (
    <div data-testid={testId}>
      {/* A table cannot be made to fit 390px without either hiding columns or
          squeezing them to nothing. Below `md` each row becomes a card of
          label/value pairs — every column still readable, nothing truncated —
          and the table returns at tablet width. Six admin screens scrolled
          sideways to ~690px in a 390px viewport before this. */}
      <div className="hidden overflow-x-auto md:block">
        <table className="w-full border-collapse" data-testid={testId + '-table'}>
          <thead>
          <tr className="border-b text-left text-sm text-muted-foreground">
            {columns.map((col) => (
              <th
                key={col.key}
                className={
                  'whitespace-nowrap px-3 py-[10px] first:rounded-l-[var(--radius-md)] last:rounded-r-[var(--radius-md)]' +
                  (col.sortable ? ' cursor-pointer select-none transition-colors hover:text-[var(--c-primary-text)]' : '')
                }
                onClick={col.sortable ? () => toggleSort(col.key) : undefined}
                data-testid={testId + '-th-' + col.key}
                style={col.width ? { width: col.width } : undefined}
              >
                {col.label}
                {col.sortable && (
                  <span>
                    {sortParam === col.key ? ' ↑' : sortParam === '-' + col.key ? ' ↓' : ''}
                  </span>
                )}
              </th>
            ))}
            {rowAction && <th className="whitespace-nowrap px-3 py-[10px] text-right" data-testid={testId + '-th-actions'}>{t('actions.actions') ?? 'Actions'}</th>}
          </tr>
          </thead>
          <tbody>
          {data.map((row, idx) => {
            const k = rowKey ? rowKey(row) : String((row as Record<string, unknown>).id ?? idx);
            return (
              <tr
                key={k}
                className="border-b border-[var(--c-hairline)] transition-colors last:border-b-0 hover:bg-[var(--c-surface-soft)]"
                data-testid={testId + '-row-' + k}
              >
                {columns.map((col) => (
                  <td
                    key={col.key}
                    className={
                      'px-3 py-[14px] align-middle text-[14px] text-[var(--c-ink)]' +
                      (col.format === 'currency' || col.format === 'number' ? ' tabular-nums' : '')
                    }
                    data-testid={testId + '-cell-' + k + '-' + col.key}
                  >
                    {col.render ? col.render(row) : defaultFormat(row[col.key], col.format)}
                  </td>
                ))}
                {rowAction && <td className="px-3 py-[14px] text-right">{rowAction(row)}</td>}
              </tr>
            );
          })}
          </tbody>
        </table>
      </div>

      <ul className="m-0 flex list-none flex-col gap-[10px] p-0 md:hidden" data-testid={testId + '-cards'}>
        {data.map((row, idx) => {
          const k = rowKey ? rowKey(row) : String((row as Record<string, unknown>).id ?? idx);
          return (
            <li
              key={k}
              className="et-lift rounded-[var(--radius-lg)] border border-[var(--c-hairline)] bg-[var(--c-surface)] p-[14px] shadow-[var(--shadow-0)]"
              data-testid={testId + '-card-' + k}
            >
              <dl className="m-0 grid grid-cols-[minmax(0,9rem)_1fr] gap-x-[12px] gap-y-[6px]">
                {columns.map((col) => (
                  <Fragment key={col.key}>
                    <dt className="m-0 text-[12px] font-medium uppercase tracking-[0.4px] text-[var(--c-muted)]">
                      {col.label}
                    </dt>
                    <dd className="m-0 min-w-0 break-words text-[14px] text-[var(--c-ink)]">
                      {col.render ? col.render(row) : defaultFormat(row[col.key], col.format)}
                    </dd>
                  </Fragment>
                ))}
              </dl>
              {rowAction && (
                <div className="mt-[12px] flex flex-wrap gap-[8px] border-t border-[var(--c-hairline)] pt-[12px]">
                  {rowAction(row)}
                </div>
              )}
            </li>
          );
        })}
      </ul>

      {pagination && (
        <nav className="mt-4 flex flex-wrap items-center justify-between gap-3" data-testid={testId + '-pagination'} aria-label="pagination">
          <span className="text-sm text-muted-foreground" data-testid={testId + '-pagination-info'}>
            {t('pagination.page')} {pagination.page} / {pagination.totalPages || 1}
          </span>
          <div className="flex gap-2">
            <button
              type="button"
              className="et-press min-h-[40px] rounded-[var(--radius-md)] border border-[var(--c-hairline-strong)] px-4 text-sm font-medium transition-colors hover:bg-[var(--c-surface-soft)] disabled:cursor-not-allowed disabled:opacity-50"
              onClick={() => changePage(-1)}
              disabled={pagination.page <= 1}
              data-testid={testId + '-prev'}
            >
              {t('pagination.prev')}
            </button>
            <button
              type="button"
              className="et-press min-h-[40px] rounded-[var(--radius-md)] border border-[var(--c-hairline-strong)] px-4 text-sm font-medium transition-colors hover:bg-[var(--c-surface-soft)] disabled:cursor-not-allowed disabled:opacity-50"
              onClick={() => changePage(1)}
              disabled={pagination.page >= pagination.totalPages}
              data-testid={testId + '-next'}
            >
              {t('pagination.next')}
            </button>
          </div>
        </nav>
      )}
    </div>
  );
}
