/**
 * Generated by scaffold-api-client-types from backend module 'cart-item'.
 * Derived from 3 DTOs. DO NOT EDIT BY HAND —
 * re-run scaffold-api-client-types when backend DTOs change.
 */
export interface CartItemResponseDto {
  id: string;
  cartId: string;
  courseId: string;
  quantity?: number;
  unitPrice: number;
  createdAt: string;
  updatedAt: string;
}

export type CartItemResponse = CartItemResponseDto;
export type CartItem = CartItemResponseDto;

export interface CreateCartItemDto {
  cartId: string;
  courseId: string;
  quantity?: number;
  unitPrice: number;
}

export type CreateCartItem = CreateCartItemDto;
export type CreateCartItemRequest = CreateCartItemDto;

// v93 fallback aliases (LLM-emitted pages expect these symbols)
export type UpdateCartItem = Partial<CreateCartItemDto>;
export type UpdateCartItemRequest = Partial<CreateCartItemDto>;
