/**
 * Generated by scaffold-api-client-types from backend module 'user'.
 * Derived from 3 DTOs. DO NOT EDIT BY HAND —
 * re-run scaffold-api-client-types when backend DTOs change.
 */

import type { user_role } from '~/enums/user-role.enum';
import type { user_status } from '~/enums/user-status.enum';
export interface CreateUserDto {
  email: string;
  passwordHash: string;
  fullName: string;
  role?: user_role;
  status?: user_status;
  headline?: string;
  bio?: string;
  avatarUrl?: string;
  country?: string;
  emailVerified?: boolean;
}

export type CreateUser = CreateUserDto;
export type CreateUserRequest = CreateUserDto;

export interface UserResponseDto {
  id: string;
  email: string;
  fullName: string;
  role?: user_role;
  status?: user_status;
  headline?: string;
  bio?: string;
  avatarUrl?: string;
  country?: string;
  emailVerified?: boolean;
  createdAt: string;
  updatedAt: string;
}

export type UserResponse = UserResponseDto;
export type User = UserResponseDto;

// v93 fallback aliases (LLM-emitted pages expect these symbols)
export type UpdateUser = Partial<CreateUserDto>;
export type UpdateUserRequest = Partial<CreateUserDto>;
