// Generated by scaffold-service-from-controller — DO NOT EDIT BY HAND. Re-run when backend controllers change.
import { createAsyncThunk } from '@reduxjs/toolkit';
import { get } from '~/services/httpMethods/get';
import { post } from '~/services/httpMethods/post';
import { put } from '~/services/httpMethods/put';
import { patch } from '~/services/httpMethods/patch';
import { del } from '~/services/httpMethods/del';
import type * as CategoryTypes from '~/types/category';

function __cleanQuery(q?: Record<string, unknown>): Record<string, unknown> | undefined {
  if (!q || typeof q !== 'object') return undefined;
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(q)) {
    const t = typeof v;
    if (v != null && (t === 'string' || t === 'number' || t === 'boolean')) out[k] = v;
  }
  return Object.keys(out).length ? out : undefined;
}

export const list = createAsyncThunk(
  'category/list',
  async (query?: Record<string, unknown>) => {
    const res = await get('/admin/categories', { params: __cleanQuery(query) });
    return res;
  },
);

export const detail = createAsyncThunk(
  'category/detail',
  async (id: string, query?: Record<string, unknown>) => {
    const res = await get(`/admin/categories/${id}`, { params: __cleanQuery(query) });
    return res;
  },
);

// v103: aliases for naming conventions LLM-emitted pages tend to use.
// No runtime cost — same function reference re-exported under a verb-prefixed name.
export const fetchDetail = detail;

// v152: entity-canonical CRUD surface — the contract scaffold-crud-pages
// imports for every entity. Synthesized (not aliased) so ids and generated
// request INTERFACES stay assignable. See emitCanonicalCrudSurface().
export const fetchAdminCategoriesList = createAsyncThunk(
  'adminCategories/fetchAdminCategoriesList',
  async (params?: Record<string, unknown>) => {
    const res = await get<unknown>('/admin/categories', { params: __cleanQuery(params) });
    return res;
  },
);

export const fetchAdminCategoriesById = createAsyncThunk(
  'adminCategories/fetchAdminCategoriesById',
  async (id: string) => {
    const res = await get<unknown>(`/admin/categories/${id}`);
    return res;
  },
);

export async function createAdminCategories(data: unknown): Promise<unknown> {
  const res = await post<unknown>('/admin/categories', data as Record<string, unknown>);
  return res;
}

export async function updateAdminCategories(id: string, data: unknown): Promise<unknown> {
  const res = await patch<unknown>(`/admin/categories/${id}`, data as Record<string, unknown>);
  return res;
}

export async function deleteAdminCategories(id: string): Promise<void> {
  await del<void>(`/admin/categories/${id}`);
}
