// Generated by scaffold-service-from-controller — DO NOT EDIT BY HAND. Re-run when backend controllers change.
import { createAsyncThunk } from '@reduxjs/toolkit';
import { get } from '~/services/httpMethods/get';
import { post } from '~/services/httpMethods/post';
import { put } from '~/services/httpMethods/put';
import { patch } from '~/services/httpMethods/patch';
import { del } from '~/services/httpMethods/del';
import type * as AdminConsoleTypes from '~/types/admin-console';

function __cleanQuery(q?: Record<string, unknown>): Record<string, unknown> | undefined {
  if (!q || typeof q !== 'object') return undefined;
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(q)) {
    const t = typeof v;
    if (v != null && (t === 'string' || t === 'number' || t === 'boolean')) out[k] = v;
  }
  return Object.keys(out).length ? out : undefined;
}

export const getStats = createAsyncThunk(
  'adminConsole/getStats',
  async (query?: Record<string, unknown>) => {
    const res = await get('/admin/stats', { params: __cleanQuery(query) });
    return res;
  },
);

export const listCourses = createAsyncThunk(
  'adminConsole/listCourses',
  async (query?: Record<string, unknown>) => {
    const res = await get('/admin/courses', { params: __cleanQuery(query) });
    return res;
  },
);

export const getCourse = createAsyncThunk(
  'adminConsole/getCourse',
  async (id: string, query?: Record<string, unknown>) => {
    const res = await get(`/admin/courses/${id}`, { params: __cleanQuery(query) });
    return res;
  },
);

export async function createCourse(data: Record<string, unknown>): Promise<unknown> {
  const res = await post(`/admin/courses`, data);
  return res;
}

export async function updateCourse(id: string, data: Record<string, unknown>): Promise<unknown> {
  const res = await patch(`/admin/courses/${id}`, data);
  return res;
}

export async function deleteCourse(id: string): Promise<unknown> {
  const res = await del(`/admin/courses/${id}`);
  return res;
}

export async function addLesson(id: string, data: Record<string, unknown>): Promise<unknown> {
  const res = await post(`/admin/courses/${id}/lessons`, data);
  return res;
}

export async function deleteLesson(id: string): Promise<unknown> {
  const res = await del(`/admin/lessons/${id}`);
  return res;
}

export const listCategories = createAsyncThunk(
  'adminConsole/listCategories',
  async (query?: Record<string, unknown>) => {
    const res = await get('/admin/categories', { params: __cleanQuery(query) });
    return res;
  },
);

export async function createCategory(data: Record<string, unknown>): Promise<unknown> {
  const res = await post(`/admin/categories`, data);
  return res;
}

export async function updateCategory(id: string, data: Record<string, unknown>): Promise<unknown> {
  const res = await patch(`/admin/categories/${id}`, data);
  return res;
}

export async function deleteCategory(id: string): Promise<unknown> {
  const res = await del(`/admin/categories/${id}`);
  return res;
}

export const listUsers = createAsyncThunk(
  'adminConsole/listUsers',
  async (query?: Record<string, unknown>) => {
    const res = await get('/admin/users', { params: __cleanQuery(query) });
    return res;
  },
);

export async function createUser(data: Record<string, unknown>): Promise<unknown> {
  const res = await post(`/admin/users`, data);
  return res;
}

export async function updateUser(id: string, data: Record<string, unknown>): Promise<unknown> {
  const res = await patch(`/admin/users/${id}`, data);
  return res;
}

export const listOrders = createAsyncThunk(
  'adminConsole/listOrders',
  async (query?: Record<string, unknown>) => {
    const res = await get('/admin/orders', { params: __cleanQuery(query) });
    return res;
  },
);

export const getOrder = createAsyncThunk(
  'adminConsole/getOrder',
  async (id: string, query?: Record<string, unknown>) => {
    const res = await get(`/admin/orders/${id}`, { params: __cleanQuery(query) });
    return res;
  },
);

export async function updateOrder(id: string, data: Record<string, unknown>): Promise<unknown> {
  const res = await patch(`/admin/orders/${id}`, data);
  return res;
}

export async function refundOrder(id: string, data: Record<string, unknown>): Promise<unknown> {
  const res = await post(`/admin/orders/${id}/refund`, data);
  return res;
}

export const listEnrollments = createAsyncThunk(
  'adminConsole/listEnrollments',
  async (query?: Record<string, unknown>) => {
    const res = await get('/admin/enrollments', { params: __cleanQuery(query) });
    return res;
  },
);

export const listCoupons = createAsyncThunk(
  'adminConsole/listCoupons',
  async (query?: Record<string, unknown>) => {
    const res = await get('/admin/coupons', { params: __cleanQuery(query) });
    return res;
  },
);

export async function createCoupon(data: Record<string, unknown>): Promise<unknown> {
  const res = await post(`/admin/coupons`, data);
  return res;
}

export async function updateCoupon(id: string, data: Record<string, unknown>): Promise<unknown> {
  const res = await patch(`/admin/coupons/${id}`, data);
  return res;
}

export async function deleteCoupon(id: string): Promise<unknown> {
  const res = await del(`/admin/coupons/${id}`);
  return res;
}

// v103: aliases for naming conventions LLM-emitted pages tend to use.
// No runtime cost — same function reference re-exported under a verb-prefixed name.
export const fetchGetStats = getStats;
export const fetchGetCourse = getCourse;
export const createAddLesson = addLesson;
export const fetchGetOrder = getOrder;
export const createRefundOrder = refundOrder;

// v152: entity-canonical CRUD surface — the contract scaffold-crud-pages
// imports for every entity. Synthesized (not aliased) so ids and generated
// request INTERFACES stay assignable. See emitCanonicalCrudSurface().
export const fetchAdminConsoleList = createAsyncThunk(
  'adminConsole/fetchAdminConsoleList',
  async (params?: Record<string, unknown>) => {
    const res = await get<unknown>('/admin/stats', { params: __cleanQuery(params) });
    return res;
  },
);

export const fetchAdminConsoleById = createAsyncThunk(
  'adminConsole/fetchAdminConsoleById',
  async (id: string) => {
    const res = await get<unknown>(`/admin/courses/${id}`);
    return res;
  },
);

export async function createAdminConsole(data: unknown): Promise<unknown> {
  const res = await post<unknown>('/admin', data as Record<string, unknown>);
  return res;
}

export async function updateAdminConsole(id: string, data: unknown): Promise<unknown> {
  const res = await patch<unknown>(`/admin/${id}`, data as Record<string, unknown>);
  return res;
}

export async function deleteAdminConsole(id: string): Promise<void> {
  await del<void>(`/admin/${id}`);
}
