// Generated by scaffold-service-from-controller — DO NOT EDIT BY HAND. Re-run when backend controllers change.
import { createAsyncThunk } from '@reduxjs/toolkit';
import { get } from '~/services/httpMethods/get';
import { post } from '~/services/httpMethods/post';
import { put } from '~/services/httpMethods/put';
import { patch } from '~/services/httpMethods/patch';
import { del } from '~/services/httpMethods/del';
import type {
  CreateCartRequest,
  UpdateCartRequest,
  CartResponse,
} from '~/types/cart';

function __cleanQuery(q?: Record<string, unknown>): Record<string, unknown> | undefined {
  if (!q || typeof q !== 'object') return undefined;
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(q)) {
    const t = typeof v;
    if (v != null && (t === 'string' || t === 'number' || t === 'boolean')) out[k] = v;
  }
  return Object.keys(out).length ? out : undefined;
}

export const fetchCarts = createAsyncThunk(
  'cart/fetchAll',
  async (params?: Record<string, unknown>) => {
    const res = await get<{ items: CartResponse[]; total: number; page: number; limit: number; totalPages: number }>('/carts', { params: __cleanQuery(params) });
    return res;
  },
);

export const fetchCartById = createAsyncThunk(
  'cart/fetchById',
  async (id: string) => {
    const res = await get<CartResponse>(`/carts/${id}`);
    return res;
  },
);

export async function createCart(data: CreateCartRequest): Promise<CartResponse> {
  const res = await post<CartResponse>('/carts', data);
  return res;
}

export async function updateCart(id: string, data: UpdateCartRequest): Promise<CartResponse> {
  const res = await patch<CartResponse>(`/carts/${id}`, data);
  return res;
}

export async function deleteCart(id: string): Promise<void> {
  await del<void>(`/carts/${id}`);
}

// LLM-friendly aliases — same thunk under common alternate names.
export const fetchCartList = fetchCarts;
export const fetchCart = fetchCartById;
export const removeCart = deleteCart;

// v118/v120 scaffold-frontend-contract-doctor R4 — stub exports for page/slice-
// imported symbols this service never defined (crud-page ↔ service-from-controller
// name drift). Thunk-used names (referenced as .fulfilled/.pending/.rejected in a
// slice) MUST be createAsyncThunk or addCase crashes SSR; others are any plain fns.
export type FetchCartListParams = Record<string, unknown>;
