// Generated by scaffold-service-from-controller — DO NOT EDIT BY HAND. Re-run when backend controllers change.
import { createAsyncThunk } from '@reduxjs/toolkit';
import { get } from '~/services/httpMethods/get';
import { post } from '~/services/httpMethods/post';
import { put } from '~/services/httpMethods/put';
import { patch } from '~/services/httpMethods/patch';
import { del } from '~/services/httpMethods/del';
import type * as EnrollmentTypes from '~/types/enrollment';
import type { EnrollmentResponse } from '~/types/enrollment';

function __cleanQuery(q?: Record<string, unknown>): Record<string, unknown> | undefined {
  if (!q || typeof q !== 'object') return undefined;
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(q)) {
    const t = typeof v;
    if (v != null && (t === 'string' || t === 'number' || t === 'boolean')) out[k] = v;
  }
  return Object.keys(out).length ? out : undefined;
}

export const findAll = createAsyncThunk(
  'enrollment/findAll',
  async (query?: Record<string, unknown>) => {
    const res = await get('/enrollments', { params: __cleanQuery(query) });
    return res;
  },
);

export const findOne = createAsyncThunk(
  'enrollment/findOne',
  async (id: string, query?: Record<string, unknown>) => {
    const res = await get(`/enrollments/${id}`, { params: __cleanQuery(query) });
    return res;
  },
);

export async function completeLesson(id: string, lessonId: string, data: Record<string, unknown>): Promise<unknown> {
  const res = await post(`/enrollments/${id}/lessons/${lessonId}/complete`, data);
  return res;
}

// v103: aliases for naming conventions LLM-emitted pages tend to use.
// No runtime cost — same function reference re-exported under a verb-prefixed name.
export const fetchFindAll = findAll;
export const fetchFindOne = findOne;
export const createCompleteLesson = completeLesson;

// v152: entity-canonical CRUD surface — the contract scaffold-crud-pages
// imports for every entity. Synthesized (not aliased) so ids and generated
// request INTERFACES stay assignable. See emitCanonicalCrudSurface().
export const fetchEnrollmentList = createAsyncThunk(
  'enrollment/fetchEnrollmentList',
  async (params?: Record<string, unknown>) => {
    const res = await get<{ items: EnrollmentResponse[]; total: number; page: number; limit: number; totalPages: number }>('/enrollments', { params: __cleanQuery(params) });
    return res;
  },
);

export const fetchEnrollmentById = createAsyncThunk(
  'enrollment/fetchEnrollmentById',
  async (id: string) => {
    const res = await get<EnrollmentResponse>(`/enrollments/${id}`);
    return res;
  },
);

export async function createEnrollment(data: unknown): Promise<EnrollmentResponse> {
  const res = await post<EnrollmentResponse>('/enrollments', data as Record<string, unknown>);
  return res;
}

export async function updateEnrollment(id: string, data: unknown): Promise<EnrollmentResponse> {
  const res = await patch<EnrollmentResponse>(`/enrollments/${id}`, data as Record<string, unknown>);
  return res;
}

export async function deleteEnrollment(id: string): Promise<void> {
  await del<void>(`/enrollments/${id}`);
}

// v118/v120 scaffold-frontend-contract-doctor R4 — stub exports for page/slice-
// imported symbols this service never defined (crud-page ↔ service-from-controller
// name drift). Thunk-used names (referenced as .fulfilled/.pending/.rejected in a
// slice) MUST be createAsyncThunk or addCase crashes SSR; others are any plain fns.
export type FetchEnrollmentListParams = Record<string, unknown>;
