// Generated by scaffold-service-from-controller — DO NOT EDIT BY HAND. Re-run when backend controllers change.
import { createAsyncThunk } from '@reduxjs/toolkit';
import { get } from '~/services/httpMethods/get';
import { post } from '~/services/httpMethods/post';
import { put } from '~/services/httpMethods/put';
import { patch } from '~/services/httpMethods/patch';
import { del } from '~/services/httpMethods/del';
import type {
  CreateLessonRequest,
  UpdateLessonRequest,
  LessonResponse,
} from '~/types/lesson';

function __cleanQuery(q?: Record<string, unknown>): Record<string, unknown> | undefined {
  if (!q || typeof q !== 'object') return undefined;
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(q)) {
    const t = typeof v;
    if (v != null && (t === 'string' || t === 'number' || t === 'boolean')) out[k] = v;
  }
  return Object.keys(out).length ? out : undefined;
}

export const fetchLessons = createAsyncThunk(
  'lesson/fetchAll',
  async (params?: Record<string, unknown>) => {
    const res = await get<{ items: LessonResponse[]; total: number; page: number; limit: number; totalPages: number }>('/lessons', { params: __cleanQuery(params) });
    return res;
  },
);

export const fetchLessonById = createAsyncThunk(
  'lesson/fetchById',
  async (id: string) => {
    const res = await get<LessonResponse>(`/lessons/${id}`);
    return res;
  },
);

export async function createLesson(data: CreateLessonRequest): Promise<LessonResponse> {
  const res = await post<LessonResponse>('/lessons', data);
  return res;
}

export async function updateLesson(id: string, data: UpdateLessonRequest): Promise<LessonResponse> {
  const res = await patch<LessonResponse>(`/lessons/${id}`, data);
  return res;
}

export async function deleteLesson(id: string): Promise<void> {
  await del<void>(`/lessons/${id}`);
}

// LLM-friendly aliases — same thunk under common alternate names.
export const fetchLessonList = fetchLessons;
export const fetchLesson = fetchLessonById;
export const removeLesson = deleteLesson;

// v118/v120 scaffold-frontend-contract-doctor R4 — stub exports for page/slice-
// imported symbols this service never defined (crud-page ↔ service-from-controller
// name drift). Thunk-used names (referenced as .fulfilled/.pending/.rejected in a
// slice) MUST be createAsyncThunk or addCase crashes SSR; others are any plain fns.
export type FetchLessonListParams = Record<string, unknown>;
