// Generated by scaffold-email
// @Global so auth / otp / notification can inject MailService without importing MailModule.
// OTP_MAILER (useExisting: MailService) lets the OTP module @Optional-inject an email
// deliverer with no compile-time dependency on this module (parity with sms's OTP_SMS).
import { Global, Module } from '@nestjs/common';
import { MailClient } from './mail.client';
import { MailService } from './mail.service';

@Global()
@Module({
  providers: [MailClient, MailService, { provide: 'OTP_MAILER', useExisting: MailService }],
  exports: [MailService, 'OTP_MAILER'],
})
export class MailModule {}
