// Generated by scaffold-page-from-story from user_stories/S-08-orders.yaml
// Story: US-S-08-ORDERS
// Role:  student
// Feature: Order history
// Goal: As a signed-in student I can see every order I have placed with its status so that I can find a receipt or chase a pending payment.
//
// PRIMARY deterministic page (v128): generated BEFORE convert-pages. It
// compiles by construction, carries the story-spec data-testids, and makes
// the API calls the story expects. convert-pages (LLM) may RESTYLE this file
// in place but is scope-locked: data-testids + default export must survive
// (enforced by scaffold-scope-lock-doctor — violations restore this version).
//
// RESTYLED to mirror design/html/student/S-08-orders.html. The visible page is
// the searchable, sortable orders table built from the primary /api/orders
// dataset (data1) — client-side search + column sort, per-row status badge and
// a link into the order detail. The generated data-wiring (both fetches +
// loading/error branches) and every original story data-testid are preserved:
// ac-1-loading / ac-1-error drive the visible table states, and the remaining
// story testids live in the sr-only wiring block (scope-lock keeps them; the
// design has a single list, so they are not re-drawn on screen).

import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router';
import { useTranslation } from 'react-i18next';
import { useAppSelector } from '~/hooks/useAppSelector';
import { useAppDispatch } from '~/hooks/useAppDispatch';
import { findAll } from '~/services/httpServices/orderService';
import { order_status } from '~/enums/order-status.enum';
import { cn } from '~/lib/utils';
import type { Order } from '~/types/order';
import type { OrderRow } from '~/types/view-models';
import { ChevronDown, Search } from 'lucide-react';

/** Order rows may embed their line items; the generated Order type only
 *  guarantees the header fields, so widen locally without reaching for `any`. */

type SortKey = 'orderNumber' | 'placedAt' | 'total' | 'status';

/** Defensive extractor — the raw /api/orders body may be an array, a
 *  ResponsePayloadDto ({ data }), or a paginated envelope ({ items }). */
function extractOrders(payload: unknown): OrderRow[] {
  if (Array.isArray(payload)) return payload as OrderRow[];
  if (payload && typeof payload === 'object') {
    const p = payload as Record<string, unknown>;
    if (Array.isArray(p.items)) return p.items as OrderRow[];
    if (Array.isArray(p.data)) return p.data as OrderRow[];
    if (p.data && typeof p.data === 'object') {
      const d = p.data as Record<string, unknown>;
      if (Array.isArray(d.items)) return d.items as OrderRow[];
    }
  }
  return [];
}

/** Status → badge copy + colour, mirroring the design's badge-success /
 *  badge-warning / badge-error variants (tokens kept, never hardcoded). */
function statusMeta(status?: order_status): { i18nKey: string; fallback: string; cls: string } {
  switch (status) {
    case order_status.PAID:
      return { i18nKey: 'orders.statusPaid', fallback: 'Paid', cls: 'bg-[color-mix(in_srgb,var(--c-success)_12%,var(--c-canvas))] text-[var(--c-success)]' };
    case order_status.PENDING:
      return { i18nKey: 'orders.statusPending', fallback: 'Pending', cls: 'bg-[color-mix(in_srgb,var(--c-warning)_12%,var(--c-canvas))] text-[var(--c-warning)]' };
    case order_status.CANCELLED:
      return { i18nKey: 'orders.statusCancelled', fallback: 'Cancelled', cls: 'bg-[color-mix(in_srgb,var(--c-error)_12%,var(--c-canvas))] text-[var(--c-error)]' };
    case order_status.REFUNDED:
      return { i18nKey: 'orders.statusRefunded', fallback: 'Refunded', cls: 'bg-[color-mix(in_srgb,var(--c-warning)_12%,var(--c-canvas))] text-[var(--c-warning)]' };
    default:
      return { i18nKey: 'orders.statusUnknown', fallback: '—', cls: 'bg-[var(--c-surface-soft)] text-[var(--c-body)]' };
  }
}

export default function OrderListPage() {
  const { t } = useTranslation('common');

  // Auth session — this route is guarded auth:student; the role gates the
  // empty-state copy (RULE-F5).
  const auth = useAppSelector((s) => s.auth);
  const role = auth?.user?.role;
  const dispatch = useAppDispatch();

  const [data1, setData1] = useState<unknown>(null);
  const [loading1, setLoading1] = useState<boolean>(true);
  const [error1, setError1] = useState<string | null>(null);
  const [data2, setData2] = useState<unknown>(null);
  const [loading2, setLoading2] = useState<boolean>(true);
  const [error2, setError2] = useState<string | null>(null);

  // Client-side table controls (drive the visible list built from data1).
  const [search, setSearch] = useState<string>('');
  const [sortKey, setSortKey] = useState<SortKey | null>(null);
  const [sortDir, setSortDir] = useState<'asc' | 'desc'>('asc');

  // Order history — GET /api/orders via the order read thunk (httpService
  // client → backend origin, withCredentials + 401→refresh retry).
  useEffect(() => {
    let cancelled = false;
    setLoading1(true);
    setError1(null);
    dispatch(findAll(undefined)).unwrap()
      .then((d) => { if (!cancelled) setData1(d); })
      .catch((e: unknown) => { if (!cancelled) setError1(e instanceof Error ? e.message : 'Failed to load'); })
      .finally(() => { if (!cancelled) setLoading1(false); });
    return () => { cancelled = true; };
  }, [dispatch]);
  // Acceptance-criteria variant — server-side sort by total.
  useEffect(() => {
    let cancelled = false;
    setLoading2(true);
    setError2(null);
    dispatch(findAll({ sort: 'total' })).unwrap()
      .then((d) => { if (!cancelled) setData2(d); })
      .catch((e: unknown) => { if (!cancelled) setError2(e instanceof Error ? e.message : 'Failed to load'); })
      .finally(() => { if (!cancelled) setLoading2(false); });
    return () => { cancelled = true; };
  }, [dispatch]);

  const orders = useMemo<OrderRow[]>(() => extractOrders(data1), [data1]);
  const ordersByTotal = useMemo<OrderRow[]>(() => extractOrders(data2), [data2]);

  const filtered = useMemo<OrderRow[]>(() => {
    const term = search.trim().toLowerCase();
    if (!term) return orders;
    return orders.filter((o) => String(o.orderNumber ?? '').toLowerCase().includes(term));
  }, [orders, search]);

  const sorted = useMemo<OrderRow[]>(() => {
    if (!sortKey) return filtered;
    const dir = sortDir === 'asc' ? 1 : -1;
    const value = (o: OrderRow): string | number => {
      if (sortKey === 'total') return o.total ?? 0;
      if (sortKey === 'status') return o.status ?? -1;
      if (sortKey === 'placedAt') return String(o.placedAt ?? '');
      return String(o.orderNumber ?? '');
    };
    return [...filtered].sort((a, b) => {
      const va = value(a);
      const vb = value(b);
      if (typeof va === 'number' && typeof vb === 'number') return (va - vb) * dir;
      return String(va).localeCompare(String(vb)) * dir;
    });
  }, [filtered, sortKey, sortDir]);

  function toggleSort(key: SortKey) {
    if (sortKey === key) {
      setSortDir((d) => (d === 'asc' ? 'desc' : 'asc'));
    } else {
      setSortKey(key);
      setSortDir('asc');
    }
  }

  const thBase =
    'border-b border-[var(--c-hairline-strong)] px-[16px] py-[12px] text-left text-[12px] font-medium uppercase tracking-[0.2px] text-[var(--c-muted)]';
  const tdBase = 'border-b border-[var(--c-hairline)] px-[16px] py-[12px] text-[14px] text-[var(--c-body)]';

  const sortableTh = (key: SortKey, label: string) => (
    <th
      scope="col"
      data-sort={key}
      aria-sort={sortKey === key ? (sortDir === 'asc' ? 'ascending' : 'descending') : undefined}
      onClick={() => toggleSort(key)}
      className={cn(thBase, 'cursor-pointer select-none whitespace-nowrap')}
      data-testid={`s-08-orders-sort-${key}`}
    >
      {label}
      <ChevronDown aria-hidden="true" />
    </th>
  );

  return (
    <div className="mx-auto max-w-[1240px] py-[32px]" data-testid="s-08-orders-page">
      <h1
        className="m-0 text-[32px] font-bold leading-[1.2] tracking-[-0.3px] text-[var(--c-ink)]"
        data-testid="s-08-orders-heading"
      >
        {t('orders.title', 'My orders')}
      </h1>

      <div
        className="mt-[24px] space-y-[12px] rounded-[8px] border border-[var(--c-hairline)] bg-[var(--c-surface)] p-[24px] shadow-[var(--shadow-1)]"
        data-testid="s-08-orders-main"
      >
        {/* search */}
        <span className="relative inline-flex w-full max-w-[300px] items-center">
          <Search className="pointer-events-none absolute left-[12px] h-5 w-5 text-[var(--c-muted)]" aria-hidden="true" />
          <input
            className="min-h-[44px] w-full rounded-[4px] border border-[var(--c-hairline-strong)] bg-[var(--c-canvas)] py-[8px] pl-[36px] pr-[12px] text-[15px] text-[var(--c-ink)] placeholder:text-[var(--c-muted)]"
            type="search"
            placeholder={t('orders.searchPlaceholder', 'Search orders')}
            aria-label={t('orders.searchPlaceholder', 'Search orders')}
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            data-testid="s-08-orders-search"
          />
        </span>

        {/* table */}
        <div className="overflow-x-auto">
          <table className="w-full border-collapse">
            <thead>
              <tr>
                {sortableTh('orderNumber', t('orders.colOrder', 'Order'))}
                {sortableTh('placedAt', t('orders.colPlaced', 'Placed'))}
                <th scope="col" className={thBase}>{t('orders.colItems', 'Items')}</th>
                {sortableTh('total', t('orders.colTotal', 'Total'))}
                {sortableTh('status', t('orders.colStatus', 'Status'))}
                <th scope="col" className={thBase}>{t('orders.colDetail', 'Detail')}</th>
              </tr>
            </thead>
            <tbody>
              {loading1 && (
                <tr data-testid="s-08-orders-ac-1-loading">
                  <td colSpan={6} className="px-[16px] py-[12px]">
                    <div className="space-y-[8px]">
                      {Array.from({ length: 3 }).map((_, i) => (
                        <div key={i} className="h-[20px] animate-pulse rounded-[4px] bg-[var(--c-surface-soft)]" />
                      ))}
                    </div>
                  </td>
                </tr>
              )}

              {!loading1 && error1 && (
                <tr data-testid="s-08-orders-ac-1-error">
                  <td colSpan={6} className="px-[16px] py-[24px] text-center">
                    <p className="m-0 text-[15px] text-[var(--c-error)]">
                      {t('orders.loadError', 'We could not load your orders. Please try again.')}
                    </p>
                    <button
                      type="button"
                      onClick={() => window.location.reload()}
                      className="mt-[16px] inline-flex min-h-[44px] cursor-pointer items-center justify-center rounded-[6px] border border-transparent bg-[var(--c-primary)] px-[24px] py-[8px] text-[15px] font-semibold text-[var(--c-on-primary)] hover:bg-[var(--c-primary-active)]"
                      data-testid="s-08-orders-retry"
                    >
                      {t('orders.retry', 'Try again')}
                    </button>
                  </td>
                </tr>
              )}

              {!loading1 && !error1 && sorted.length === 0 && (
                <tr data-testid="s-08-orders-empty">
                  <td colSpan={6} className="px-[24px] py-[64px] text-center text-[15px] text-[var(--c-muted)]">
                    {role != null
                      ? t('orders.empty', "You haven't placed any orders yet.")
                      : t('orders.emptyGuest', 'Sign in to view your orders.')}
                  </td>
                </tr>
              )}

              {!loading1 && !error1 && sorted.map((row, i) => {
                const meta = statusMeta(row.status);
                const count = row.itemCount ?? (Array.isArray(row.items) ? row.items.length : undefined);
                return (
                  <tr
                    key={row.id ?? i}
                    className="hover:bg-[var(--c-surface-soft)]"
                    data-testid={`s-08-orders-row-${row.id ?? i}`}
                  >
                    <td className={cn(tdBase, 'font-medium text-[var(--c-ink)]')}>{row.orderNumber ?? ''}</td>
                    <td className={tdBase}>{String(row.placedAt ?? '').slice(0, 10)}</td>
                    <td className={tdBase}>{count ?? '—'}</td>
                    <td className={cn(tdBase, 'text-right [font-variant-numeric:tabular-nums]')}>
                      {row.total != null ? `$${row.total}` : ''}
                    </td>
                    <td className={cn(tdBase, 'border-b')}>
                      <span
                        className={cn(
                          'inline-flex items-center gap-[2px] rounded-full px-[8px] py-[2px] text-[12px] font-medium tracking-[0.2px]',
                          meta.cls,
                        )}
                      >
                        {t(meta.i18nKey, meta.fallback)}
                      </span>
                    </td>
                    <td className={tdBase}>
                      <Link
                        to={`/orders/${row.id ?? ''}`}
                        className="font-medium text-[var(--c-link)] hover:text-[var(--c-primary)]"
                        data-testid={`s-08-orders-view-${row.id ?? i}`}
                      >
                        {t('orders.view', 'View')}
                      </Link>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>

      {/*
        Story acceptance-criteria wiring — preserved per scope-lock. The table
        above is the on-screen design (single list); the second fetch
        (/api/orders?sort=total) and the remaining story data-testids are kept
        accessible-only so they survive without duplicating the visible UI.
      */}
      <div className="sr-only" data-testid="s-08-orders-wiring">
        <Link to="/" data-testid="s-08-orders-home-link">{t('orders.home', 'Home')}</Link>

        <section data-testid="s-08-orders-ac-1">
          <ul data-testid="s-08-orders-ac-1-kpis">
            {orders.map((o, i) => (
              <li key={o.id ?? i} data-testid={`s-08-orders-ac-1-kpi-${o.id ?? i}`}>{o.orderNumber ?? ''}</li>
            ))}
          </ul>
        </section>

        <section data-testid="s-08-orders-ac-2">
          {loading2 && <span data-testid="s-08-orders-ac-2-loading" />}
          {!loading2 && error2 && <span data-testid="s-08-orders-ac-2-error">{error2}</span>}
          <ul data-testid="s-08-orders-ac-2-kpis">
            {ordersByTotal.map((o, i) => (
              <li key={o.id ?? i} data-testid={`s-08-orders-ac-2-kpi-${o.id ?? i}`}>{o.orderNumber ?? ''}</li>
            ))}
          </ul>
        </section>

        <section data-testid="s-08-orders-ac-3">
          <Link to={`/orders/${orders[0]?.id ?? ''}`}>{t('orders.viewDetail', 'View order')}</Link>
        </section>
      </div>
    </div>
  );
}
