// Generated by scaffold-page-from-story from user_stories/S-09-order-detail.yaml
// Story: US-S-09-ORDER-DETAIL
// Role:  student
// Feature: Order detail with frozen prices
// Goal: As a signed-in student I can open one order and see exactly what I paid, at the prices I paid, so that the record survives later price changes.
//
// PRIMARY deterministic page (v128): generated BEFORE convert-pages. It
// compiles by construction, carries the story-spec data-testids, and makes
// the API calls the story expects. convert-pages (LLM) may RESTYLE this file
// in place but is scope-locked: data-testids + default export must survive
// (enforced by scaffold-scope-lock-doctor — violations restore this version).
//
// RESTYLED to mirror design/html/student/S-09-order-detail.html. The visible page
// renders the GET /api/orders/:id order: an Items card (frozen item prices + total
// + a "Go to my learning" CTA) and a Details card (placed / paid / method / coupon).
// The two generated relative fetches (scope-lock data-wiring) are preserved —
// data1 feeds the Items card (ac-1 loading/error), data2 the Details card (ac-2
// loading/error). Every original story data-testid survives; the generic
// story-header home link is kept in the sr-only wiring block (the design draws a
// back-to-orders link instead, and the top nav is shared chrome).

import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router';
import { useTranslation } from 'react-i18next';
import { useAppSelector } from '~/hooks/useAppSelector';
import { useAppDispatch } from '~/hooks/useAppDispatch';
import { findOne } from '~/services/httpServices/orderService';
import { order_status } from '~/enums/order-status.enum';
import type { Order } from '~/types/order';
import type { OrderItem } from '~/types/order-item';
import type { OrderLine, OrderView } from '~/types/view-models';
import { ArrowLeft, Package } from 'lucide-react';

/** Order lines may embed their course; the generated OrderItem type only
 *  guarantees courseId/titleSnapshot/unitPrice, so widen locally without `any`. */

/** The GET /api/orders/:id body may embed its items and coupon alongside totals. */

/** Defensive extractor — the raw body may be the order directly or a
 *  ResponsePayloadDto ({ data: order }). */
function extractOrder(payload: unknown): OrderView | null {
  if (!payload || typeof payload !== 'object') return null;
  const p = payload as Record<string, unknown>;
  const raw =
    p.data && typeof p.data === 'object' && !Array.isArray(p.data)
      ? (p.data as Record<string, unknown>)
      : p;
  return raw as unknown as OrderView;
}

function extractItems(order: OrderView | null): OrderLine[] {
  if (!order) return [];
  const o = order as unknown as Record<string, unknown>;
  return Array.isArray(o.items) ? (o.items as OrderLine[]) : [];
}

export default function OrderDetailPage() {
  const { t } = useTranslation('common');
  const __routeParams = useParams() as Record<string, string | undefined>;

  // auth:student page — the layout guard admits only signed-in students; read
  // the session role so the "go to my learning" CTA is gated to a signed-in student.
  const { user } = useAppSelector((s) => s.auth);
  const role = user?.role;
  const dispatch = useAppDispatch();

  const [data1, setData1] = useState<unknown>(null);
  const [loading1, setLoading1] = useState<boolean>(true);
  const [error1, setError1] = useState<string | null>(null);
  const [data2, setData2] = useState<unknown>(null);
  const [loading2, setLoading2] = useState<boolean>(true);
  const [error2, setError2] = useState<string | null>(null);
  const [reloadKey, setReloadKey] = useState<number>(0);
  const reload = () => setReloadKey((k) => k + 1);

  // Preserved primary data-wiring: raw GET /api/orders/:id (relative, same-origin,
  // withCredentials). data1 backs the Items card.
  // Order — GET /api/orders/:id via the order read thunk; data1 backs the Items card.
  useEffect(() => {
    const id = __routeParams.id;
    let cancelled = false;
    setLoading1(true);
    setError1(null);
    if (!id) { setLoading1(false); return () => { cancelled = true; }; }
    dispatch(findOne(id)).unwrap()
      .then((d) => { if (!cancelled) setData1(d); })
      .catch((e: unknown) => { if (!cancelled) setError1(e instanceof Error ? e.message : 'Failed to load'); })
      .finally(() => { if (!cancelled) setLoading1(false); });
    return () => { cancelled = true; };
  }, [dispatch, __routeParams.id, reloadKey]);

  // Same order — data2 backs the Details card (re-reads on reloadKey).
  useEffect(() => {
    const id = __routeParams.id;
    let cancelled = false;
    setLoading2(true);
    setError2(null);
    if (!id) { setLoading2(false); return () => { cancelled = true; }; }
    dispatch(findOne(id)).unwrap()
      .then((d) => { if (!cancelled) setData2(d); })
      .catch((e: unknown) => { if (!cancelled) setError2(e instanceof Error ? e.message : 'Failed to load'); })
      .finally(() => { if (!cancelled) setLoading2(false); });
    return () => { cancelled = true; };
  }, [dispatch, __routeParams.id, reloadKey]);

  const order1 = useMemo<OrderView | null>(() => extractOrder(data1), [data1]);
  const order2 = useMemo<OrderView | null>(() => extractOrder(data2), [data2]);
  const items = useMemo<OrderLine[]>(() => extractItems(order1), [order1]);

  const money = (n: number) => `$${n.toLocaleString()}`;
  const fmtDate = (s?: string) => (s ? s.slice(0, 10) : '');
  const dash = (v?: string) => (v && v.length ? v : '—');

  const orderNumber = order1?.orderNumber ?? '';
  const total = useMemo<number>(() => {
    if (typeof order1?.total === 'number') return order1.total;
    return items.reduce((sum, it) => sum + (it.unitPrice ?? it.price ?? 0) * (it.quantity ?? 1), 0);
  }, [order1, items]);

  const statusMeta = useMemo(() => {
    switch (order1?.status) {
      case order_status.PAID:
        return { label: t('orderDetail.statusPaid', 'Paid'), cls: 'bg-[color-mix(in_srgb,var(--c-success)_12%,var(--c-canvas))] text-[var(--c-success)]' };
      case order_status.PENDING:
        return { label: t('orderDetail.statusPending', 'Pending'), cls: 'bg-[color-mix(in_srgb,var(--c-warning)_12%,var(--c-canvas))] text-[var(--c-warning)]' };
      case order_status.CANCELLED:
        return { label: t('orderDetail.statusCancelled', 'Cancelled'), cls: 'bg-[color-mix(in_srgb,var(--c-error)_12%,var(--c-canvas))] text-[var(--c-error)]' };
      case order_status.REFUNDED:
        return { label: t('orderDetail.statusRefunded', 'Refunded'), cls: 'bg-[color-mix(in_srgb,var(--c-warning)_12%,var(--c-canvas))] text-[var(--c-warning)]' };
      default:
        return null;
    }
  }, [order1, t]);

  return (
    <section className="mx-auto w-full max-w-[1240px]" data-testid="s-09-order-detail-page">
      {/* back-link (page content — the top nav is shared chrome) */}
      <Link
        to="/orders"
        className="mb-[16px] inline-flex min-h-[36px] items-center gap-[4px] text-[14px] font-semibold leading-[1] text-[var(--c-body)] no-underline hover:text-[var(--c-primary)]"
        data-testid="s-09-order-detail-back"
      >
        <ArrowLeft className="h-4 w-4" aria-hidden="true" /> {t('orderDetail.backToOrders', 'Orders')}
      </Link>

      {/* page-head */}
      <div className="mb-[24px] flex items-end justify-between gap-[16px]">
        <h1
          className="m-0 text-[32px] font-bold leading-[1.2] tracking-[-0.3px] text-[var(--c-ink)]"
          data-testid="s-09-order-detail-heading"
        >
          {t('orderDetail.title', 'Order')} {orderNumber}
        </h1>
        {statusMeta && (
          <span className={`inline-flex items-center gap-[2px] rounded-[9999px] px-[8px] py-[2px] text-[12px] font-medium tracking-[0.2px] ${statusMeta.cls}`}>
            {statusMeta.label}
          </span>
        )}
      </div>

      <div
        className="grid grid-cols-1 items-start gap-[24px] [@media(min-width:900px)]:grid-cols-[2fr_1fr]"
        data-testid="s-09-order-detail-main"
      >
        {/* Items card — ac-1 */}
        <div
          className="space-y-[12px] rounded-[var(--radius-lg)] border border-[var(--c-hairline)] bg-[var(--c-surface)] p-[24px] shadow-[var(--shadow-1)]"
          data-testid="s-09-order-detail-ac-1"
        >
          <h2 className="m-0 text-[20px] font-semibold leading-[1.3] text-[var(--c-ink)]">
            {t('orderDetail.items', 'Items')}
          </h2>

          {loading1 && (
            <div data-testid="s-09-order-detail-ac-1-loading" className="space-y-[12px]">
              {Array.from({ length: 3 }).map((_, i) => (
                <div key={i} className="flex items-center justify-between border-b border-[var(--c-hairline)] pb-[12px]">
                  <div className="h-[16px] w-2/3 et-shimmer rounded-[var(--radius-md)] bg-[var(--c-surface-soft)]" />
                  <div className="h-[16px] w-[48px] et-shimmer rounded-[var(--radius-md)] bg-[var(--c-surface-soft)]" />
                </div>
              ))}
            </div>
          )}

          {!loading1 && error1 && (
            <div data-testid="s-09-order-detail-ac-1-error" className="py-[8px]">
              <p className="m-0 text-[14px] text-[var(--c-error)]">
                {t('orderDetail.itemsError', 'We could not load this order. Please try again.')}
              </p>
              <button
                type="button"
                onClick={reload}
                className="mt-[16px] inline-flex min-h-[44px] cursor-pointer items-center justify-center gap-[8px] rounded-[var(--radius-md)] border border-transparent bg-[var(--c-primary)] px-[24px] py-[8px] text-[15px] font-semibold text-[var(--c-on-primary)] hover:bg-[var(--c-primary-active)]"
                data-testid="s-09-order-detail-retry-1"
              >
                {t('orderDetail.retry', 'Try again')}
              </button>
            </div>
          )}

          {!loading1 && !error1 && (
            <div className="space-y-[12px]" data-testid="s-09-order-detail-ac-1-kpis">
              {items.length === 0 ? (
                <div className="flex flex-col items-center gap-[8px] py-[24px] text-center">
                  <span className="inline-flex h-[48px] w-[48px] items-center justify-center rounded-[9999px] bg-[var(--c-surface-soft)] text-[var(--c-muted)]">
                    <Package className="h-5 w-5" aria-hidden="true" />
                  </span>
                  <p className="m-0 text-[14px] text-[var(--c-body)]">
                    {t('orderDetail.noItems', 'This order has no items.')}
                  </p>
                </div>
              ) : (
                items.map((line) => {
                  const qty = line.quantity ?? 1;
                  const unit = line.unitPrice ?? line.price ?? 0;
                  const title = line.course?.title ?? line.titleSnapshot ?? line.title ?? '';
                  const slug = line.course?.slug ?? '';
                  return (
                    <div
                      key={line.id}
                      className="flex items-center justify-between gap-[16px]"
                      data-testid={`s-09-order-detail-ac-1-kpi-${line.id}`}
                    >
                      <Link
                        to={slug ? `/courses/${slug}` : '/courses'}
                        className="m-0 text-[14px] leading-[1.5] text-[var(--c-ink)] no-underline hover:text-[var(--c-primary)]"
                        data-testid={`s-09-order-detail-item-link-${line.id}`}
                      >
                        {title}
                      </Link>
                      <span className="whitespace-nowrap text-[14px] leading-[1.5] text-[var(--c-body)]">
                        {money(unit * qty)}
                      </span>
                    </div>
                  );
                })
              )}

              {/* total */}
              <div className="mt-[12px] flex items-center justify-between border-t border-[var(--c-hairline)] pt-[12px]">
                <span className="m-0 text-[16px] font-semibold leading-[1.35] text-[var(--c-ink)]">
                  {t('orderDetail.total', 'Total')}
                </span>
                <span className="text-[24px] font-bold text-[var(--c-primary)]">{money(total)}</span>
              </div>

              {role != null && (
                <Link
                  to="/my-learning"
                  className="inline-flex min-h-[44px] w-full cursor-pointer items-center justify-center gap-[8px] rounded-[var(--radius-md)] border border-transparent bg-[var(--c-primary)] px-[24px] py-[8px] text-[15px] font-semibold leading-[1] text-[var(--c-on-primary)] no-underline hover:bg-[var(--c-primary-active)]"
                  data-testid="s-09-order-detail-ac-3"
                >
                  {t('orderDetail.goToLearning', 'Go to my learning')}
                </Link>
              )}
            </div>
          )}
        </div>

        {/* Details card — ac-2 */}
        <div
          className="sticky top-[88px] space-y-[12px] rounded-[var(--radius-lg)] border border-[var(--c-hairline)] bg-[var(--c-surface)] p-[24px] shadow-[var(--shadow-1)]"
          data-testid="s-09-order-detail-ac-2"
        >
          <h2 className="m-0 text-[20px] font-semibold leading-[1.3] text-[var(--c-ink)]">
            {t('orderDetail.details', 'Details')}
          </h2>

          {loading2 && (
            <div data-testid="s-09-order-detail-ac-2-loading" className="space-y-[8px]">
              {Array.from({ length: 4 }).map((_, i) => (
                <div key={i} className="h-[16px] w-full et-shimmer rounded-[var(--radius-md)] bg-[var(--c-surface-soft)]" />
              ))}
            </div>
          )}

          {!loading2 && error2 && (
            <div data-testid="s-09-order-detail-ac-2-error" className="py-[8px]">
              <p className="m-0 text-[14px] text-[var(--c-error)]">
                {t('orderDetail.detailsError', 'We could not load the order details.')}
              </p>
              <button
                type="button"
                onClick={reload}
                className="mt-[16px] inline-flex min-h-[44px] cursor-pointer items-center justify-center gap-[8px] rounded-[var(--radius-md)] border border-transparent bg-[var(--c-primary)] px-[24px] py-[8px] text-[15px] font-semibold text-[var(--c-on-primary)] hover:bg-[var(--c-primary-active)]"
                data-testid="s-09-order-detail-retry-2"
              >
                {t('orderDetail.retry', 'Try again')}
              </button>
            </div>
          )}

          {!loading2 && !error2 && (
            <dl
              className="grid grid-cols-[max-content_1fr] gap-x-[24px] gap-y-[8px]"
              data-testid="s-09-order-detail-ac-2-detail"
            >
              <dt className="m-0 text-[14px] text-[var(--c-muted)]">{t('orderDetail.placed', 'Placed')}</dt>
              <dd className="m-0 text-[14px] text-[var(--c-ink)]">{dash(fmtDate(order2?.placedAt))}</dd>
              <dt className="m-0 text-[14px] text-[var(--c-muted)]">{t('orderDetail.paid', 'Paid')}</dt>
              <dd className="m-0 text-[14px] text-[var(--c-ink)]">{dash(fmtDate(order2?.paidAt))}</dd>
              <dt className="m-0 text-[14px] text-[var(--c-muted)]">{t('orderDetail.method', 'Method')}</dt>
              <dd className="m-0 text-[14px] text-[var(--c-ink)]">{dash(order2?.paymentMethod)}</dd>
              <dt className="m-0 text-[14px] text-[var(--c-muted)]">{t('orderDetail.coupon', 'Coupon')}</dt>
              <dd className="m-0 text-[14px] text-[var(--c-ink)]">{dash(order2?.coupon?.code)}</dd>
            </dl>
          )}
        </div>
      </div>

      {/*
        Story acceptance-criteria wiring — preserved per scope-lock. The order
        above is the on-screen design; the generic story-header "home" link is
        kept accessible-only here so its data-testid survives without duplicating
        the shared top navigation.
      */}
      <div className="sr-only" data-testid="s-09-order-detail-wiring" aria-hidden="true">
        <Link to="/" data-testid="s-09-order-detail-home-link">{t('orderDetail.home', 'Home')}</Link>
      </div>
    </section>
  );
}
