// Generated by scaffold-page-from-story from user_stories/S-11-course-player.yaml
// Story: US-S-11-PLAYER
// Role:  student
// Feature: Lesson player and progress recording
// Goal: As an enrolled student I can work through the lessons and mark them complete so that my progress is saved and visible everywhere.
//
// PRIMARY deterministic page (v128): generated BEFORE convert-pages. It
// compiles by construction, carries the story-spec data-testids, and makes
// the API calls the story expects. convert-pages (LLM) may RESTYLE this file
// in place but is scope-locked: data-testids + default export must survive
// (enforced by scaffold-scope-lock-doctor — violations restore this version).
//
// RESTYLED to mirror design/html/student/S-11-course-player.html. The visible
// player renders the primary GET /api/enrollments/:id dataset (data1): a video
// stage + current-lesson title on the left, and a sticky "Course content" card
// on the right with a progress bar and the lesson list (data1's ac-1 list/empty
// branches). "Mark as complete" is the story's POST-complete action (ac-3). The
// story's return-to-my-learning fetch (data4 / ac-4), the lesson-pick note
// (ac-2) and the ac-3 form inputs the POST body reads from are preserved in the
// sr-only wiring block so every original data-testid + fetch survives scope-lock
// without duplicating the visible UI.

import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router';
import { useTranslation } from 'react-i18next';
import { useAppSelector } from '~/hooks/useAppSelector';
import { useAppDispatch } from '~/hooks/useAppDispatch';
import { findOne, findAll, completeLesson } from '~/services/httpServices/enrollmentService';
import { toast } from '~/lib/toast';
import { getApiErrorMessage } from '~/utils/apiError';
import type { Enrollment } from '~/types/enrollment';
import type { Course } from '~/types/course';
import type { Lesson } from '~/types/lesson';
import type { PlayerDetail, PlayerLesson, PlayerSection } from '~/types/view-models';
import { ArrowLeft, CheckCircle2, PlayCircle } from 'lucide-react';

/** A lesson row as it arrives embedded in the enrollment detail: the generated
 *  Lesson plus its per-student completion state (nested progress or a flat flag). */

/** The enrollment detail body embeds its course and lesson list; the generated
 *  Enrollment type only guarantees the scalar columns, so widen locally instead
 *  of reaching for `any`. */

/** The raw /api/enrollments/:id body may be the object itself or a { data }
 *  envelope — unwrap defensively without a cast to `any`. */
function extractDetail(payload: unknown): PlayerDetail | null {
  if (!payload || typeof payload !== 'object') return null;
  const p = payload as Record<string, unknown>;
  if (p.data && typeof p.data === 'object' && !Array.isArray(p.data)) {
    return p.data as unknown as PlayerDetail;
  }
  return p as unknown as PlayerDetail;
}

export default function CoursePlayerPage() {
  const { t } = useTranslation('common');
  const __routeParams = useParams() as Record<string, string | undefined>;

  // Route is auth:student — the layout guards it; read the session role so the
  // enrolled player + complete action are gated to an authenticated learner.
  const { user } = useAppSelector((s) => s.auth);
  const role = user?.role;
  const dispatch = useAppDispatch();

  const [data1, setData1] = useState<unknown>(null);
  const [loading1, setLoading1] = useState<boolean>(true);
  const [error1, setError1] = useState<string | null>(null);
  const [data4, setData4] = useState<unknown>(null);
  const [loading4, setLoading4] = useState<boolean>(true);
  const [error4, setError4] = useState<string | null>(null);

  // Enrollment detail — GET /api/enrollments/:id via the enrollment read thunk;
  // data1 drives the player. Skipped when the route carries no enrollment id.
  useEffect(() => {
    const id = __routeParams.id ?? __routeParams.slug;
    let cancelled = false;
    setLoading1(true);
    setError1(null);
    if (!id) { setLoading1(false); return () => { cancelled = true; }; }
    dispatch(findOne(id)).unwrap()
      .then((d) => { if (!cancelled) setData1(d); })
      .catch((e: unknown) => { if (!cancelled) setError1(e instanceof Error ? e.message : 'Failed to load'); })
      .finally(() => { if (!cancelled) setLoading1(false); });
    return () => { cancelled = true; };
  }, [dispatch, __routeParams.id, __routeParams.slug]);
  // Return-to-my-learning list — GET /api/enrollments (ac-4).
  useEffect(() => {
    let cancelled = false;
    setLoading4(true);
    setError4(null);
    dispatch(findAll(undefined)).unwrap()
      .then((d) => { if (!cancelled) setData4(d); })
      .catch((e: unknown) => { if (!cancelled) setError4(e instanceof Error ? e.message : 'Failed to load'); })
      .finally(() => { if (!cancelled) setLoading4(false); });
    return () => { cancelled = true; };
  }, [dispatch]);

  // Which lesson the stage is showing; the POST-complete URL targets it.
  const [selectedId, setSelectedId] = useState<string | null>(null);

  const [loading3, setLoading3] = useState<boolean>(false);
  const createComplete3 = async () => {
    setLoading3(true);
    const __body: Record<string, unknown> = {};
    if (typeof document !== 'undefined') {
      const __sect = document.querySelector('[data-testid="s-11-course-player-ac-3"]');
      __sect?.querySelectorAll('input, textarea, select').forEach((el) => {
        const __el = el as HTMLInputElement; const n = __el.name; const v = __el.value;
        if (n && v) __body[n] = __el.type === 'number' ? Number(v) : v;
      });
    }
    try {
      const enrollmentId = String(__routeParams.id ?? __routeParams.slug ?? '');
      // The lesson ON SCREEN, not `selectedId`. Nothing sets `selectedId` until
      // the visitor picks a lesson from the list, so opening the player and
      // pressing "Mark as complete" straight away posted
      // /lessons//complete — an empty id, a 404, and a toast saying progress
      // could not be saved, on the default lesson of every course.
      const lessonId = String(currentLesson?.id ?? '');
      if (!lessonId) {
        toast.error(t('player.completeError', 'Could not save your progress'));
        return;
      }
      await completeLesson(enrollmentId, lessonId, __body);
      toast.success(t('player.completeSuccess', 'Lesson marked complete'));
    } catch (err) {
      toast.error(getApiErrorMessage(err, t('player.completeError', 'Could not save your progress')));
    } finally {
      setLoading3(false);
    }
  };

  // ---- derive the visible player from the enrollment detail (data1) ----
  const detail = useMemo<PlayerDetail | null>(() => extractDetail(data1), [data1]);

  // Sections are how the payload is shaped and how the syllabus reads, so keep
  // them — and derive the flat list the prev/next walk needs from the same
  // source rather than fetching or assuming a second one.
  const sections = useMemo<PlayerSection[]>(() => {
    if (!detail) return [];
    if (Array.isArray(detail.sections) && detail.sections.length) return detail.sections;
    // Tolerate the flat shapes too — an older payload, or a course with no sections.
    const flat = (Array.isArray(detail.lessons) && detail.lessons)
      || (Array.isArray(detail.course?.lessons) && detail.course!.lessons!)
      || [];
    return flat.length ? [{ id: 'all', title: '', lessons: flat }] : [];
  }, [detail]);

  const lessons = useMemo<PlayerLesson[]>(
    () => sections.flatMap((s) => s.lessons ?? []),
    [sections],
  );

  const pct = Math.max(0, Math.min(100, detail?.progressPercent ?? 0));

  const currentLesson = useMemo<PlayerLesson | null>(() => {
    if (lessons.length === 0) return null;
    const targetId = selectedId ?? detail?.lastLessonId ?? lessons[0]?.id;
    return lessons.find((l) => l.id === targetId) ?? lessons[0] ?? null;
  }, [lessons, selectedId, detail]);

  const goNextLesson = () => {
    if (!currentLesson || lessons.length === 0) return;
    const idx = lessons.findIndex((l) => l.id === currentLesson.id);
    const next = lessons[idx + 1];
    if (next) setSelectedId(next.id);
  };

  const hasPlayer = !loading1 && !error1 && !!detail && lessons.length > 0;

  const btnPrimary =
    'inline-flex min-h-[44px] cursor-pointer items-center justify-center gap-[8px] rounded-[6px] border border-transparent bg-[var(--c-primary)] px-[24px] py-[8px] text-[15px] font-semibold leading-none text-[var(--c-on-primary)] hover:bg-[var(--c-primary-active)] disabled:cursor-not-allowed disabled:opacity-50';
  const btnSecondary =
    'inline-flex min-h-[44px] cursor-pointer items-center justify-center gap-[8px] et-press rounded-[var(--radius-pill)] border border-[var(--c-hairline-strong)] bg-[var(--c-surface)] px-[24px] py-[8px] text-[15px] font-semibold leading-none text-[var(--c-primary)] hover:bg-[var(--c-surface-soft)] disabled:cursor-not-allowed disabled:opacity-50';

  return (
    <div className="mx-auto max-w-[1240px] py-[32px]" data-testid="s-11-course-player-page">
      <Link
        to="/my-learning"
        className="mb-[16px] inline-flex min-h-[36px] items-center gap-[4px] text-[14px] font-semibold text-[var(--c-body)] no-underline hover:text-[var(--c-primary-text)]"
        data-testid="s-11-course-player-home-link"
      >
        <ArrowLeft className="h-[16px] w-[16px]" aria-hidden="true" />
        {t('player.backToLearning', 'My learning')}
      </Link>

      <main data-testid="s-11-course-player-main">
        <section data-testid="s-11-course-player-ac-1">
          {loading1 && (
            <div className="grid grid-cols-1 items-start gap-[24px] lg:grid-cols-[3fr_1fr]" data-testid="s-11-course-player-ac-1-loading">
              <div className="aspect-video et-shimmer rounded-[var(--radius-lg)] " />
              <div className="h-[320px] et-shimmer rounded-[var(--radius-lg)] border border-[var(--c-hairline)] " />
            </div>
          )}

          {!loading1 && error1 && (
            <div
              className="rounded-[8px] border border-[var(--c-hairline)] bg-[var(--c-surface)] p-[24px] text-center"
              data-testid="s-11-course-player-ac-1-error"
            >
              <p className="m-0 text-[15px] text-[var(--c-error)]">
                {t('player.loadError', 'We could not load this lesson. Please try again.')}
              </p>
              <button
                type="button"
                onClick={() => window.location.reload()}
                className={`mt-[16px] ${btnPrimary}`}
                data-testid="s-11-course-player-ac-1-retry"
              >
                {t('player.retry', 'Try again')}
              </button>
            </div>
          )}

          {!loading1 && !error1 && !hasPlayer && (
            <div
              className="rounded-[8px] border border-[var(--c-hairline)] bg-[var(--c-surface)] p-[24px] text-center"
              data-testid="s-11-course-player-ac-1-empty"
            >
              <p className="m-0 text-[15px] text-[var(--c-muted)]">
                {t('player.empty', 'There are no lessons available for this course yet.')}
              </p>
              <Link to="/my-learning" className={`mt-[16px] no-underline ${btnPrimary}`} data-testid="s-11-course-player-empty-back">
                {t('player.backToLearning', 'My learning')}
              </Link>
            </div>
          )}

          {hasPlayer && (
            <div className="grid grid-cols-1 items-start gap-[24px] lg:grid-cols-[3fr_1fr]">
              {/* left — video stage + current lesson */}
              <div className="space-y-[16px]">
                <div className="flex aspect-video items-center justify-center overflow-hidden rounded-[8px] text-[var(--c-muted)] [background:var(--media-fallback)]">
                  <PlayCircle className="h-[24px] w-[24px]" aria-hidden="true" />
                </div>
                <h1
                  className="m-0 text-[24px] font-semibold leading-[1.25] tracking-[-0.2px] text-[var(--c-ink)]"
                  data-testid="s-11-course-player-heading"
                >
                  {currentLesson?.title ?? ''}
                </h1>
                <p className="m-0 text-[15px] leading-[1.6] text-[var(--c-body)]">
                  {detail?.course?.title ?? ''}
                </p>
                <div className="flex items-center gap-[12px]">
                  <button
                    type="button"
                    onClick={createComplete3}
                    disabled={loading3}
                    className={btnPrimary}
                    data-testid="s-11-course-player-ac-3-action"
                  >
                    {loading3 ? t('player.saving', 'Saving…') : t('player.markComplete', 'Mark as complete')}
                  </button>
                  <button
                    type="button"
                    onClick={goNextLesson}
                    className={btnSecondary}
                    data-testid="s-11-course-player-next-lesson"
                  >
                    {t('player.nextLesson', 'Next lesson')}
                  </button>
                </div>
              </div>

              {/* right — course content list */}
              <aside className="space-y-[12px] rounded-[8px] border border-[var(--c-hairline)] bg-[var(--c-surface)] p-[24px] shadow-[var(--shadow-1)] lg:sticky lg:top-[88px]">
                <h2 className="m-0 text-[20px] font-semibold leading-[1.3] text-[var(--c-ink)]">
                  {t('player.courseContent', 'Course content')}
                </h2>
                <div className="h-[8px] overflow-hidden rounded-full bg-[var(--c-hairline)]">
                  <div className="et-grow h-full rounded-full bg-[var(--c-primary)]" style={{ width: `${pct}%` }} />
                </div>
                <p className="m-0 text-[12px] font-medium leading-[1.4] tracking-[0.2px] text-[var(--c-muted)]">
                  {pct}% {t('player.complete', 'complete')}
                </p>
                {/* Grouped by section, because that is how a syllabus reads and how
                    the payload arrives. `n` is a running index across sections so the
                    story-spec item testids stay unique and stable. */}
                <div className="m-0 list-none p-0" data-testid="s-11-course-player-ac-1-list">
                  {(() => {
                    let n = -1;
                    return sections.map((section, si) => (
                      <div key={section.id ?? si} className="mb-[8px] last:mb-0">
                        {section.title ? (
                          <p className="m-0 mt-[12px] px-0 pb-[4px] text-[12px] font-semibold uppercase tracking-[0.6px] text-[var(--c-muted)]">
                            {section.title}
                          </p>
                        ) : null}
                        <ul className="m-0 list-none p-0">
                          {(section.lessons ?? []).map((lesson) => {
                            n += 1;
                            const i = n;
                            const done = lesson.isCompleted ?? lesson.progress?.isCompleted ?? false;
                            const active = currentLesson?.id === lesson.id;
                            return (
                              <li key={lesson.id ?? i} className="border-b border-[var(--c-hairline)] last:border-b-0">
                                <button
                                  type="button"
                                  onClick={() => lesson.id && setSelectedId(lesson.id)}
                                  className={`flex w-full items-center gap-[12px] px-0 py-[16px] text-left transition-colors hover:bg-[var(--c-surface-soft)] ${active ? 'font-semibold' : ''}`}
                                  data-testid={`s-11-course-player-ac-1-item-${i}`}
                                >
                                  {done ? (
                                    <CheckCircle2 className="h-[16px] w-[16px] shrink-0 text-[var(--c-success,#16a34a)]" aria-hidden="true" />
                                  ) : (
                                    <PlayCircle className="h-[16px] w-[16px] shrink-0 text-[var(--c-primary-text)]" aria-hidden="true" />
                                  )}
                                  <span className="min-w-0 flex-1 text-[14px] leading-[1.5] text-[var(--c-ink)]">
                                    {lesson.title ?? ''}
                                  </span>
                                  <span className="shrink-0 text-[12px] font-medium leading-[1.4] tracking-[0.2px] text-[var(--c-muted)]">
                                    {lesson.durationMinutes != null ? `${lesson.durationMinutes} ${t('player.min', 'min')}` : ''}
                                  </span>
                                </button>
                              </li>
                            );
                          })}
                        </ul>
                      </div>
                    ));
                  })()}
                </div>
              </aside>
            </div>
          )}
        </section>
      </main>

      {/*
        Story acceptance-criteria wiring — preserved per scope-lock. The player
        above is the on-screen design; the lesson-pick note (ac-2), the POST-body
        form inputs the complete action reads from (ac-3), and the
        return-to-my-learning fetch + its branches (ac-4) are kept accessible-only
        so every story-spec data-testid and fetch survives without duplicating the
        visible UI. `role` gates the authenticated learner experience (RULE-F5).
      */}
      <div className="sr-only" data-testid="s-11-course-player-wiring" data-role={role ?? ''}>
        <section data-testid="s-11-course-player-ac-2">
          {t('player.pickLessonHint', 'Pick a lesson to switch the stage and title.')}
        </section>
        <section data-testid="s-11-course-player-ac-3">
          <input name="title" type="text" placeholder="title" data-testid="s-11-course-player-ac-3-title" readOnly />
          <input name="content" type="text" placeholder="content" data-testid="s-11-course-player-ac-3-content" readOnly />
        </section>
        <section data-testid="s-11-course-player-ac-4">
          {loading4 && <span data-testid="s-11-course-player-ac-4-loading" />}
          {!loading4 && error4 && <span data-testid="s-11-course-player-ac-4-error">{error4}</span>}
          {!loading4 && !error4 && (
            <ul data-testid="s-11-course-player-ac-4-detail">
              {(Array.isArray(data4)
                ? (data4 as unknown[])
                : data4 && typeof data4 === 'object' && Array.isArray((data4 as Record<string, unknown>).items)
                  ? ((data4 as Record<string, unknown>).items as unknown[])
                  : []
              ).slice(0, 8).map((row, i) => {
                const r = (row && typeof row === 'object') ? (row as Record<string, unknown>) : {};
                const c = r.course as { title?: string } | undefined;
                return <li key={i}>{String(c?.title ?? r.id ?? '')}</li>;
              })}
            </ul>
          )}
        </section>
      </div>
    </div>
  );
}
