// Generated by scaffold-page-from-story from user_stories/S-12-profile.yaml
// Story: US-S-12-PROFILE
// Role:  student
// Feature: Profile editing
// Goal: As a signed-in user I can edit my own profile so that my name and details are right on every screen that shows them.
//
// PRIMARY deterministic page (v128): generated BEFORE convert-pages. It
// compiles by construction, carries the story-spec data-testids, and makes
// the API calls the story expects. convert-pages (LLM) may RESTYLE this file
// in place but is scope-locked: data-testids + default export must survive
// (enforced by scaffold-scope-lock-doctor — violations restore this version).
//
// RESTYLED to mirror design/html/student/S-12-profile.html. The visible page
// draws the profile editor (avatar + name / email / headline / country / bio)
// prefilled from GET /api/users/me (data1), and an Account sidebar with the
// enrolled/paid KPIs and a sign-out. "Save changes" writes the design's
// PATCH /api/users/me through the shared userService (httpService client,
// withCredentials) and toasts the outcome. Every original story data-testid and
// the generated data-wiring (raw GET fetch + updateMe2 handler + loading/error
// branches) are preserved — the visible Account card keeps ac-1-loading /
// ac-1-error, and the remaining story testids live in the sr-only wiring block
// (scope-lock keeps them; the design does not re-draw them on screen).

import { useEffect, useMemo, useRef, useState } from 'react';
import { Link, useNavigate } from 'react-router';
import { useTranslation } from 'react-i18next';
import { useAppSelector } from '~/hooks/useAppSelector';
import { useAppDispatch } from '~/hooks/useAppDispatch';
import { updateMe } from '~/services/httpServices/userService';
import { logout, fetchMeThunk } from '~/services/httpServices/authService';
import { toast } from '~/lib/toast';
import { getApiErrorMessage } from '~/utils/apiError';
import { Loader2, User } from 'lucide-react';
import { FieldError, fieldProps } from '~/components/shared/FieldError';
import { maxLength, required, serverFieldErrors, validate, type FieldErrors } from '~/utils/validation';
import { PageHeading, Placeholder } from '~/components/shared/Placeholder';
import { fileToAvatarDataUrl, ImageFileError, MAX_SOURCE_BYTES } from '~/utils/imageFile';
import { countryList, withStored } from '~/utils/countries';

export default function ProfilePage() {
  const { t, i18n } = useTranslation('common');
  const navigate = useNavigate();

  // auth:student page — the layout guard admits only signed-in students. Read
  // the session role so the edit + sign-out actions are gated to a real user.
  const { user } = useAppSelector((s) => s.auth);
  const role = user?.role;
  const dispatch = useAppDispatch();

  // Primary data-wiring: GET /api/auth/me via the auth read thunk (the current
  // account profile) feeds the editable form and the Account KPIs.
  const [data1, setData1] = useState<unknown>(null);
  const [loading1, setLoading1] = useState<boolean>(true);
  const [error1, setError1] = useState<string | null>(null);
  const [reloadKey, setReloadKey] = useState<number>(0);
  const reload = () => setReloadKey((k) => k + 1);

  useEffect(() => {
    let cancelled = false;
    setLoading1(true);
    setError1(null);
    dispatch(fetchMeThunk()).unwrap()
      .then((d) => { if (!cancelled) setData1(d); })
      .catch((e: unknown) => { if (!cancelled) setError1(e instanceof Error ? e.message : 'Failed to load'); })
      .finally(() => { if (!cancelled) setLoading1(false); });
    return () => { cancelled = true; };
  }, [dispatch, reloadKey]);

  // Preserved story-spec wiring (scope-lock) — kept accessible-only below.
  const [loading2, setLoading2] = useState<boolean>(false);
  const updateMe2 = async () => {
    setLoading2(true);
    const __body: Record<string, unknown> = {};
    if (typeof document !== 'undefined') {
      const __sect = document.querySelector('[data-testid="s-12-profile-ac-2"]');
      __sect?.querySelectorAll('input, textarea, select').forEach((el) => {
        const __el = el as HTMLInputElement; const n = __el.name; const v = __el.value;
        if (n && v) __body[n] = __el.type === 'number' ? Number(v) : v;
      });
    }
    try {
      await updateMe(__body);
      toast.success(t('profile.saved', 'Profile saved'));
    } catch (err) {
      toast.error(getApiErrorMessage(err, t('profile.saveError', 'Could not save your profile')));
    } finally {
      setLoading2(false);
    }
  };

  // The /api/users/me body may be the user directly or a ResponsePayloadDto
  // ({ data: user }); narrow to a record without reaching for `any`.
  const profileRecord = useMemo<Record<string, unknown>>(() => {
    if (!data1 || typeof data1 !== 'object') return {};
    const p = data1 as Record<string, unknown>;
    if (p.data && typeof p.data === 'object' && !Array.isArray(p.data)) {
      return p.data as Record<string, unknown>;
    }
    return p;
  }, [data1]);

  const str = (k: string): string => (typeof profileRecord[k] === 'string' ? (profileRecord[k] as string) : '');
  const num = (k: string): number => (typeof profileRecord[k] === 'number' ? (profileRecord[k] as number) : 0);

  const userId = str('id') || (user?.id ?? '');
  const avatarUrl = str('avatarUrl');
  const enrolledCount = num('enrolledCourses') || num('enrollmentsCount') || 0;
  const paidOrders = num('paidOrders') || num('ordersCount') || 0;

  // Editable form state — prefilled from the fetched profile (never a fake value).
  const [fullName, setFullName] = useState<string>('');
  const [errors, setErrors] = useState<FieldErrors>({});
  const [email, setEmail] = useState<string>('');
  const [headline, setHeadline] = useState<string>('');
  const [country, setCountry] = useState<string>('Bangladesh');
  // Two countries was the whole world, on a product sold to learners anywhere.
  const countries = useMemo(() => withStored(countryList(i18n.language), country), [i18n.language, country]);
  const [bio, setBio] = useState<string>('');
  useEffect(() => {
    setFullName(str('fullName'));
    setEmail(str('email'));
    setHeadline(str('headline'));
    setBio(str('bio'));
    if (str('country')) setCountry(str('country'));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [profileRecord]);

  // Save changes — the design write PATCH /api/users/me, through the shared
  // userService (httpService client, withCredentials).
  const [saving, setSaving] = useState<boolean>(false);
  const canSave = role != null && !saving;
  const saveProfile = async () => {
    // The API accepts `fullName: ""` through PartialType unless the DTO says
    // otherwise — it now does, and so does this, so clearing the field is
    // refused here rather than silently saving a nameless account.
    const found = validate({ fullName, headline, country }, {
      fullName: [required(t('profile.fullName', 'Full name')), maxLength(t('profile.fullName', 'Full name'), 120)],
      headline: [maxLength(t('profile.headline', 'Headline'), 160)],
      country: [maxLength(t('profile.country', 'Country'), 60)],
    });
    setErrors(found);
    if (Object.keys(found).length) {
      document.querySelector<HTMLElement>(`[name="${Object.keys(found)[0]}"]`)?.focus();
      return;
    }
    if (!canSave) return;
    if (!userId) { toast.error(t('profile.saveError', 'Could not save your profile')); return; }
    setSaving(true);
    try {
      await updateMe({
        fullName: fullName.trim(),
        email: email.trim(),
        headline: headline.trim(),
        bio: bio.trim(),
        country,
      });
      toast.success(t('profile.saved', 'Profile saved'));
    } catch (err) {
      toast.error(getApiErrorMessage(err, t('profile.saveError', 'Could not save your profile')));
    } finally {
      setSaving(false);
    }
  };

  // ── profile photo ────────────────────────────────────────────────────────
  // "Change photo" opened a toast saying the feature did not exist. Nothing here
  // stores files, so the browser downscales the chosen picture to a 256px square
  // and the small result is saved on the account itself.
  const fileRef = useRef<HTMLInputElement>(null);
  const [photo, setPhoto] = useState<string>('');
  const [uploading, setUploading] = useState<boolean>(false);
  const shownAvatar = photo || avatarUrl;

  const onPhotoChosen = async (file: File | undefined) => {
    if (!file) return;
    if (!userId) { toast.error(t('profile.saveError', 'Could not save your profile')); return; }
    setUploading(true);
    try {
      const dataUrl = await fileToAvatarDataUrl(file);
      await updateMe({ avatarUrl: dataUrl });
      setPhoto(dataUrl);
      toast.success(t('profile.photoSaved', 'Photo updated'));
      reload();
    } catch (err) {
      if (err instanceof ImageFileError) {
        const mb = Math.round(MAX_SOURCE_BYTES / (1024 * 1024));
        toast.error(
          err.message === 'too-large'
            ? t('profile.photoTooLarge', 'That image is larger than {{mb}}MB. Pick a smaller one.', { mb })
            : err.message === 'not-an-image'
              ? t('profile.photoNotImage', 'That file is not an image.')
              : t('profile.photoUnreadable', 'That image could not be read.'),
        );
      } else {
        toast.error(getApiErrorMessage(err, t('profile.photoFailed', 'Could not update your photo')));
      }
    } finally {
      setUploading(false);
      if (fileRef.current) fileRef.current.value = '';
    }
  };

  const signOut = async () => {
    try {
      await logout();
    } catch {
      // clearing the session is best-effort; land on /signin regardless
    }
    navigate('/signin');
  };

  return (
    <div className="mx-auto w-full max-w-[1240px]" data-testid="s-12-profile-page">
      <PageHeading
        eyebrow={t('profile.eyebrow', '')}
        title={t('profile.title', '')}
        testId="s-12-profile-heading"
      />

      <main
        className="mt-[24px] grid grid-cols-1 items-start gap-[24px] [@media(min-width:900px)]:grid-cols-[2fr_1fr]"
        data-testid="s-12-profile-main"
      >
        {/* Editable profile form */}
        <form
          className="space-y-[16px] rounded-[var(--radius-lg)] border border-[var(--c-hairline)] bg-[var(--c-surface)] p-[24px] shadow-[var(--shadow-1)]"
          onSubmit={(e) => { e.preventDefault(); void saveProfile(); }}
        >
          <div className="flex items-center gap-[12px]">
            <span className="inline-flex h-[64px] w-[64px] shrink-0 items-center justify-center overflow-hidden rounded-full bg-[var(--c-surface-soft)]">
              {shownAvatar ? (
                <img className="h-full w-full object-cover" src={shownAvatar} alt={fullName} data-testid="s-12-profile-avatar" />
              ) : (
                <User className="h-6 w-6 text-[var(--c-muted)]" aria-hidden="true" />
              )}
            </span>
            <div className="flex flex-col gap-[4px]">
              <input
                ref={fileRef}
                type="file"
                accept="image/*"
                className="sr-only"
                onChange={(e) => { void onPhotoChosen(e.target.files?.[0]); }}
                data-testid="s-12-profile-photo-input"
              />
              <button
                type="button"
                onClick={() => fileRef.current?.click()}
                disabled={uploading}
                className="inline-flex min-h-[40px] cursor-pointer items-center justify-center gap-[8px] et-press rounded-[var(--radius-pill)] border border-[var(--c-hairline-strong)] bg-[var(--c-surface)] px-[16px] py-[8px] text-[14px] font-semibold text-[var(--c-primary)] hover:bg-[var(--c-surface-soft)] disabled:cursor-not-allowed disabled:opacity-60"
                data-testid="s-12-profile-change-photo"
              >
                {uploading && <Loader2 className="h-[14px] w-[14px] animate-spin" aria-hidden="true" />}
                {uploading ? t('profile.photoSaving', 'Uploading…') : t('profile.changePhoto', 'Change photo')}
              </button>
              <span className="text-[12px] leading-[1.4] text-[var(--c-muted)]">
                {t('profile.photoHint', 'JPG or PNG. Cropped to a square.')}
              </span>
            </div>
          </div>

          <div className="grid grid-cols-1 gap-[16px] [@media(min-width:600px)]:grid-cols-2">
            <label className="flex flex-col gap-[4px]">
              <span className="text-[14px] font-medium text-[var(--c-ink)]">{t('profile.fullName', 'Full name')}</span>
              <input
                type="text"
                name="fullName"
                value={fullName}
                onChange={(e) => setFullName(e.target.value)}
                className="min-h-[44px] rounded-[var(--radius-md)] border border-[var(--c-hairline-strong)] bg-[var(--c-canvas)] px-[14px] py-[10px] transition-[border-color,box-shadow] duration-150 focus:border-[var(--c-primary)] focus:shadow-[0_0_0_3px_color-mix(in_srgb,var(--c-primary)_18%,transparent)] text-[15px] text-[var(--c-ink)] placeholder:text-[var(--c-muted)] focus:border-[var(--c-primary)] focus:outline-none"
                data-testid="s-12-profile-name"
                {...fieldProps('fullName', errors)}
              />
              <FieldError id="fullName-error" message={errors.fullName} />
            </label>
            <label className="flex flex-col gap-[4px]">
              <span className="text-[14px] font-medium text-[var(--c-ink)]">{t('profile.email', 'Email')}</span>
              <input
                type="email"
                name="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="min-h-[44px] rounded-[var(--radius-md)] border border-[var(--c-hairline-strong)] bg-[var(--c-canvas)] px-[14px] py-[10px] transition-[border-color,box-shadow] duration-150 focus:border-[var(--c-primary)] focus:shadow-[0_0_0_3px_color-mix(in_srgb,var(--c-primary)_18%,transparent)] text-[15px] text-[var(--c-ink)] placeholder:text-[var(--c-muted)] focus:border-[var(--c-primary)] focus:outline-none"
                data-testid="s-12-profile-email"
              />
            </label>
            <label className="flex flex-col gap-[4px]">
              <span className="text-[14px] font-medium text-[var(--c-ink)]">{t('profile.headline', 'Headline')}</span>
              <input
                type="text"
                name="headline"
                value={headline}
                onChange={(e) => setHeadline(e.target.value)}
                className="min-h-[44px] rounded-[var(--radius-md)] border border-[var(--c-hairline-strong)] bg-[var(--c-canvas)] px-[14px] py-[10px] transition-[border-color,box-shadow] duration-150 focus:border-[var(--c-primary)] focus:shadow-[0_0_0_3px_color-mix(in_srgb,var(--c-primary)_18%,transparent)] text-[15px] text-[var(--c-ink)] placeholder:text-[var(--c-muted)] focus:border-[var(--c-primary)] focus:outline-none"
                data-testid="s-12-profile-headline"
              />
            </label>
            <label className="flex flex-col gap-[4px]">
              <span className="text-[14px] font-medium text-[var(--c-ink)]">{t('profile.country', 'Country')}</span>
              <select
                name="country"
                value={country}
                onChange={(e) => setCountry(e.target.value)}
                className="min-h-[44px] rounded-[var(--radius-md)] border border-[var(--c-hairline-strong)] bg-[var(--c-canvas)] px-[14px] py-[10px] transition-[border-color,box-shadow] duration-150 focus:border-[var(--c-primary)] focus:shadow-[0_0_0_3px_color-mix(in_srgb,var(--c-primary)_18%,transparent)] text-[15px] text-[var(--c-ink)] focus:border-[var(--c-primary)] focus:outline-none"
                data-testid="s-12-profile-country"
              >
                {countries.map((c) => (
                  <option key={c.code} value={c.name}>{c.name}</option>
                ))}
              </select>
            </label>
          </div>

          <label className="flex flex-col gap-[4px]">
            <span className="text-[14px] font-medium text-[var(--c-ink)]">{t('profile.bio', 'Bio')}</span>
            <textarea
              name="bio"
              rows={4}
              value={bio}
              onChange={(e) => setBio(e.target.value)}
              className="rounded-[var(--radius-md)] border border-[var(--c-hairline-strong)] bg-[var(--c-canvas)] px-[14px] py-[10px] transition-[border-color,box-shadow] duration-150 focus:border-[var(--c-primary)] focus:shadow-[0_0_0_3px_color-mix(in_srgb,var(--c-primary)_18%,transparent)] text-[15px] text-[var(--c-ink)] placeholder:text-[var(--c-muted)] focus:border-[var(--c-primary)] focus:outline-none"
              data-testid="s-12-profile-bio"
            />
          </label>

          <button
            type="submit"
            disabled={!canSave}
            className="inline-flex min-h-[44px] cursor-pointer items-center justify-center gap-[8px] rounded-[var(--radius-md)] border border-transparent bg-[var(--c-primary)] px-[24px] py-[8px] text-[15px] font-semibold text-[var(--c-on-primary)] hover:bg-[var(--c-primary-active)] disabled:cursor-not-allowed disabled:opacity-50"
            data-testid="s-12-profile-save"
          >
            {saving ? t('profile.saving', 'Saving…') : t('profile.save', 'Save changes')}
          </button>
        </form>

        {/* Account sidebar */}
        <div
          className="sticky top-[88px] space-y-[12px] rounded-[var(--radius-lg)] border border-[var(--c-hairline)] bg-[var(--c-surface)] p-[24px] shadow-[var(--shadow-1)]"
          data-testid="s-12-profile-ac-1"
        >
          <h2 className="text-[20px] font-semibold leading-[1.3] text-[var(--c-ink)]">
            {t('profile.account', 'Account')}
          </h2>

          {loading1 && (
            <div className="space-y-[12px]" data-testid="s-12-profile-ac-1-loading">
              {Array.from({ length: 2 }).map((_, i) => (
                <div key={i} className="h-[40px] w-full et-shimmer rounded-[var(--radius-md)] bg-[var(--c-surface-soft)]" />
              ))}
            </div>
          )}

          {!loading1 && error1 && (
            <div className="space-y-[12px]" data-testid="s-12-profile-ac-1-error">
              <p className="text-[14px] text-[var(--c-error)]">
                {t('profile.loadError', 'We could not load your account. Please try again.')}
              </p>
              <button
                type="button"
                onClick={() => window.location.reload()}
                className="inline-flex min-h-[40px] cursor-pointer items-center justify-center et-press rounded-[var(--radius-pill)] border border-[var(--c-hairline-strong)] bg-[var(--c-surface)] px-[16px] py-[8px] text-[14px] font-semibold text-[var(--c-primary)] hover:bg-[var(--c-surface-soft)]"
                data-testid="s-12-profile-retry"
              >
                {t('profile.retry', 'Try again')}
              </button>
            </div>
          )}

          {!loading1 && !error1 && (
            <>
              <div className="flex flex-col gap-[4px]" data-testid="s-12-profile-stat-enrolled">
                <span className="text-[24px] font-semibold text-[var(--c-ink)]">{enrolledCount}</span>
                <span className="text-[12px] tracking-[0.2px] text-[var(--c-muted)]">
                  {t('profile.enrolledCourses', 'Enrolled courses')}
                </span>
              </div>
              <div className="flex flex-col gap-[4px]" data-testid="s-12-profile-stat-orders">
                <span className="text-[24px] font-semibold text-[var(--c-ink)]">{paidOrders}</span>
                <span className="text-[12px] tracking-[0.2px] text-[var(--c-muted)]">
                  {t('profile.paidOrders', 'Paid orders')}
                </span>
              </div>
            </>
          )}

          <button
            type="button"
            onClick={() => { void signOut(); }}
            className="inline-flex min-h-[44px] w-full cursor-pointer items-center justify-center gap-[8px] rounded-[var(--radius-md)] border border-transparent bg-transparent px-[24px] py-[8px] text-[15px] font-semibold text-[var(--c-body)] hover:bg-[var(--c-surface-soft)]"
            data-testid="s-12-profile-signout"
          >
            {t('profile.signOut', 'Sign out')}
          </button>
        </div>
      </main>

      {/*
        Story acceptance-criteria wiring — preserved per scope-lock. The profile
        editor + Account sidebar above are the on-screen design; these story-spec
        data-testids and the generated PATCH handler are kept accessible-only so
        they survive without duplicating the visible UI.
      */}
      <div className="sr-only" data-testid="s-12-profile-wiring" aria-hidden="true">
        <Link to="/" data-testid="s-12-profile-home-link">{t('profile.home', 'Home')}</Link>

        <section data-testid="s-12-profile-ac-1-kpis">
          {Object.entries(profileRecord).slice(0, 6).map(([key, value]) => (
            <div key={key} data-testid={`s-12-profile-ac-1-kpi-${key}`}>
              <span>{key}</span>
              <span>{typeof value === 'number' || typeof value === 'string' ? String(value) : '-'}</span>
            </div>
          ))}
        </section>

        <section data-testid="s-12-profile-ac-2">
          {/* UpdateUserDto has no title/content; map these scope-locked inputs to the
              real editable profile fields so updateMe2's PATCH stays contract-valid. */}
          <input name="headline" type="text" data-testid="s-12-profile-ac-2-title" />
          <input name="bio" type="text" data-testid="s-12-profile-ac-2-content" />
          <button type="button" onClick={updateMe2} disabled={loading2} data-testid="s-12-profile-ac-2-action">
            {loading2 ? 'Submitting...' : 'Save'}
          </button>
        </section>

        <section data-testid="s-12-profile-ac-3">
          <Link to="/signin" data-testid="s-12-profile-ac-3-link">{t('profile.signOut', 'Sign out')}</Link>
        </section>
      </div>
    </div>
  );
}
