// Generated by scaffold-search-filter-bar — DO NOT EDIT BY HAND. Re-run to refresh.
import { cn } from '~/lib/utils';
import { Button } from '~/components/ui/button';

export interface FilterOption {
  value: string;
  label: string;
}

export interface FilterChipsProps {
  options: FilterOption[];
  selected?: string;
  onChange: (value: string | undefined) => void;
  testId?: string;
}

export function FilterChips({ options, selected, onChange, testId = 'filter-chips' }: FilterChipsProps) {
  return (
    <div className="flex flex-wrap gap-2" data-testid={testId}>
      <Button
        variant={selected ? 'outline' : 'default'}
        size="sm"
        onClick={() => onChange(undefined)}
        data-testid={`${testId}-all`}
      >
        All
      </Button>
      {options.map((o) => (
        <Button
          key={o.value}
          variant={selected === o.value ? 'default' : 'outline'}
          size="sm"
          onClick={() => onChange(o.value)}
          className={cn(selected === o.value && 'shadow-sm')}
          data-testid={`${testId}-${o.value}`}
        >
          {o.label}
        </Button>
      ))}
    </div>
  );
}
