// Generated by scaffold-search-filter-bar — DO NOT EDIT BY HAND. Re-run to refresh.
import { useEffect, useState } from 'react';
import { Search } from 'lucide-react';
import { Input } from '~/components/ui/input';
import { useDebouncedValue } from '~/hooks/useDebouncedValue';

export interface SearchInputProps {
  value?: string;
  placeholder?: string;
  delayMs?: number;
  onDebouncedChange: (value: string) => void;
  testId?: string;
}

export function SearchInput({ value = '', placeholder = 'Search…', delayMs = 300, onDebouncedChange, testId = 'search-input' }: SearchInputProps) {
  const [local, setLocal] = useState(value);
  const debounced = useDebouncedValue(local, delayMs);
  useEffect(() => { onDebouncedChange(debounced); }, [debounced, onDebouncedChange]);
  return (
    <div className="relative w-full max-w-sm">
      <Search className="absolute left-2 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground pointer-events-none" />
      <Input
        value={local}
        onChange={(e) => setLocal(e.target.value)}
        placeholder={placeholder}
        className="pl-8"
        data-testid={testId}
      />
    </div>
  );
}
