/**
 * Generated by scaffold-layouts. Admin role wrapper with sidebar + topbar.
 * Renders <Outlet /> as the page content area. Wire via routes.ts:
 *   layout('components/layouts/AdminLayout.tsx', adminRoutes)
 *
 * RULE-F3 (role-based layout separation): admin gets its own layout
 * distinct from worker/user layouts so role boundaries are clear in code.
 */
import { Outlet, Link, NavLink } from 'react-router';
import { useTranslation } from 'react-i18next';
import { useAppSelector } from '~/hooks/useAppSelector';
import { LanguageToggle } from '~/components/shared/LanguageToggle';
import { user_role } from '~/enums/user-role.enum';
// __NAV_ITEMS_IMPORT__

export default function AdminLayout() {
  const { t } = useTranslation('common');
  const user = useAppSelector((s) => s.auth?.user);
  const roleLabel =
    user?.role === user_role.ADMIN
      ? t('roles.admin', { defaultValue: 'Admin' })
      : user?.role === user_role.INSTRUCTOR
        ? t('roles.instructor', { defaultValue: 'Instructor' })
        : user?.role === user_role.STUDENT
          ? t('roles.student', { defaultValue: 'Student' })
          : '';

  return (
    <div className="flex min-h-screen" data-testid="admin-layout">
      {/* Sidebar */}
      <aside className="hidden md:flex w-64 flex-col bg-card border-r" data-testid="admin-sidebar">
        <div className="p-4 border-b">
          <Link to="/admin" className="block text-xl font-bold" data-testid="admin-sidebar-logo">
            {t('brand.name')}
          </Link>
        </div>
        <nav className="flex-1 p-2 space-y-1" data-testid="admin-sidebar-nav">
          {/* __ADMIN_NAV_ITEMS__ */}
        </nav>
        <div className="p-4 border-t text-sm text-muted-foreground" data-testid="admin-sidebar-user">
          {user?.email ?? t('actions.loading')}
        </div>
      </aside>

      {/* Main area */}
      <div className="flex-1 flex flex-col">
        <header className="h-14 bg-card border-b flex items-center justify-between px-4" data-testid="admin-topbar">
          <button
            className="md:hidden p-2"
            data-testid="admin-topbar-menu"
            aria-label={t('nav.menu')}
          >
            ☰
          </button>
          <div className="flex items-center gap-3">
            <LanguageToggle />
            <span className="text-sm text-muted-foreground" data-testid="admin-topbar-role">
              {/* The role travels as its numeric JWT claim, so rendering it directly put a
                  bare "99" in the console's top bar. Name it. */}
              {roleLabel}
            </span>
          </div>
        </header>

        <main className="flex-1 overflow-y-auto" data-testid="admin-main">
          <Outlet />
        </main>
      </div>
    </div>
  );
}
