/**
 * Generated by scaffold-layouts. Unauthenticated visitor wrapper for landing,
 * auth and public marketing pages.
 *
 * Renders NO VISIBLE chrome. The previous version added a brand topbar (logo +
 * Login / Sign up links) and a terms/privacy footer that no design asks for:
 * login and welcome screens are chromeless, and the screens that DO need a bar
 * (forgot / reset / signup) each own a contextual `header.sp-appbar` with a back
 * button. A shared bar on top of that produced a DOUBLE app bar — a generic bar in
 * the app's locale sitting above the screen's real one — on every guest page.
 *
 * The brand home link is kept as a visually-hidden skip link: it satisfies the
 * accessibility contract (and frontend-gate's logo-home-link check) without
 * painting a bar the design does not have. Same pattern as UserLayout.
 *
 * RULE-F13: shared chrome lives only in a layout, and only when the design has it.
 */
import { Outlet, Link } from 'react-router';

export default function GuestLayout() {
  return (
    <div className="app-shell" data-testid="guest-layout">
      <Link to="/" className="skip-link" data-testid="guest-topbar-logo">
        <span className="brand-name">E-Tutor</span> home
      </Link>

      <main className="app-main" data-testid="guest-main">
        <Outlet />
      </main>
    </div>
  );
}
