/**
 * Generated by scaffold-layouts. User (worker/customer) wrapper with
 * topbar nav + bottom mobile nav. Distinct from AdminLayout — RULE-F3.
 */
import { Outlet, Link, NavLink, useLocation } from 'react-router';
import { useTranslation } from 'react-i18next';
import { useAppSelector } from '~/hooks/useAppSelector';
import { BOTTOMNAV_ROUTES, hasChrome } from '~/components/layouts/design-chrome';

export default function UserLayout() {
  const { t } = useTranslation('common');
  const user = useAppSelector((s) => s.auth?.user);

  return (
    <div className="flex min-h-screen flex-col" data-testid="user-layout">
      <header className="h-14 bg-card border-b flex items-center justify-between px-4" data-testid="user-topbar">
        <Link to="/" className="text-xl font-bold" data-testid="user-topbar-logo">
          {t('brand.name')}
        </Link>
        <nav className="hidden md:flex gap-4" data-testid="user-topbar-nav">
          {/* __USER_NAV_ITEMS__ */}
        </nav>
        <div className="text-sm text-muted-foreground" data-testid="user-topbar-user">
          {user?.email ?? ''}
        </div>
      </header>

      <main className="flex-1" data-testid="user-main">
        <Outlet />
      </main>

      {/* Mobile bottom nav */}
      <nav className="md:hidden h-14 border-t bg-card flex items-center justify-around" data-testid="user-bottom-nav">
        {/* __USER_BOTTOM_NAV_ITEMS__ */}
      </nav>
    </div>
  );
}
