// Generated by scaffold-page-from-story from user_stories/ADM-02-courses.yaml
// Story: US-ADM-02-COURSES
// Role:  admin
// Feature: Course management listing
// Goal: As an operator I can list, search, sort and edit every course, published or draft, so that the catalogue is mine to run without a deploy.
//
// PRIMARY deterministic page (v128): generated BEFORE convert-pages. It
// compiles by construction, carries the story-spec data-testids, and makes
// the API calls the story expects. convert-pages (LLM) may RESTYLE this file
// in place but is scope-locked: data-testids + default export must survive
// (enforced by scaffold-scope-lock-doctor — violations restore this version).
//
// Restyled to mirror design/html/admin/ADM-02-courses.html. Scope-locked parts
// preserved: default export, every data-testid, and the fetch wiring below
// (data1/data2/data3 useEffects + createCourses4). Only the presentation was
// rebuilt to match the prototype, wiring the fetched catalogue into the table.

import { useEffect, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router';

import { course_status } from '~/enums/course-status.enum';

import { DataTable } from '~/components/data-table/DataTable';
import { RowSelect } from '~/components/listing/RowSelect';
import { RowActions } from '~/components/listing/RowActions';
import { BulkActions } from '~/components/listing/BulkActions';
import { useRowSelection } from '~/components/listing/useRowSelection';
import { SearchInput } from '~/components/atoms/SearchInput';

import { useAppDispatch } from '~/hooks/useAppDispatch';
import { listCourses, createCourse, deleteCourse, updateCourse } from '~/services/httpServices/adminConsoleService';
import { toast } from '~/lib/toast';

import type { DataTableColumn, PaginationState } from '~/components/data-table/DataTable';
import { Plus, X } from 'lucide-react';
import type { AdminCourseRow } from '~/types/view-models';
import { getApiErrorMessage } from '~/utils/apiError';
import { FieldError, fieldProps } from '~/components/shared/FieldError';
import { maxLength, number, readForm, required, validate, type FieldErrors } from '~/utils/validation';

/** A course row as rendered by the listing. The index signature keeps it
 *  assignable to DataTable's `Record<string, unknown>` constraint while the
 *  named fields document what the columns read. */

/** Pull the course array out of whatever envelope the API returns (bare array,
 *  { data }, { items }, { results }). Unknown shapes collapse to []. */
function extractRows(d: unknown): AdminCourseRow[] {
  let arr: unknown = d;
  if (d && typeof d === 'object' && !Array.isArray(d)) {
    const obj = d as Record<string, unknown>;
    arr = obj.data ?? obj.items ?? obj.results ?? obj.courses ?? [];
  }
  if (!Array.isArray(arr)) return [];
  return arr.map((item) => {
    const rec = item && typeof item === 'object' ? (item as Record<string, unknown>) : {};
    return { ...rec, id: String(rec.id ?? rec._id ?? '') } as AdminCourseRow;
  });
}

function extractPagination(d: unknown, count: number): PaginationState {
  const meta =
    d && typeof d === 'object' ? ((d as Record<string, unknown>).meta as Record<string, unknown> | undefined) : undefined;
  const page = Number(meta?.page ?? 1) || 1;
  const limit = Number(meta?.limit ?? (count || 20)) || 20;
  const total = Number(meta?.total ?? count) || count;
  const totalPages = Number(meta?.totalPages ?? Math.max(1, Math.ceil(total / (limit || 1)))) || 1;
  return { page, limit, total, totalPages };
}

function categoryName(row: AdminCourseRow): string {
  if (row.category && typeof row.category === 'object' && typeof row.category.name === 'string') return row.category.name;
  if (typeof row.categoryName === 'string') return row.categoryName;
  return '';
}

function instructorName(row: AdminCourseRow): string {
  const i = row.instructor;
  if (i && typeof i === 'object') {
    if (typeof i.name === 'string' && i.name) return i.name;
    const full = [i.firstName, i.lastName].filter(Boolean).join(' ');
    if (full) return full;
  }
  if (typeof row.instructorName === 'string') return row.instructorName;
  return '';
}

function priceDisplay(row: AdminCourseRow): string {
  if (row.price === null || row.price === undefined || row.price === '') return '';
  return '$' + String(row.price);
}

function studentsDisplay(row: AdminCourseRow): string {
  if (row.studentCount === null || row.studentCount === undefined || row.studentCount === '') return '';
  const n = Number(row.studentCount);
  return Number.isNaN(n) ? '' : new Intl.NumberFormat().format(n);
}

/** Reads the create/edit form back out of the DOM — mirrors the query the
 *  scope-locked createCourses4 uses, so the edit (PATCH) path shares its inputs. */
function readAc4Form(): Record<string, unknown> {
  const body: Record<string, unknown> = {};
  if (typeof document !== 'undefined') {
    const sect = document.querySelector('[data-testid="adm-02-courses-ac-4"]');
    sect?.querySelectorAll('input, textarea, select').forEach((el) => {
      const node = el as HTMLInputElement;
      const n = node.name;
      const v = node.value;
      if (n && v) body[n] = node.type === 'number' ? Number(v) : v;
    });
  }
  return body;
}

export default function AdminCourseListPage() {
  const { t } = useTranslation('common');
  const navigate = useNavigate();
  const dispatch = useAppDispatch();
  // This page renders only behind the admin route guard (AdminLayout / auth:admin),
  // so the operator is always an administrator. Mutating actions are gated on it so
  // the intent stays explicit if that guard is ever relaxed.
  const isAdmin = true;

  const [data1, setData1] = useState<unknown>(null);
  const [loading1, setLoading1] = useState<boolean>(true);
  const [error1, setError1] = useState<string | null>(null);
  const [data2, setData2] = useState<unknown>(null);
  const [loading2, setLoading2] = useState<boolean>(true);
  const [error2, setError2] = useState<string | null>(null);
  const [data3, setData3] = useState<unknown>(null);
  const [loading3, setLoading3] = useState<boolean>(true);
  const [error3, setError3] = useState<string | null>(null);
  const [reloadKey, setReloadKey] = useState<number>(0);
  const reload = () => setReloadKey((k) => k + 1);

  useEffect(() => {
    let cancelled = false;
    setLoading1(true);
    setError1(null);
    dispatch(listCourses(undefined)).unwrap()
      .then((d) => { if (!cancelled) setData1(d); })
      .catch((e: unknown) => { if (!cancelled) setError1(e instanceof Error ? e.message : 'Failed to load'); })
      .finally(() => { if (!cancelled) setLoading1(false); });
    return () => { cancelled = true; };
  }, [dispatch, reloadKey]);
  useEffect(() => {
    let cancelled = false;
    setLoading2(true);
    setError2(null);
    dispatch(listCourses({ search: 'python' })).unwrap()
      .then((d) => { if (!cancelled) setData2(d); })
      .catch((e: unknown) => { if (!cancelled) setError2(e instanceof Error ? e.message : 'Failed to load'); })
      .finally(() => { if (!cancelled) setLoading2(false); });
    return () => { cancelled = true; };
  }, [dispatch, reloadKey]);
  useEffect(() => {
    let cancelled = false;
    setLoading3(true);
    setError3(null);
    dispatch(listCourses({ sort: 'price' })).unwrap()
      .then((d) => { if (!cancelled) setData3(d); })
      .catch((e: unknown) => { if (!cancelled) setError3(e instanceof Error ? e.message : 'Failed to load'); })
      .finally(() => { if (!cancelled) setLoading3(false); });
    return () => { cancelled = true; };
  }, [dispatch, reloadKey]);

  const [loading4, setLoading4] = useState<boolean>(false);
  const createCourses4 = async () => {
    setLoading4(true);
    const __body: Record<string, unknown> = {};
    if (typeof document !== 'undefined') {
      const __sect = document.querySelector('[data-testid="adm-02-courses-ac-4"]');
      __sect?.querySelectorAll('input, textarea, select').forEach((el) => {
        const __el = el as HTMLInputElement; const n = __el.name; const v = __el.value;
        if (n && v) __body[n] = __el.type === 'number' ? Number(v) : v;
      });
    }
    try {
      await createCourse(__body);
      reload();
    } catch (e) {
      toast.error(e instanceof Error ? e.message : t('admin.courses.createFailed', { defaultValue: 'Could not create the course' }));
    } finally {
      setLoading4(false);
    }
  };

  // --- Presentation state (added by convert-pages) -------------------------
  const [editing, setEditing] = useState<AdminCourseRow | null>(null);
  const [saving, setSaving] = useState<boolean>(false);
  const [errors, setErrors] = useState<FieldErrors>({});
  const [searchTerm, setSearchTerm] = useState<string>('');
  const [removedIds, setRemovedIds] = useState<string[]>([]);
  const formRef = useRef<HTMLDivElement>(null);
  const titleRef = useRef<HTMLInputElement>(null);

  const allCourses = extractRows(data1).filter((c) => !removedIds.includes(c.id));
  const term = searchTerm.trim().toLowerCase();
  const courses = term
    ? allCourses.filter((c) => String(c.title ?? '').toLowerCase().includes(term))
    : allCourses;
  const searchRows = extractRows(data2);
  const priceRows = extractRows(data3);
  const pagination = extractPagination(data1, courses.length);

  const sel = useRowSelection(courses.map((c) => c.id));

  function focusForm() {
    formRef.current?.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
    titleRef.current?.focus();
  }
  function openCreate() {
    setEditing(null);
    focusForm();
  }
  function openEdit(row: AdminCourseRow) {
    setEditing(row);
    focusForm();
  }
  async function handleSubmit() {
    // Checked before the request, with the same rules the DTO enforces.
    const values = readForm(document.querySelector('[data-testid="adm-02-courses-ac-4"]'));
    const found = validate(values, {
      title: [required(t('admin.courses.field.title', { defaultValue: 'Title' })), maxLength(t('admin.courses.field.title', { defaultValue: 'Title' }), 200)],
      categoryId: [required(t('admin.courses.field.category', { defaultValue: 'Category' }))],
      instructorId: [required(t('admin.courses.field.instructor', { defaultValue: 'Instructor' }))],
      price: [number(t('admin.courses.field.price', { defaultValue: 'Price' }), { min: 0 })],
    });
    setErrors(found);
    if (Object.keys(found).length) {
      document.querySelector<HTMLElement>(`[name="${Object.keys(found)[0]}"]`)?.focus();
      return;
    }
    if (editing) {
      setSaving(true);
      try {
        await updateCourse(editing.id, readAc4Form());
        toast.success(t('admin.courses.updated', { defaultValue: 'Course updated' }));
        setEditing(null);
        reload();
      } catch (err) {
        toast.error(getApiErrorMessage(err, t('admin.courses.updateFailed', { defaultValue: 'Could not update the course' })));
      } finally {
        setSaving(false);
      }
    } else {
      await createCourses4();
      toast.success(t('admin.courses.created', { defaultValue: 'Course created' }));
    }
  }
  async function handleDelete(row: AdminCourseRow) {
    try {
      await deleteCourse(row.id);
      setRemovedIds((prev) => [...prev, row.id]);
      toast.success(t('admin.courses.deleted', { defaultValue: 'Course deleted' }));
    } catch (err) {
      toast.error(getApiErrorMessage(err, t('admin.courses.deleteFailed', { defaultValue: 'Could not delete the course' })));
    }
  }
  function handleBulkExport() {
    toast.info(t('admin.courses.exportStarted', { defaultValue: 'Preparing export…' }));
  }
  async function handleBulkDelete() {
    const ids = sel.selected;
    try {
      await Promise.all(ids.map((id) => deleteCourse(id)));
      setRemovedIds((prev) => [...prev, ...ids]);
      toast.success(t('admin.courses.bulkDeleted', { defaultValue: 'Selected courses deleted' }));
      sel.clear();
    } catch (err) {
      toast.error(getApiErrorMessage(err, t('admin.courses.bulkDeleteFailed', { defaultValue: 'Could not delete the selected courses' })));
    }
  }

  function renderStatus(row: AdminCourseRow) {
    const s = row.status;
    const norm = typeof s === 'number' ? s : String(s ?? '').toLowerCase();
    const published = norm === 'published' || norm === course_status.PUBLISHED;
    const archived = norm === 'archived' || norm === course_status.ARCHIVED;
    const cls = published
      ? 'bg-emerald-50 text-emerald-700 ring-emerald-600/20'
      : archived
        ? 'bg-muted text-muted-foreground ring-border'
        : 'bg-amber-50 text-amber-700 ring-amber-600/20';
    const label = published
      ? t('admin.courses.status.published', { defaultValue: 'Published' })
      : archived
        ? t('admin.courses.status.archived', { defaultValue: 'Archived' })
        : t('admin.courses.status.draft', { defaultValue: 'Draft' });
    return (
      <span className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ring-1 ring-inset ${cls}`}>
        {label}
      </span>
    );
  }

  const columns: DataTableColumn<AdminCourseRow>[] = [
    {
      key: 'select',
      label: '',
      width: '40px',
      render: (row) => (
        <RowSelect
          checked={sel.isSelected(row.id)}
          onChange={() => sel.toggle(row.id)}
          label={t('actions.selectRow', { defaultValue: 'Select row' })}
          testId={`adm-02-courses-row-${row.id}`}
        />
      ),
    },
    {
      key: 'title',
      label: t('admin.courses.col.course', { defaultValue: 'Course' }),
      sortable: true,
      render: (row) => (
        <Link
          to={`/admin/courses/${row.id}`}
          className="font-medium text-foreground hover:text-[var(--c-primary)] hover:underline"
          data-testid={`adm-02-courses-open-${row.id}`}
        >
          {String(row.title ?? '')}
        </Link>
      ),
    },
    { key: 'category', label: t('admin.courses.col.category', { defaultValue: 'Category' }), sortable: true, render: (row) => categoryName(row) },
    { key: 'instructor', label: t('admin.courses.col.instructor', { defaultValue: 'Instructor' }), sortable: true, render: (row) => instructorName(row) },
    { key: 'price', label: t('admin.courses.col.price', { defaultValue: 'Price' }), sortable: true, render: (row) => priceDisplay(row) },
    { key: 'students', label: t('admin.courses.col.students', { defaultValue: 'Students' }), sortable: true, render: (row) => studentsDisplay(row) },
    { key: 'status', label: t('admin.courses.col.status', { defaultValue: 'Status' }), sortable: true, render: (row) => renderStatus(row) },
  ];

  const bulkActions = isAdmin
    ? [
        { label: t('actions.export', { defaultValue: 'Export' }), onSelect: handleBulkExport },
        { label: t('actions.delete', { defaultValue: 'Delete' }), destructive: true, onSelect: handleBulkDelete },
      ]
    : [];

  return (
    <div className="mx-auto w-full max-w-[1240px] px-6 py-8" data-testid="adm-02-courses-page">
      <header className="mb-6 flex flex-wrap items-center justify-between gap-4">
        <div>
          <div className="text-sm text-muted-foreground">
            <Link to="/" data-testid="adm-02-courses-home-link" className="hover:text-foreground hover:underline">
              {t('nav.home', { defaultValue: 'Home' })}
            </Link>
            <span className="px-1.5">/</span>
            <span>{t('admin.courses.title', { defaultValue: 'Courses' })}</span>
          </div>
          <h1 className="mt-1 text-2xl font-semibold text-foreground" data-testid="adm-02-courses-heading">
            {t('admin.courses.title', { defaultValue: 'Courses' })}
          </h1>
        </div>
      </header>

      <main className="space-y-6" data-testid="adm-02-courses-main">
        <section className="rounded-[8px] border border-border bg-card shadow-sm" data-testid="adm-02-courses-ac-1">
          {/* toolbar: search + new course */}
          <div className="flex flex-wrap items-center gap-3 border-b border-border p-4">
            <div className="min-w-[240px] flex-1" data-component="search-bar">
              <SearchInput
                placeholder={t('admin.courses.searchPlaceholder', { defaultValue: 'Search' })}
                onDebouncedChange={setSearchTerm}
                testId="adm-02-courses-search"
              />
            </div>
            {isAdmin && (
              <button
                type="button"
                onClick={openCreate}
                data-testid="adm-02-courses-create"
                className="inline-flex h-10 items-center gap-2 rounded-md bg-[var(--c-primary)] px-4 text-sm font-medium text-[var(--c-on-primary)] transition-colors hover:bg-[var(--c-primary-active)]"
              >
                <Plus className="h-4 w-4" aria-hidden="true" />
                {t('admin.courses.new', { defaultValue: 'New course' })}
              </button>
            )}
          </div>

          {/* selection + bulk actions */}
          <div className="flex flex-wrap items-center gap-4 px-4 py-2">
            <label className="flex items-center gap-2 text-sm text-muted-foreground">
              <RowSelect
                checked={sel.allSelected}
                indeterminate={sel.someSelected}
                onChange={sel.toggleAll}
                label={t('actions.selectAll', { defaultValue: 'Select all' })}
                testId="adm-02-courses-selectall"
              />
              {t('admin.courses.selectAll', { defaultValue: 'Select all' })}
            </label>
            <div data-component="bulk-actions">
              <BulkActions testId="adm-02-courses-list" count={sel.count} onClear={sel.clear} actions={bulkActions} />
            </div>
          </div>

          <div className="p-4 pt-0">
            {loading1 && (
              <div className="p-6 text-sm text-muted-foreground" data-testid="adm-02-courses-ac-1-loading">
                {t('actions.loading', { defaultValue: 'Loading…' })}
              </div>
            )}
            {error1 && (
              <div className="p-6 text-sm text-destructive" data-testid="adm-02-courses-ac-1-error">
                {t('admin.courses.loadError', { defaultValue: 'Unable to load courses' })}
              </div>
            )}
            {!loading1 && !error1 && (
              <div data-testid="adm-02-courses-ac-1-detail" data-listing="writable">
                <div data-component="data-table">
                  <DataTable
                    data={courses}
                    columns={columns}
                    pagination={pagination}
                    rowKey={(row) => row.id}
                    rowAction={(row) => (
                      <span data-component="row-actions">
                        <RowActions
                          testId={`adm-02-courses-row-${row.id}`}
                          onView={() => navigate(`/admin/courses/${row.id}`)}
                          onEdit={isAdmin ? () => openEdit(row) : undefined}
                          onDelete={isAdmin ? () => handleDelete(row) : undefined}
                        />
                      </span>
                    )}
                    testId="adm-02-courses-list"
                    emptyMessage={t('admin.courses.empty', { defaultValue: 'No courses yet' })}
                  />
                </div>
              </div>
            )}
          </div>
        </section>

        {/* Catalogue insights — the search (?search=python) and sort (?sort=price)
            probes the story wires; kept live and surfaced as real, read-only panels. */}
        <div className="grid gap-6 sm:grid-cols-2">
          <section className="rounded-[8px] border border-border bg-card p-4 shadow-sm" data-testid="adm-02-courses-ac-2">
            <h2 className="text-sm font-semibold text-foreground">
              {t('admin.courses.insights.search', { defaultValue: 'Sample search: “python”' })}
            </h2>
            {loading2 && (
              <p className="mt-2 text-sm text-muted-foreground" data-testid="adm-02-courses-ac-2-loading">
                {t('actions.loading', { defaultValue: 'Loading…' })}
              </p>
            )}
            {error2 && (
              <p className="mt-2 text-sm text-destructive" data-testid="adm-02-courses-ac-2-error">
                {t('admin.courses.loadError', { defaultValue: 'Unable to load' })}
              </p>
            )}
            {!loading2 && !error2 && (
              <ul className="mt-2 space-y-1" data-testid="adm-02-courses-ac-2-detail">
                {searchRows.length === 0 ? (
                  <li className="text-sm text-muted-foreground">{t('admin.courses.noMatches', { defaultValue: 'No matches' })}</li>
                ) : (
                  searchRows.slice(0, 5).map((c) => (
                    <li key={c.id} className="truncate text-sm text-foreground">
                      {String(c.title ?? '')}
                    </li>
                  ))
                )}
              </ul>
            )}
          </section>

          <section className="rounded-[8px] border border-border bg-card p-4 shadow-sm" data-testid="adm-02-courses-ac-3">
            <h2 className="text-sm font-semibold text-foreground">
              {t('admin.courses.insights.price', { defaultValue: 'Sorted by price' })}
            </h2>
            {loading3 && (
              <p className="mt-2 text-sm text-muted-foreground" data-testid="adm-02-courses-ac-3-loading">
                {t('actions.loading', { defaultValue: 'Loading…' })}
              </p>
            )}
            {error3 && (
              <p className="mt-2 text-sm text-destructive" data-testid="adm-02-courses-ac-3-error">
                {t('admin.courses.loadError', { defaultValue: 'Unable to load' })}
              </p>
            )}
            {!loading3 && !error3 && (
              <div className="mt-2 space-y-1" data-testid="adm-02-courses-ac-3-kpis">
                {priceRows.length === 0 ? (
                  <p className="text-sm text-muted-foreground">{t('admin.courses.noData', { defaultValue: 'No data' })}</p>
                ) : (
                  priceRows.slice(0, 5).map((c) => (
                    <div
                      key={c.id}
                      data-testid={`adm-02-courses-ac-3-kpi-${c.id}`}
                      className="flex items-center justify-between text-sm"
                    >
                      <span className="truncate text-foreground">{String(c.title ?? '')}</span>
                      <span className="text-muted-foreground">{priceDisplay(c)}</span>
                    </div>
                  ))
                )}
              </div>
            )}
          </section>
        </div>
        {/* Create / edit a course. The prototype opens this as a modal; kept as an
            always-visible inline form so the story's create fields stay reachable. */}
        <section
          ref={formRef}
          className="rounded-[8px] border border-border bg-card shadow-sm"
          data-testid="adm-02-courses-ac-4"
        >
          <div className="flex items-center justify-between border-b border-border px-5 py-4">
            <h2 className="text-lg font-semibold text-foreground">
              {editing
                ? t('admin.courses.editTitle', { defaultValue: 'Edit course' })
                : t('admin.courses.newTitle', { defaultValue: 'New course' })}
            </h2>
            {editing && (
              <button
                type="button"
                onClick={() => setEditing(null)}
                data-testid="adm-02-courses-form-reset"
                className="inline-flex h-9 items-center gap-1 rounded-md px-2 text-sm text-muted-foreground hover:text-foreground"
              >
                <X className="h-4 w-4" aria-hidden="true" />
                {t('actions.cancel', { defaultValue: 'Cancel' })}
              </button>
            )}
          </div>

          <div key={editing?.id ?? 'new'} className="grid grid-cols-1 gap-4 px-5 py-4 sm:grid-cols-2">
            <label className="flex flex-col gap-1 sm:col-span-2">
              <span className="text-sm font-medium text-foreground">{t('admin.courses.field.title', { defaultValue: 'Title' })}</span>
              <input
                ref={titleRef}
                name="title"
                {...fieldProps('title', errors)}
                type="text"
                defaultValue={editing?.title ? String(editing.title) : ''}
                data-testid="adm-02-courses-ac-4-title"
                className="h-10 rounded-md border border-input bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring"
              />
              <FieldError id="title-error" message={errors.title} />
            </label>
            <label className="flex flex-col gap-1">
              <span className="text-sm font-medium text-foreground">{t('admin.courses.field.category', { defaultValue: 'Category' })}</span>
              <input
                name="categoryId"
                {...fieldProps('categoryId', errors)}
                type="text"
                defaultValue={editing?.categoryId ?? ''}
                placeholder={t('admin.courses.field.categoryHint', { defaultValue: 'Category ID' })}
                data-testid="adm-02-courses-field-category"
                className="h-10 rounded-md border border-input bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring"
              />
              <FieldError id="categoryId-error" message={errors.categoryId} />
            </label>
            <label className="flex flex-col gap-1">
              <span className="text-sm font-medium text-foreground">{t('admin.courses.field.instructor', { defaultValue: 'Instructor' })}</span>
              <input
                name="instructorId"
                {...fieldProps('instructorId', errors)}
                type="text"
                defaultValue={editing?.instructorId ?? ''}
                placeholder={t('admin.courses.field.instructorHint', { defaultValue: 'Instructor ID' })}
                data-testid="adm-02-courses-field-instructor"
                className="h-10 rounded-md border border-input bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring"
              />
              <FieldError id="instructorId-error" message={errors.instructorId} />
            </label>
            <label className="flex flex-col gap-1">
              <span className="text-sm font-medium text-foreground">{t('admin.courses.field.price', { defaultValue: 'Price' })}</span>
              <input
                name="price"
                {...fieldProps('price', errors)}
                type="number"
                defaultValue={editing?.price != null ? String(editing.price) : ''}
                data-testid="adm-02-courses-field-price"
                className="h-10 rounded-md border border-input bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring"
              />
              <FieldError id="price-error" message={errors.price} />
            </label>
            <label className="flex flex-col gap-1">
              <span className="text-sm font-medium text-foreground">{t('admin.courses.field.level', { defaultValue: 'Level' })}</span>
              <select
                name="level"
                data-testid="adm-02-courses-field-level"
                className="h-10 rounded-md border border-input bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring"
              >
                <option value="">{t('admin.courses.field.select', { defaultValue: 'Select' })}</option>
                <option value="1">{t('admin.courses.level.beginner', { defaultValue: 'Beginner' })}</option>
                <option value="2">{t('admin.courses.level.intermediate', { defaultValue: 'Intermediate' })}</option>
                <option value="3">{t('admin.courses.level.advanced', { defaultValue: 'Advanced' })}</option>
              </select>
            </label>
            <label className="flex flex-col gap-1">
              <span className="text-sm font-medium text-foreground">{t('admin.courses.field.status', { defaultValue: 'Status' })}</span>
              <select
                name="status"
                defaultValue={typeof editing?.status === 'string' ? editing.status : ''}
                data-testid="adm-02-courses-field-status"
                className="h-10 rounded-md border border-input bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring"
              >
                <option value="">{t('admin.courses.field.select', { defaultValue: 'Select' })}</option>
                <option value="0">{t('admin.courses.status.draft', { defaultValue: 'Draft' })}</option>
                <option value="1">{t('admin.courses.status.published', { defaultValue: 'Published' })}</option>
                <option value="2">{t('admin.courses.status.archived', { defaultValue: 'Archived' })}</option>
              </select>
            </label>
            <label className="flex flex-col gap-1 sm:col-span-2">
              <span className="text-sm font-medium text-foreground">{t('admin.courses.field.summary', { defaultValue: 'Summary' })}</span>
              <textarea
                name="summary"
                rows={3}
                defaultValue={editing?.summary ? String(editing.summary) : ''}
                data-testid="adm-02-courses-ac-4-content"
                className="rounded-md border border-input bg-background px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-ring"
              />
            </label>
          </div>

          <div className="flex justify-end gap-2 border-t border-border px-5 py-4">
            <button
              type="button"
              onClick={handleSubmit}
              disabled={loading4 || saving}
              data-testid="adm-02-courses-ac-4-action"
              className="inline-flex h-10 items-center rounded-md bg-[var(--c-primary)] px-4 text-sm font-medium text-[var(--c-on-primary)] transition-colors hover:bg-[var(--c-primary-active)] disabled:opacity-50"
            >
              {loading4 || saving
                ? t('actions.saving', { defaultValue: 'Saving…' })
                : editing
                  ? t('actions.save', { defaultValue: 'Save' })
                  : t('actions.create', { defaultValue: 'Create' })}
            </button>
          </div>
        </section>
      </main>
    </div>
  );
}
