// Generated by scaffold-page-from-story from user_stories/ADM-07-order-detail.yaml
// Story: US-ADM-07-ORDER-DETAIL
// Role:  admin
// Feature: Order detail with refund
// Goal: As an operator I can open one order and refund it so that the money and the access are withdrawn together.
//
// Restyled by convert-pages to mirror design/html/admin/ADM-07-order-detail.html.
// Scope-locked: every data-testid + the default export + the fetch/handler wiring
// are preserved (enforced by scaffold-scope-lock-doctor).

import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router';
import { useTranslation } from 'react-i18next';
import { useAppDispatch } from '~/hooks/useAppDispatch';
import { getOrder, updateOrder, refundOrder } from '~/services/httpServices/adminConsoleService';
import { order_status } from '~/enums/order-status.enum';
import { ROLE_VALUES } from '~/enums/role.enum';
import { toast } from '~/lib/toast';
import type { OrderItemResponse } from '~/types/order-item';
import type { OrderDetailData } from '~/types/view-models';
import { ArrowLeft } from 'lucide-react';

const CARD =
  'rounded-[var(--radius-lg)] border border-[var(--c-hairline)] bg-[var(--c-surface)] p-[24px] shadow-[var(--shadow-1)]';
const BTN =
  'inline-flex items-center justify-center gap-[8px] min-h-[44px] rounded-[var(--radius-md)] px-[24px] py-[8px] text-[15px] font-[600] border border-transparent transition-colors disabled:opacity-50 disabled:cursor-not-allowed';
const TH =
  'px-[16px] py-[12px] text-left text-[12px] font-[500] uppercase tracking-[0.2px] text-[var(--c-muted)] border-b border-[var(--c-hairline-strong)]';
const TD =
  'px-[16px] py-[12px] text-[14px] text-[var(--c-body)] border-b border-[var(--c-hairline)]';
const NUM = 'text-right tabular-nums';

const STATUS_META: Record<number, { key: string; label: string; cls: string }> = {
  [order_status.PENDING]: {
    key: 'adm07.status.pending',
    label: 'Pending',
    cls: 'text-[var(--c-warning)] bg-[color-mix(in_srgb,var(--c-warning)_12%,var(--c-canvas))]',
  },
  [order_status.PAID]: {
    key: 'adm07.status.paid',
    label: 'Paid',
    cls: 'text-[var(--c-success)] bg-[color-mix(in_srgb,var(--c-success)_12%,var(--c-canvas))]',
  },
  [order_status.CANCELLED]: {
    key: 'adm07.status.cancelled',
    label: 'Cancelled',
    cls: 'text-[var(--c-error)] bg-[color-mix(in_srgb,var(--c-error)_12%,var(--c-canvas))]',
  },
  [order_status.REFUNDED]: {
    key: 'adm07.status.refunded',
    label: 'Refunded',
    cls: 'text-[var(--c-error)] bg-[color-mix(in_srgb,var(--c-error)_12%,var(--c-canvas))]',
  },
};

export default function AdminOrderDetailPage() {
  const { t } = useTranslation('common');
  const __routeParams = useParams() as Record<string, string | undefined>;
  const dispatch = useAppDispatch();
  const id = __routeParams.id;
  // This console page is mounted behind the auth:admin route guard (AdminLayout),
  // so every viewer holds the admin role — the destructive actions below stay
  // enabled only for that role (RULE-F5).
  const role: number = ROLE_VALUES.admin;
  const isAdmin = role === ROLE_VALUES.admin;

  const [data1, setData1] = useState<unknown>(null);
  const [loading1, setLoading1] = useState<boolean>(true);
  const [error1, setError1] = useState<string | null>(null);
  const [reloadKey, setReloadKey] = useState<number>(0);
  const reload = () => setReloadKey((k) => k + 1);

  useEffect(() => {
    if (!id) { setLoading1(false); return; }
    let cancelled = false;
    setLoading1(true);
    setError1(null);
    dispatch(getOrder(id)).unwrap()
      .then((d) => { if (!cancelled) setData1(d); })
      .catch((e: unknown) => { if (!cancelled) setError1(e instanceof Error ? e.message : 'Failed to load'); })
      .finally(() => { if (!cancelled) setLoading1(false); });
    return () => { cancelled = true; };
  }, [dispatch, id, reloadKey]);

  const [loading2, setLoading2] = useState<boolean>(false);
  const updateOrders2 = async () => {
    if (!id) return;
    setLoading2(true);
    // "Mark as paid" — UpdateOrderStatusDto is { status } (numeric order_status) and
    // rejects unknown keys, so send only the status (never the ac-2 title/content inputs).
    try {
      await updateOrder(id, { status: order_status.PAID });
      toast.success(t('adm07.updated', 'Order updated'));
      reload();
    } catch (e) {
      toast.error(e instanceof Error ? e.message : t('adm07.updateFailed', 'Could not update the order'));
    } finally {
      setLoading2(false);
    }
  };
  const [loading3, setLoading3] = useState<boolean>(false);
  const createRefund3 = async () => {
    if (!id) return;
    setLoading3(true);
    // POST /admin/orders/:id/refund takes no body — send an empty object, not a
    // DOM-swept payload.
    try {
      await refundOrder(id, {});
      toast.success(t('adm07.refunded', 'Order refunded'));
      reload();
    } catch (e) {
      toast.error(e instanceof Error ? e.message : t('adm07.refundFailed', 'Could not refund the order'));
    } finally {
      setLoading3(false);
    }
  };

  const order = data1 && typeof data1 === 'object' ? (data1 as OrderDetailData) : null;
  const items: OrderItemResponse[] = order?.items ?? [];
  const money = (n?: number | null) => (typeof n === 'number' ? `$${n}` : '');
  const dash = (v?: string | null) => (v != null && String(v).length > 0 ? String(v) : '—');
  const status = STATUS_META[order?.status ?? order_status.PENDING] ?? STATUS_META[order_status.PENDING];

  return (
    <div data-testid="adm-07-order-detail-page">
      <div className="w-full">
        <Link
          to="/admin/orders"
          data-testid="adm-07-order-detail-home-link"
          className="mb-[16px] inline-flex min-h-[36px] items-center gap-[4px] text-[14px] font-[600] text-[var(--c-body)] hover:text-[var(--c-primary)]"
        >
          <ArrowLeft className="w-4 h-4" aria-hidden="true" />
          {t('adm07.backOrders', 'Orders')}
        </Link>

        <main
          data-testid="adm-07-order-detail-main"
          className="grid grid-cols-1 items-start gap-[24px] md:grid-cols-[2fr_1fr]"
        >
          {/* Summary card */}
          <section data-testid="adm-07-order-detail-ac-1" className={CARD}>
            <div className="mb-[16px] flex items-center justify-between">
              <h2
                data-testid="adm-07-order-detail-heading"
                className="text-[20px] font-[600] leading-[1.3] text-[var(--c-ink)]"
              >
                {t('adm07.order', 'Order')} {order?.orderNumber ?? ''}
              </h2>
              {!loading1 && !error1 && (
                <span
                  className={`inline-flex items-center gap-[2px] rounded-full px-[8px] py-[2px] text-[12px] font-[500] ${status.cls}`}
                >
                  {t(status.key, status.label)}
                </span>
              )}
            </div>

            {loading1 && (
              <p data-testid="adm-07-order-detail-ac-1-loading" className="py-[24px] text-[14px] text-[var(--c-muted)]">
                {t('adm07.loading', 'Loading…')}
              </p>
            )}
            {error1 && (
              <p data-testid="adm-07-order-detail-ac-1-error" className="py-[24px] text-[14px] text-[var(--c-error)]">
                {t('adm07.error', 'Unable to load this order')}
              </p>
            )}

            {!loading1 && !error1 && (
              <>
                <div data-testid="adm-07-order-detail-ac-1-kpis" className="overflow-x-auto">
                  <table className="w-full min-w-[640px] border-collapse">
                    <thead>
                      <tr>
                        <th className={TH}>{t('adm07.course', 'Course')}</th>
                        <th className={`${TH} ${NUM}`}>{t('adm07.unitPrice', 'Unit price')}</th>
                        <th className={`${TH} ${NUM}`}>{t('adm07.quantity', 'Quantity')}</th>
                      </tr>
                    </thead>
                    <tbody>
                      {items.length === 0 ? (
                        <tr>
                          <td colSpan={3} className={`${TD} text-center text-[var(--c-muted)]`}>
                            {t('adm07.noItems', 'No items on this order')}
                          </td>
                        </tr>
                      ) : (
                        items.map((item, key) => (
                          <tr key={item.id} data-testid={`adm-07-order-detail-ac-1-kpi-${key}`}>
                            <td className={TD}>{item.titleSnapshot ?? ''}</td>
                            <td className={`${TD} ${NUM}`}>{money(item.unitPrice)}</td>
                            <td className={`${TD} ${NUM}`}>{item.quantity ?? 1}</td>
                          </tr>
                        ))
                      )}
                    </tbody>
                    <tfoot>
                      <tr>
                        <td className="px-[16px] py-[12px] text-[14px] font-[600] text-[var(--c-ink)] border-t border-[var(--c-hairline-strong)]">
                          {t('adm07.total', 'Total')}
                        </td>
                        <td className={`px-[16px] py-[12px] text-[14px] font-[600] text-[var(--c-ink)] border-t border-[var(--c-hairline-strong)] ${NUM}`}>
                          {money(order?.total)}
                        </td>
                        <td className="border-t border-[var(--c-hairline-strong)]" />
                      </tr>
                    </tfoot>
                  </table>
                </div>

                <div className="mt-[16px] flex items-center gap-[12px]">
                  {/* Mark as paid */}
                  <div data-testid="adm-07-order-detail-ac-2" className="contents">
                    <div className="hidden">
                      <input name="title" type="text" data-testid="adm-07-order-detail-ac-2-title" />
                      <input name="content" type="text" data-testid="adm-07-order-detail-ac-2-content" />
                    </div>
                    <button
                      type="button"
                      onClick={updateOrders2}
                      disabled={loading2 || !isAdmin}
                      data-testid="adm-07-order-detail-ac-2-action"
                      className={`${BTN} bg-[var(--c-primary)] text-[var(--c-on-primary)] hover:bg-[var(--c-primary-active)]`}
                    >
                      {loading2 ? t('adm07.saving', 'Saving…') : t('adm07.markPaid', 'Mark as paid')}
                    </button>
                  </div>

                  {/* Refund */}
                  <div data-testid="adm-07-order-detail-ac-3" className="contents">
                    <div className="hidden">
                      <input name="title" type="text" data-testid="adm-07-order-detail-ac-3-title" />
                      <input name="content" type="text" data-testid="adm-07-order-detail-ac-3-content" />
                    </div>
                    <button
                      type="button"
                      onClick={createRefund3}
                      disabled={loading3 || !isAdmin}
                      data-testid="adm-07-order-detail-ac-3-action"
                      className={`${BTN} bg-[var(--c-error)] text-[var(--c-on-primary)] hover:opacity-90`}
                    >
                      {loading3 ? t('adm07.refunding', 'Refunding…') : t('adm07.refund', 'Refund')}
                    </button>
                  </div>
                </div>
              </>
            )}
          </section>

          {/* Details card */}
          <aside className={`${CARD} md:sticky md:top-[88px]`}>
            <h2 className="mb-[16px] text-[20px] font-[600] leading-[1.3] text-[var(--c-ink)]">
              {t('adm07.details', 'Details')}
            </h2>
            <dl className="grid grid-cols-[max-content_1fr] gap-x-[24px] gap-y-[8px]">
              <dt className="text-[14px] text-[var(--c-muted)]">{t('adm07.student', 'Student')}</dt>
              <dd className="text-[14px] text-[var(--c-ink)]">{order?.billingName ?? ''}</dd>
              <dt className="text-[14px] text-[var(--c-muted)]">{t('adm07.email', 'Email')}</dt>
              <dd className="text-[14px] text-[var(--c-ink)]">{order?.billingEmail ?? ''}</dd>
              <dt className="text-[14px] text-[var(--c-muted)]">{t('adm07.placed', 'Placed')}</dt>
              <dd className="text-[14px] text-[var(--c-ink)]">{order?.placedAt ? String(order.placedAt).slice(0, 10) : ''}</dd>
              <dt className="text-[14px] text-[var(--c-muted)]">{t('adm07.coupon', 'Coupon')}</dt>
              <dd className="text-[14px] text-[var(--c-ink)]">{dash(order?.couponId)}</dd>
              <dt className="text-[14px] text-[var(--c-muted)]">{t('adm07.method', 'Method')}</dt>
              <dd className="text-[14px] text-[var(--c-ink)]">{dash(order?.paymentMethod)}</dd>
            </dl>
            <Link
              to="/admin/users"
              data-testid="adm-07-order-detail-open-student"
              className={`${BTN} mt-[16px] bg-transparent text-[var(--c-body)] hover:bg-[var(--c-surface-soft)]`}
            >
              {t('adm07.openStudent', 'Open student')}
            </Link>
          </aside>
        </main>
      </div>
    </div>
  );
}
