// Generated by scaffold-page-from-story from user_stories/ADM-00-login.yaml
// Story: US-ADM-00-LOGIN
// Role:  admin
// Feature: Admin console sign-in
// Goal: As an operator I can sign in to the console so that I can manage the catalogue and the orders.
//
// Restyled by convert-pages to mirror design/html/admin/ADM-00-login.html
// (a single centered auth card: brand → heading → email → password → Sign in).
// Scope-locked parts preserved: all data-testids, the default export
// (AdminLoginPage), and the data wiring + loading/error/empty branches.

import { useEffect, useState, type FormEvent } from "react";
import { Link, useNavigate } from "react-router";
import { useTranslation } from "react-i18next";
import { useAppDispatch } from "~/hooks/useAppDispatch";
import { loginThunk } from "~/services/httpServices/authService";
import { getStats } from "~/services/httpServices/adminConsoleService";
import { Button } from "~/components/ui/button";
import { Input } from "~/components/ui/input";
import { Label } from "~/components/ui/label";
import { toast } from "~/lib/toast";
import { GraduationCap } from "lucide-react";
import { FieldError, fieldProps } from '~/components/shared/FieldError';
import { email as emailRule, required, serverFieldErrors, validate, type FieldErrors } from '~/utils/validation';
import { AuthPanel } from '~/components/shared/AuthPanel';

export default function AdminLoginPage() {
  const { t } = useTranslation();
  const dispatch = useAppDispatch();
  const navigate = useNavigate();

  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [submitting, setSubmitting] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [errors, setErrors] = useState<FieldErrors>({});

  // POST /api/auth/login → session (design write; feedback: toast).
  async function onSubmit(e: FormEvent) {
    e.preventDefault();
    // `required` on the inputs gets the browser's own bubble, which is not
    // styled like anything else here and says "Please fill out this field".
    // Same rules as the API, shown the same way as every other form.
    const found = validate({ email, password }, {
      email: [required(t('auth:login.emailLabel', 'Email')), emailRule()],
      password: [required(t('auth:login.passwordLabel', 'Password'))],
    });
    setErrors(found);
    if (Object.keys(found).length) {
      document.querySelector<HTMLElement>(`[name="${Object.keys(found)[0]}"]`)?.focus();
      return;
    }
    setSubmitting(true);
    setError(null);
    const result = await dispatch(loginThunk({ email, password }));
    setSubmitting(false);
    if (loginThunk.fulfilled.match(result)) {
      toast.success(t("auth:login.success", "Signed in"));
      // Not '/': that route redirects here-ward through the console front door,
      // and before it existed it was a blank page — so a correct password landed
      // on an empty white screen.
      navigate("/admin");
    } else {
      setError(t("auth:login.failure", "Could not sign you in"));
      toast.error(t("auth:login.failure", "Could not sign you in"));
    }
  }

  // Console stats wiring (kept per scope-lock; the login design shows no
  // dashboard, so the section renders hidden while its data branches survive).
  const [stats, setStats] = useState<unknown>(null);
  const [statsLoading, setStatsLoading] = useState<boolean>(true);
  const [statsError, setStatsError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    setStatsLoading(true);
    setStatsError(null);
    dispatch(getStats())
      .unwrap()
      .then((d) => {
        if (!cancelled) setStats(d);
      })
      .catch((err) => {
        if (!cancelled)
          setStatsError(err instanceof Error ? err.message : "Unable to load");
      })
      .finally(() => {
        if (!cancelled) setStatsLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [dispatch]);

  return (
    // The page owns its own centring. It used to rely on the root shell's
    // `container mx-auto`, and when the console chrome moved out of that shell
    // the form had nothing constraining it: a 1440px-wide card pinned to the top
    // left corner with the rest of the window empty below it.
    <main className="grid min-h-screen grid-cols-1 items-center gap-[24px] bg-muted/30 px-[16px] py-[32px] sm:px-[32px] lg:grid-cols-[1.05fr_1fr] lg:gap-[40px] lg:px-[64px]">
      <AuthPanel
        brand={t('brand.name', 'E-Tutor')}
        homeHref="/admin/login"
        title={t('auth:login.panelTitle', 'Run the catalogue from one place.')}
        points={[
          t('auth:login.panelPoint1', 'Courses, categories and instructors'),
          t('auth:login.panelPoint2', 'Orders, coupons and revenue at a glance'),
          t('auth:login.panelPoint3', 'Every enrolment and how far it has come'),
        ]}
      />
      <form
        onSubmit={onSubmit}
        className="mx-auto flex w-full max-w-[440px] flex-col gap-[16px] rounded-[var(--radius-xl)] border bg-card p-[28px] shadow-[var(--shadow-2)]"
        data-testid="adm-00-login-page"
      >
        <Link
          to="/"
          className="inline-flex items-center gap-[8px] text-foreground no-underline"
          data-testid="adm-00-login-home-link"
        >
          <span className="inline-flex h-8 w-8 items-center justify-center rounded-[var(--radius-md)] bg-primary text-primary-foreground">
            <GraduationCap className="h-5 w-5" aria-hidden="true" />
          </span>
          <span className="text-[20px] font-bold tracking-[-0.2px]">
            {t("brand.name", "E-Tutor")}
          </span>
        </Link>

        <h1
          className="text-[24px] font-semibold leading-[1.25] tracking-[-0.2px] text-foreground"
          data-testid="adm-00-login-heading"
        >
          {t("auth:login.adminTitle", "Admin sign in")}
        </h1>

        <div
          className="flex flex-col gap-[16px]"
          data-testid="adm-00-login-main"
        >
          <div
            className="flex flex-col gap-[16px]"
            data-testid="adm-00-login-ac-1"
          >
            <div className="flex flex-col gap-[4px]">
              <Label htmlFor="adm-login-email">
                {t("auth:login.emailLabel", "Email")}
              </Label>
              <Input
                id="adm-login-email"
                name="email"
                type="email"
                autoComplete="email"
                placeholder={t(
                  "auth:login.adminEmailPlaceholder",
                  "admin@etutor.test",
                )}
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                {...fieldProps('email', errors)}
                data-testid="adm-00-login-ac-1-email"
              />
              <FieldError id="email-error" message={errors.email} />
            </div>

            <div className="flex flex-col gap-[4px]">
              <Label htmlFor="adm-login-password">
                {t("auth:login.passwordLabel", "Password")}
              </Label>
              <Input
                id="adm-login-password"
                name="password"
                type="password"
                autoComplete="current-password"
                placeholder={t(
                  "auth:login.adminPasswordPlaceholder",
                  "Your password",
                )}
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                {...fieldProps('password', errors)}
                data-testid="adm-00-login-ac-1-password"
              />
              <FieldError id="password-error" message={errors.password} />
            </div>

            {error && (
              <p
                className="text-[13px] text-destructive"
                data-testid="adm-00-login-error"
              >
                {error}
              </p>
            )}

            <Button
              type="submit"
              size="lg"
              disabled={submitting}
              className="w-full"
              data-testid="adm-00-login-ac-1-action"
            >
              {submitting
                ? t("actions.loading", "Loading...")
                : t("auth:login.submitButton", "Sign in")}
            </Button>
          </div>

          {/* Console stats — data wiring preserved (scope-lock); hidden on the sign-in surface. */}
          <div
            className="hidden"
            aria-hidden="true"
            data-testid="adm-00-login-ac-2"
          >
            {statsLoading && (
              <p data-testid="adm-00-login-ac-2-loading">
                {t("actions.loading", "Loading...")}
              </p>
            )}
            {statsError && (
              <p
                className="text-destructive"
                data-testid="adm-00-login-ac-2-error"
              >
                {t("empty.error", "Unable to load")}
              </p>
            )}
            {!statsLoading && !statsError && (
              <div
                className="grid grid-cols-1 gap-4 sm:grid-cols-3"
                data-testid="adm-00-login-ac-2-kpis"
              >
                {Object.entries(
                  stats && typeof stats === "object"
                    ? (stats as Record<string, unknown>)
                    : {},
                )
                  .slice(0, 6)
                  .map(([key, value]) => (
                    <div
                      key={key}
                      data-testid={`adm-00-login-ac-2-kpi-${key}`}
                      className="rounded bg-muted p-3"
                    >
                      <p className="text-xs text-muted-foreground">{key}</p>
                      <p className="text-2xl font-bold">
                        {typeof value === "number" || typeof value === "string"
                          ? String(value)
                          : "-"}
                      </p>
                    </div>
                  ))}
              </div>
            )}
          </div>
        </div>
      </form>
    </main>
  );
}
