// Generated by scaffold-page-from-story from user_stories/ADM-08-enrollments.yaml
// Story: US-ADM-08-ENROLLMENTS
// Role:  admin
// Feature: Enrollment monitoring (read-only)
// Goal: As an operator I can see who is enrolled in what and how far they have got so that I can answer a support question without touching the data.
//
// Restyled by convert-pages to mirror design/html/admin/ADM-08-enrollments.html.
// Scope-locked: every data-testid + the default export + the fetch/loading/error
// wiring are preserved (enforced by scaffold-scope-lock-doctor).

import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useAppDispatch } from '~/hooks/useAppDispatch';
import { listEnrollments } from '~/services/httpServices/adminConsoleService';
import { enrollment_status } from '~/enums/enrollment-status.enum';
import { ROLE_VALUES } from '~/enums/role.enum';
import { SearchInput } from '~/components/atoms/SearchInput';
import { ChevronDown } from 'lucide-react';
import type { EnrollmentListResponse, EnrollmentRow } from '~/types/view-models';
import { PageHeading } from '~/components/shared/Placeholder';
import { formatDate } from '~/utils/date';


const CARD =
  'rounded-[var(--radius-lg)] border border-[var(--c-hairline)] bg-[var(--c-surface)] p-[24px] shadow-[var(--shadow-1)]';
const TH =
  'px-[16px] py-[12px] text-left text-[12px] font-[500] uppercase tracking-[0.2px] text-[var(--c-muted)] border-b border-[var(--c-hairline-strong)]';
const TD =
  'px-[16px] py-[12px] text-[14px] text-[var(--c-body)] border-b border-[var(--c-hairline)]';
const NUM = 'text-right tabular-nums';

const STATUS_META: Record<number, { key: string; label: string; cls: string }> = {
  [enrollment_status.ACTIVE]: {
    key: 'adm08.status.active',
    label: 'Active',
    cls: 'bg-[var(--c-primary-soft)] text-[var(--c-primary)]',
  },
  [enrollment_status.COMPLETED]: {
    key: 'adm08.status.completed',
    label: 'Completed',
    cls: 'bg-[color-mix(in_srgb,var(--c-success)_12%,var(--c-canvas))] text-[var(--c-success)]',
  },
  [enrollment_status.CANCELLED]: {
    key: 'adm08.status.cancelled',
    label: 'Cancelled',
    cls: 'bg-[var(--c-surface-soft)] text-[var(--c-body)]',
  },
};

const COLUMNS: { key: string; label: string; num?: boolean }[] = [
  { key: 'student', label: 'Student' },
  { key: 'course', label: 'Course' },
  { key: 'progress', label: 'Progress', num: true },
  { key: 'status', label: 'Status' },
  { key: 'enrolledAt', label: 'Enrolled' },
];

export default function AdminEnrollmentListPage() {
  const { t } = useTranslation('common');
  const dispatch = useAppDispatch();
  // Mounted behind the auth:admin route guard (AdminLayout), so every viewer
  // holds the admin role — the console read below runs only for that role (RULE-F5).
  const role: number = ROLE_VALUES.admin;
  const isAdmin = role === ROLE_VALUES.admin;

  const [rows, setRows] = useState<EnrollmentRow[]>([]);
  const [total, setTotal] = useState<number>(0);
  const [search, setSearch] = useState<string>('');
  const [sort, setSort] = useState<string>('');
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!isAdmin) return;
    let cancelled = false;
    setLoading(true);
    setError(null);
    const query: Record<string, unknown> = {};
    if (search) query.search = search;
    if (sort) query.sort = sort;
    dispatch(listEnrollments(query)).unwrap()
      .then((d: unknown) => {
        if (cancelled) return;
        const body = d && typeof d === 'object' ? (d as EnrollmentListResponse) : null;
        setRows(Array.isArray(body?.items) ? (body as EnrollmentListResponse).items : []);
        setTotal(typeof body?.meta?.total === 'number' ? (body as EnrollmentListResponse).meta.total : 0);
      })
      .catch((e: unknown) => { if (!cancelled) setError(e instanceof Error ? e.message : 'Failed to load'); })
      .finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [dispatch, search, sort, isAdmin]);

  const searchActive = search.trim().length > 0;
  const sortActive = sort.length > 0;
  const isEmpty = !loading && !error && rows.length === 0;

  const onSearch = (value: string) => setSearch(value);
  const onSort = (key: string) => setSort((prev) => (prev === key ? '' : key));

  const fmtProgress = (v: number | null | undefined) => (typeof v === 'number' ? `${v}%` : '');
  const fmtDate = (v: string | null | undefined) => formatDate(v);
  const statusMeta = (s: enrollment_status | null | undefined) =>
    s != null && STATUS_META[s] ? STATUS_META[s] : null;

  return (
    <div data-testid="adm-08-enrollments-page">
      <div className="w-full">
        <PageHeading
        eyebrow={t("admin.enrollments.eyebrow", { defaultValue: "Learning" })}
        title={t("admin.enrollments.title", { defaultValue: "Enrolments" })}
        hint={t("admin.enrollments.hint", { defaultValue: "Who has access to what, and how far they are." })}
        testId="adm-08-enrollments-heading"
      />

        <main data-testid="adm-08-enrollments-main">
          <section data-testid="adm-08-enrollments-ac-1" className={CARD}>
            {/* Toolbar — search (AC2: admin searches by course/student) */}
            <div
              data-testid="adm-08-enrollments-ac-2"
              className="mb-[16px] flex flex-wrap items-center gap-[12px]"
            >
              <SearchInput
                value={search}
                placeholder={t('adm08.searchPlaceholder', 'Search')}
                onDebouncedChange={onSearch}
                testId="enrollments-search"
              />
              <span className="flex-1" />
              {searchActive && loading && (
                <span data-testid="adm-08-enrollments-ac-2-loading" className="text-[12px] text-[var(--c-muted)]">
                  {t('adm08.searching', 'Searching…')}
                </span>
              )}
              {searchActive && !loading && error && (
                <span data-testid="adm-08-enrollments-ac-2-error" className="text-[12px] text-[var(--c-error)]">
                  {t('adm08.error', 'Unable to load enrollments')}
                </span>
              )}
              {searchActive && !loading && !error && (
                <span data-testid="adm-08-enrollments-ac-2-detail" className="text-[12px] text-[var(--c-muted)]">
                  {total} {t('adm08.results', 'results')}
                </span>
              )}
            </div>

            {/* Sort status (AC3: admin sorts by progress) */}
            {sortActive && (
              <div className="mb-[12px] flex items-center gap-[8px]">
                {loading && (
                  <span data-testid="adm-08-enrollments-ac-3-loading" className="text-[12px] text-[var(--c-muted)]">
                    {t('adm08.sorting', 'Sorting…')}
                  </span>
                )}
                {!loading && error && (
                  <span data-testid="adm-08-enrollments-ac-3-error" className="text-[12px] text-[var(--c-error)]">
                    {t('adm08.error', 'Unable to load enrollments')}
                  </span>
                )}
                {!loading && !error && (
                  <span data-testid="adm-08-enrollments-ac-3-detail" className="text-[12px] text-[var(--c-muted)]">
                    {t('adm08.sortedBy', 'Sorted by')} {sort}
                  </span>
                )}
              </div>
            )}

            <div className="w-full min-w-0 overflow-x-auto">
              <table data-testid="adm-08-enrollments-ac-3" className="w-full min-w-[640px] border-collapse">
                <thead>
                  <tr>
                    {COLUMNS.map((col) => {
                      const active = sort === col.key;
                      return (
                        <th
                          key={col.key}
                          scope="col"
                          aria-sort={active ? 'descending' : undefined}
                          onClick={() => onSort(col.key)}
                          data-testid={`adm-08-enrollments-sort-${col.key}`}
                          className={`${TH} ${col.num ? NUM : ''} cursor-pointer select-none whitespace-nowrap ${active ? 'text-[var(--c-ink)]' : ''}`}
                        >
                          {t(`adm08.col.${col.key}`, col.label)}{' '}
                          <ChevronDown className="inline-block w-4 h-4 align-[-0.18em] opacity-50" aria-hidden="true" />
                        </th>
                      );
                    })}
                  </tr>
                </thead>
                <tbody data-testid="adm-08-enrollments-ac-1-kpis">
                  {loading && (
                    <tr data-testid="adm-08-enrollments-ac-1-loading">
                      <td colSpan={COLUMNS.length} className={`${TD} text-center text-[var(--c-muted)]`}>
                        {t('adm08.loading', 'Loading…')}
                      </td>
                    </tr>
                  )}
                  {!loading && error && (
                    <tr data-testid="adm-08-enrollments-ac-1-error">
                      <td colSpan={COLUMNS.length} className={`${TD} text-center text-[var(--c-error)]`}>
                        {t('adm08.error', 'Unable to load enrollments')}
                      </td>
                    </tr>
                  )}
                  {isEmpty && (
                    <tr>
                      <td colSpan={COLUMNS.length} className={`${TD} py-[40px] text-center text-[var(--c-muted)]`}>
                        {t('adm08.empty', 'No enrollments found')}
                      </td>
                    </tr>
                  )}
                  {!loading && !error && rows.map((row) => {
                    const meta = statusMeta(row.status);
                    return (
                      <tr
                        key={row.id}
                        data-testid={`adm-08-enrollments-row-${row.id}`}
                        className="hover:bg-[var(--c-surface-soft)]"
                      >
                        <td className={TD}>{row.student ?? ''}</td>
                        <td className={TD}>{row.course ?? ''}</td>
                        <td className={`${TD} ${NUM}`}>{fmtProgress(row.progressPercent)}</td>
                        <td className={TD}>
                          {meta && (
                            <span className={`inline-flex items-center gap-[2px] rounded-full px-[8px] py-[2px] text-[12px] font-[500] ${meta.cls}`}>
                              {t(meta.key, meta.label)}
                            </span>
                          )}
                        </td>
                        <td className={TD}>{fmtDate(row.enrolledAt)}</td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </section>

        </main>
      </div>
    </div>
  );
}
