// Generated by scaffold-dto-from-entity — DO NOT EDIT BY HAND. Re-run if entity changes.
import { IsOptional, IsString, IsNumber, IsBoolean, IsEnum, IsEmail, IsDateString, IsArray, IsObject, IsUUID } from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export class CreateLessonProgressDto {
  @ApiProperty()
  @IsUUID()
  enrollmentId!: string;

  @ApiProperty()
  @IsUUID()
  lessonId!: string;

  @ApiPropertyOptional()
  @IsOptional() @IsBoolean()
  isCompleted?: boolean;

  @ApiPropertyOptional()
  @IsOptional() @IsNumber()
  watchedSeconds?: number;

  @ApiPropertyOptional()
  @IsOptional() @IsDateString()
  completedAt?: Date;

}

export type CreateLessonProgressRequest = CreateLessonProgressDto;
