// Generated by scaffold-dto-from-entity — DO NOT EDIT BY HAND. Re-run if entity changes.
import { PartialType } from '@nestjs/swagger';
import { CreateLessonProgressDto } from './create-lesson-progress.dto';

export class UpdateLessonProgressDto extends PartialType(CreateLessonProgressDto) {}

export type UpdateLessonProgressRequest = UpdateLessonProgressDto;
