// Generated by scaffold-enum-sync — DO NOT EDIT BY HAND. Re-run if backend enum changes.

/**
 * discount_type — generated by scaffold-enums-from-spec from PROJECT_DATABASE.md.
 */
export enum discount_type {
  PERCENT = 1,
  FIXED = 2,
}
