/**
 * Generated by scaffold-entities from PROJECT_DATABASE.md table `course_sections`.
 * Edits to this file are preserved across re-runs ONLY when the table
 * definition is unchanged; otherwise re-run with --force to regenerate.
 */
import { Column, Entity, JoinColumn, ManyToOne } from 'typeorm';
import { BaseEntity } from '../../core/base/base.entity';
import { Course } from '../course/course.entity';

@Entity('course_sections')
export class CourseSection extends BaseEntity {
  @Column({ name: 'course_id', type: 'uuid' })
  courseId!: string;

  @Column({ type: 'varchar', length: 200 })
  title!: string;

  @Column({ type: 'varchar', length: 300, nullable: true })
  summary?: string;

  @Column({ name: 'display_order', type: 'int', default: 0 })
  displayOrder!: number;

  // ── Relations ──

  @ManyToOne(() => Course, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'course_id' })
  course?: Course;

}
