// Generated by scaffold-admin-crud — admin read surface over CategoryService
import { Controller, Get, Param, Query, ParseUUIDPipe, UseGuards } from '@nestjs/common';
import { ApiTags, ApiOperation } from '@nestjs/swagger';
import { JwtAuthGuard } from '../../core/guards/jwt-auth.guard';
import { RolesGuard } from '../../core/guards/roles.guard';
import { Roles } from '../../core/decorators/roles.decorator';
import { CategoryService } from './category.service';

@ApiTags('admin/categories')
@Controller('admin/categories')
@UseGuards(JwtAuthGuard, RolesGuard)
@Roles('admin', '99')
export class AdminCategoriesController {
  constructor(private readonly service: CategoryService) {}

  @Get()
  @ApiOperation({ summary: 'Admin: list all categories' })
  async list(@Query() query: Record<string, unknown>) {
    const items = await this.service.findAll();
    return { items, total: items.length };
  }

  @Get(':id')
  @ApiOperation({ summary: 'Admin: get one categories by id' })
  async detail(@Param('id', ParseUUIDPipe) id: string) {
    return this.service.findByIdOrFail(id);
  }
}
